//* Generated by bankc.
//* Do not edit this file directly.
//BRANCHAC JOB (BANKLANG),'BRANCH-ACCRUAL-CURSOR',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/BRANCH-ACCRUAL-CURSOR.cbl
//* COPYBOOK source: dist/copybooks/ACCRUAL-REQUEST.cpy
//* COPYBOOK source: dist/copybooks/ACCOUNT-ROW.cpy
//* COPYBOOK source: dist/copybooks/ACCRUAL-SUMMARY.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.BRANCHACCRUALCURSOR
//* The compile step above is a documentation-friendly skeleton.
