CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> INTEREST — InterestPostingBatch
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   RUN-BATCH, the transaction this program is entered at.
      *>   Also carries: POST-INTEREST.
      *>
      *> ENTRY
      *>   A batch program with no parameters, started by EXEC PGM in a
      *>     job.
      *>
      *> FILES
      *>   ACCOUNTF input   sequential ACCRUAL-FEED-ROW (80 bytes)
      *>   ADVICEOU output  sequential POSTING-ADVICE (62 bytes)
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>   BANKLEDG ledger posting and rollback
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>     which.
      *>   16  A sort or merge did not complete. SORT-RETURN says so.
      *>
      *> RESTART
      *>   Not restartable. Rerun from the top: the generated job
      *>     deletes a half-written output dataset rather than
      *>     cataloguing it, so there is nothing for a second run to
      *>     read as though it were complete.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. INTEREST.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT ACCOUNT-FEED-FILE ASSIGN TO ACCOUNTF
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS ACCOUNT-FEED-STATUS.
           SELECT ADVICE-OUTPUT-FILE ASSIGN TO ADVICEOU
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS ADVICE-OUTPUT-STATUS.

       DATA DIVISION.
       FILE SECTION.
       FD  ACCOUNT-FEED-FILE
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.
       01  ACCOUNT-FEED-RECORD.
           05  ACCOUNT-ID           PIC X(16).
           05  BRANCH-CODE          PIC X(8).
           05  BALANCE              PIC S9(16)V99 COMP-3.
           05  ACCRUED-INTEREST     PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
       FD  ADVICE-OUTPUT-FILE
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.
       01  ADVICE-OUTPUT-RECORD.
           05  ACCOUNT-ID           PIC X(16).
           05  INTEREST-AMOUNT      PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
       WORKING-STORAGE SECTION.
       01  ACCOUNT-FEED-STATUS  PIC X(2).
           88  ACCOUNT-FEED-STATUS-OK   VALUE "00" THRU "09".
           88  ACCOUNT-FEED-STATUS-EOF  VALUE "10".
           88  ACCOUNT-FEED-STATUS-DUPKEY VALUE "22".
           88  ACCOUNT-FEED-STATUS-NOTFND VALUE "23".
       01  ADVICE-OUTPUT-STATUS PIC X(2).
           88  ADVICE-OUTPUT-STATUS-OK  VALUE "00" THRU "09".
           88  ADVICE-OUTPUT-STATUS-EOF VALUE "10".
           88  ADVICE-OUTPUT-STATUS-DUPKEY VALUE "22".
           88  ADVICE-OUTPUT-STATUS-NOTFND VALUE "23".
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       01  BANK-RND-1-VALUE     PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-STEP      PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-UNITS     PIC S9(18) COMP-3.
       01  BANK-RND-1-EXCESS    PIC SV9(6) COMP-3.
       01  ACCRUAL-FEED-ROW.
           05  ACCOUNT-ID           PIC X(16).
           05  BRANCH-CODE          PIC X(8).
           05  BALANCE              PIC S9(16)V99 COMP-3.
           05  ACCRUED-INTEREST     PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
       01  POSTING-ADVICE.
           05  ACCOUNT-ID           PIC X(16).
           05  INTEREST-AMOUNT      PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
       01  IS-ELIGIBLE-RESULT PIC X VALUE "N".
       01  IS-ELIGIBLE-P1       PIC S9(16)V99 COMP-3.
       01  IS-ELIGIBLE-P2       PIC S9(16)V99 COMP-3.
       01  RATE-FOR-RESULT PIC S9(5)V9999 COMP-3.
       01  RATE-FOR-P1          PIC S9(16)V99 COMP-3.
       01  RATE-FOR-P2          PIC S9(16)V99 COMP-3.
       01  ACCRUE-RESULT PIC S9(16)V99 COMP-3.
       01  ACCRUE-P1            PIC S9(16)V99 COMP-3.
       01  ACCRUE-P2            PIC S9(5)V9999 COMP-3.
       01  FEE-FOR-RESULT PIC S9(16)V99 COMP-3.
       01  FEE-FOR-P1           PIC S9(16)V99 COMP-3.
       01  FEE-FOR-P2           PIC S9(16)V99 COMP-3.
       01  MINIMUM-BALANCE      PIC S9(16)V99 COMP-3.
       01  PREMIUM-THRESHOLD    PIC S9(16)V99 COMP-3.
       01  MAINTENANCE-FEE      PIC S9(16)V99 COMP-3.
       01  INTEREST             PIC S9(16)V99 COMP-3.
       01  FEE                  PIC S9(16)V99 COMP-3.
       01  RUN-BATCH-LOOP-1     PIC 9(9) COMP.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION    PIC X(6).
           05  BANK-LEDGER-ACCOUNT      PIC X(32).
           05  BANK-LEDGER-AMOUNT       PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT         PIC X(32).
           05  BANK-AUDIT-CORRELATION   PIC X(64).

       PROCEDURE DIVISION.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM RUN-BATCH THRU RUN-BATCH-EXIT
           MOVE BANK-RETURN-CODE TO RETURN-CODE
           GOBACK.
       IS-ELIGIBLE.
           IF (IS-ELIGIBLE-P1 >= IS-ELIGIBLE-P2) AND (IS-ELIGIBLE-P1 >
               0.00)
               MOVE "Y" TO IS-ELIGIBLE-RESULT
           ELSE
               MOVE "N" TO IS-ELIGIBLE-RESULT
           END-IF
           CONTINUE.
       IS-ELIGIBLE-EXIT.
           EXIT.
       RATE-FOR.
           IF RATE-FOR-P1 >= RATE-FOR-P2
               MOVE 0.0450 TO RATE-FOR-RESULT
           ELSE
               MOVE 0.0125 TO RATE-FOR-RESULT
           END-IF
           CONTINUE.
       RATE-FOR-EXIT.
           EXIT.
       ACCRUE.
           *> HALF_EVEN is generated. COBOL has
           *> only ROUNDED, which is HALF_UP.
           COMPUTE BANK-RND-1-VALUE = (ACCRUE-P1 * ACCRUE-P2)
               ON SIZE ERROR
                   DISPLAY "ARITHMETIC OVERFLOW ACCRUE-RESULT" UPON
                       SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "ARITHMETIC-OVERFLOW" TO BANK-FAILURE-CODE
                   GO TO ACCRUE-EXIT
           END-COMPUTE
           COMPUTE BANK-RND-1-EXCESS =
               (ACCRUE-P1 * ACCRUE-P2) - BANK-RND-1-VALUE
           COMPUTE BANK-RND-1-STEP = 0.01
           IF BANK-RND-1-EXCESS < 0
               COMPUTE BANK-RND-1-STEP = -0.01
           END-IF
           COMPUTE BANK-RND-1-UNITS = BANK-RND-1-VALUE * 100
           EVALUATE TRUE
               WHEN FUNCTION ABS (BANK-RND-1-EXCESS) > 0.005
                   ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
               WHEN FUNCTION ABS (BANK-RND-1-EXCESS) = 0.005
                   IF FUNCTION MOD (BANK-RND-1-UNITS, 2) = 1
                       ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
                   END-IF
           END-EVALUATE
           MOVE BANK-RND-1-VALUE TO ACCRUE-RESULT
           CONTINUE.
       ACCRUE-EXIT.
           EXIT.
       FEE-FOR.
           IF (FEE-FOR-P1 - FEE-FOR-P2) >= 0.00
               MOVE FEE-FOR-P2 TO FEE-FOR-RESULT
           ELSE
               MOVE 0.00 TO FEE-FOR-RESULT
           END-IF
           CONTINUE.
       FEE-FOR-EXIT.
           EXIT.
       POST-INTEREST.
           MOVE 100.00 TO MINIMUM-BALANCE
           MOVE 500000.00 TO PREMIUM-THRESHOLD
           MOVE 25.00 TO MAINTENANCE-FEE
           MOVE 0.00 TO INTEREST
           MOVE 0.00 TO FEE
           MOVE BALANCE OF ACCRUAL-FEED-ROW TO IS-ELIGIBLE-P1
           MOVE MINIMUM-BALANCE TO IS-ELIGIBLE-P2
           PERFORM IS-ELIGIBLE THRU IS-ELIGIBLE-EXIT
           IF BANK-FAILURE-CODE NOT = SPACES
               GO TO POST-INTEREST-EXIT
           END-IF
           IF IS-ELIGIBLE-RESULT = "Y"
               MOVE BALANCE OF ACCRUAL-FEED-ROW TO RATE-FOR-P1
               MOVE PREMIUM-THRESHOLD TO RATE-FOR-P2
               PERFORM RATE-FOR THRU RATE-FOR-EXIT
               IF BANK-FAILURE-CODE NOT = SPACES
                   GO TO POST-INTEREST-EXIT
               END-IF
               MOVE BALANCE OF ACCRUAL-FEED-ROW TO ACCRUE-P1
               MOVE RATE-FOR-RESULT TO ACCRUE-P2
               PERFORM ACCRUE THRU ACCRUE-EXIT
               IF BANK-FAILURE-CODE NOT = SPACES
                   GO TO POST-INTEREST-EXIT
               END-IF
               MOVE ACCRUE-RESULT TO INTEREST
               MOVE BALANCE OF ACCRUAL-FEED-ROW TO FEE-FOR-P1
               MOVE MAINTENANCE-FEE TO FEE-FOR-P2
               PERFORM FEE-FOR THRU FEE-FOR-EXIT
               IF BANK-FAILURE-CODE NOT = SPACES
                   GO TO POST-INTEREST-EXIT
               END-IF
               MOVE FEE-FOR-RESULT TO FEE
           ELSE
               MOVE 0.00 TO INTEREST
               MOVE 0.00 TO FEE
           END-IF
           MOVE "CREDIT" TO BANK-LEDGER-OPERATION
           MOVE ACCOUNT-ID OF ACCRUAL-FEED-ROW TO BANK-LEDGER-ACCOUNT
           MOVE INTEREST TO BANK-LEDGER-AMOUNT
           CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
           MOVE "DEBIT" TO BANK-LEDGER-OPERATION
           MOVE "INTEREST-EXPENSE" TO BANK-LEDGER-ACCOUNT
           MOVE INTEREST TO BANK-LEDGER-AMOUNT
           CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
           MOVE "DEBIT" TO BANK-LEDGER-OPERATION
           MOVE ACCOUNT-ID OF ACCRUAL-FEED-ROW TO BANK-LEDGER-ACCOUNT
           MOVE FEE TO BANK-LEDGER-AMOUNT
           CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
           MOVE "CREDIT" TO BANK-LEDGER-OPERATION
           MOVE "FEE-INCOME" TO BANK-LEDGER-ACCOUNT
           MOVE FEE TO BANK-LEDGER-AMOUNT
           CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
           MOVE ACCOUNT-ID OF ACCRUAL-FEED-ROW TO ACCOUNT-ID OF
               POSTING-ADVICE
           MOVE INTEREST TO INTEREST-AMOUNT OF POSTING-ADVICE
           MOVE IDEMPOTENCY-KEY OF ACCRUAL-FEED-ROW TO IDEMPOTENCY-KEY
               OF POSTING-ADVICE
           MOVE "INTEREST_POSTED" TO BANK-AUDIT-EVENT
           MOVE IDEMPOTENCY-KEY OF ACCRUAL-FEED-ROW TO
               BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       POST-INTEREST-EXIT.
           EXIT.
       RUN-BATCH.
           OPEN INPUT ACCOUNT-FEED-FILE
           IF NOT ACCOUNT-FEED-STATUS-OK
               DISPLAY "OPEN FAILED accountFeed STATUS "
                   ACCOUNT-FEED-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO RUN-BATCH-EXIT
           END-IF
           OPEN OUTPUT ADVICE-OUTPUT-FILE
           IF NOT ADVICE-OUTPUT-STATUS-OK
               DISPLAY "OPEN FAILED adviceOutput STATUS "
                   ADVICE-OUTPUT-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO RUN-BATCH-EXIT
           END-IF
           MOVE 0 TO RUN-BATCH-LOOP-1
           PERFORM UNTIL RUN-BATCH-LOOP-1 >= 100000 OR NOT
               (ACCOUNT-FEED-STATUS = "00")
               ADD 1 TO RUN-BATCH-LOOP-1
               READ ACCOUNT-FEED-FILE
                   AT END MOVE "10" TO ACCOUNT-FEED-STATUS
                   NOT AT END
                       MOVE ACCOUNT-ID OF ACCOUNT-FEED-RECORD TO
                           ACCOUNT-ID OF ACCRUAL-FEED-ROW
                       MOVE BRANCH-CODE OF ACCOUNT-FEED-RECORD TO
                           BRANCH-CODE OF ACCRUAL-FEED-ROW
                       MOVE BALANCE OF ACCOUNT-FEED-RECORD TO BALANCE OF
                           ACCRUAL-FEED-ROW
                       MOVE ACCRUED-INTEREST OF ACCOUNT-FEED-RECORD TO
                           ACCRUED-INTEREST OF ACCRUAL-FEED-ROW
                       MOVE IDEMPOTENCY-KEY OF ACCOUNT-FEED-RECORD TO
                           IDEMPOTENCY-KEY OF ACCRUAL-FEED-ROW
               END-READ
               IF NOT ACCOUNT-FEED-STATUS-OK AND NOT
                   ACCOUNT-FEED-STATUS-EOF
                   DISPLAY "READ FAILED accountFeed STATUS "
                       ACCOUNT-FEED-STATUS UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "READ-FAILED" TO BANK-FAILURE-CODE
                   GO TO RUN-BATCH-EXIT
               END-IF
               IF ACCOUNT-FEED-STATUS = "00"
                   MOVE ACCOUNT-ID OF POSTING-ADVICE TO ACCOUNT-ID OF
                       ADVICE-OUTPUT-RECORD
                   MOVE INTEREST-AMOUNT OF POSTING-ADVICE TO
                       INTEREST-AMOUNT OF ADVICE-OUTPUT-RECORD
                   MOVE IDEMPOTENCY-KEY OF POSTING-ADVICE TO
                       IDEMPOTENCY-KEY OF ADVICE-OUTPUT-RECORD
                   WRITE ADVICE-OUTPUT-RECORD
                   IF NOT ADVICE-OUTPUT-STATUS-OK
                       DISPLAY "WRITE FAILED adviceOutput STATUS "
                           ADVICE-OUTPUT-STATUS UPON SYSOUT
                       MOVE 12 TO BANK-RETURN-CODE
                       MOVE "WRITE-FAILED" TO BANK-FAILURE-CODE
                       GO TO RUN-BATCH-EXIT
                   END-IF
               END-IF
           END-PERFORM
           IF RUN-BATCH-LOOP-1 >= 100000 AND (ACCOUNT-FEED-STATUS =
               "00")
               DISPLAY "LOOP LIMIT 100000 REACHED, WORK UNFINISHED" UPON
                   SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "BANK-LOOP-EXHAUSTED" TO BANK-FAILURE-CODE
               GO TO RUN-BATCH-EXIT
           END-IF
           CLOSE ACCOUNT-FEED-FILE
           IF NOT ACCOUNT-FEED-STATUS-OK
               DISPLAY "CLOSE FAILED accountFeed STATUS "
                   ACCOUNT-FEED-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO RUN-BATCH-EXIT
           END-IF
           CLOSE ADVICE-OUTPUT-FILE
           IF NOT ADVICE-OUTPUT-STATUS-OK
               DISPLAY "CLOSE FAILED adviceOutput STATUS "
                   ADVICE-OUTPUT-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO RUN-BATCH-EXIT
           END-IF
           MOVE "INTEREST_BATCH_COMPLETED" TO BANK-AUDIT-EVENT
           MOVE IDEMPOTENCY-KEY OF ACCRUAL-FEED-ROW TO
               BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       RUN-BATCH-EXIT.
           EXIT.
