*> Generated by bankc.
*> Do not edit this file directly.
01  POSTING-ADVICE.
    05  ACCOUNT-ID           PIC X(16).
    05  INTEREST-AMOUNT      PIC S9(16)V99 COMP-3.
    05  IDEMPOTENCY-KEY      PIC X(36).
