//* Generated by bankc. Do not edit this file directly.
//ACCOUNTT JOB (BANKLANG),'ACCOUNT-TRANSFER',
//             CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID,REGION=0M
//* Compile and link-edit the generated library. It has no entry point.
//* Source member:   BANKLANG.COBOL(ACCOUNTT)
//* Load module:     BANKLANG.LOADLIB(ACCOUNTT)
//* Dataset names, unit and space parameters are placeholders for a
//* site's own standards. See docs/jcl-model.md.
//* IGYWCL is IBM's compile-and-link cataloged procedure. It supplies
//* STEPLIB, SYSUT1-SYSUT15, SYSMDECK, the LE link libraries, and
//* REGION=0M. Only the site-specific DDs are overridden here.
//* PGMLIB must name a load library that already exists: the
//* procedure allocates SYSLMOD DISP=(MOD,PASS), so a library that
//* does not exist is created, passed, and gone at end of job.
//COMPILE  EXEC IGYWCL,
//             LNGPRFX='IGY.V6R4M0',LIBPRFX='CEE',
//             PGMLIB='BANKLANG.LOADLIB',GOPGM=ACCOUNTT
//COBOL.SYSIN    DD DISP=SHR,DSN=BANKLANG.COBOL(ACCOUNTT)
//LKED.SYSLIB    DD DISP=SHR,DSN=BANKLANG.OBJLIB
//               DD DISP=SHR,DSN=CEE.SCEELKEX
//               DD DISP=SHR,DSN=CEE.SCEELKED
//* No run step: this module declares no transaction, so nothing in it
//* is an entry point. It is compiled and link-edited into the load
//* library so a caller can be bound against ACCOUNTT, and it is
//* that caller's job step that runs.
