//* Generated by bankc.
//* Do not edit this file directly.
//ACCOUNTT JOB (BANKLANG),'ACCOUNT-TRANSFER',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/ACCOUNT-TRANSFER.cbl
//* COPYBOOK source: dist/copybooks/TRANSFER-REQUEST.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.ACCOUNTTRANSFER
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(ACCOUNTT)
//RUN      EXEC PGM=ACCOUNTT
//SYSOUT   DD SYSOUT=*
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the load library name are
//* placeholders for an installation's own standards.
