*> Generated by bankc.
*> Do not edit this file directly.
01  SAVINGS-ACCOUNT.
    05  ACCOUNT-ID           PIC X(16).
    05  BALANCE              PIC S9(16)V99 COMP-3.
    05  IDEMPOTENCY-KEY      PIC X(36).
    05  MINIMUM-BALANCE      PIC S9(16)V99 COMP-3.
    05  REQUESTED            PIC S9(16)V99 COMP-3.
