CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> ONLINEEN — OnlineEnquiry
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   ACCOUNT-ENQUIRY, the transaction this program is entered at.
      *>
      *> ENTRY
      *>   A CICS transaction, started by a transaction identifier in a
      *>     region rather than by EXEC PGM in a job.
      *>   DFHCOMMAREA holds ENQUIRY-REQUEST, and EIBCALEN is tested
      *>     against its length before anything reads it.
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  Not used under CICS. A failure abends the task with code
      *>     BLNG.
      *>
      *> RESTART
      *>   Rerunnable. The program writes no dataset.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ONLINEEN.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
           EXEC SQL INCLUDE SQLCA END-EXEC.
           EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01  FETCH-ACCOUNT-H1     PIC X(16).
           EXEC SQL END DECLARE SECTION END-EXEC.
       01  LINK-RESP            PIC S9(8) COMP.
       01  COMMIT-RESP          PIC S9(8) COMP.
       01  ROLLBACK-RESP        PIC S9(8) COMP.
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       01  ENQUIRY-REQUEST.
           05  ACCOUNT-ID           PIC X(16).
           05  REQUESTED-BY         PIC X(20).
           05  IDEMPOTENCY-KEY      PIC X(36).
           EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01  ACCOUNT-BALANCE-ROW.
           05  ROW-ACCOUNT-ID       PIC X(16).
           05  ROW-BALANCE          PIC S9(16)V99 COMP-3.
           05  ROW-STATUS           PIC X(8).
           EXEC SQL END DECLARE SECTION END-EXEC.
       01  BALANCE-REPLY.
           05  REPLY-ACCOUNT-ID     PIC X(16).
           05  REPLY-BALANCE        PIC S9(16)V99 COMP-3.
           05  OUTCOME              PIC X(14).
               88  OUTCOME-FOUND                VALUE "FOUND".
               88  OUTCOME-NOT-FOUND            VALUE "NOT_FOUND".
               88  OUTCOME-UNAVAILABLE          VALUE "UNAVAILABLE".
               88  OUTCOME-UNAVAILABLE-DB       VALUE "UNAVAILABLE_DB".
       01  IS-AVAILABLE-RESULT PIC X(1) VALUE "N".
       01  IS-AVAILABLE-P1      PIC X(8).
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION    PIC X(6).
           05  BANK-LEDGER-ACCOUNT      PIC X(32).
           05  BANK-LEDGER-AMOUNT       PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT         PIC X(32).
           05  BANK-AUDIT-CORRELATION   PIC X(64).

       LINKAGE SECTION.
       01  DFHCOMMAREA.
           05  LK-ACCOUNT-ID        PIC X(16).
           05  LK-REQUESTED-BY      PIC X(20).
           05  LK-IDEMPOTENCY-KEY   PIC X(36).

       PROCEDURE DIVISION.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM ACCOUNT-ENQUIRY THRU ACCOUNT-ENQUIRY-EXIT
           IF BANK-RETURN-CODE NOT = 0
               EXEC CICS ABEND ABCODE("BLNG") END-EXEC
           END-IF
           EXEC CICS RETURN END-EXEC
           GOBACK.
       IS-AVAILABLE.
           IF IS-AVAILABLE-P1 = "OPEN"
               MOVE "Y" TO IS-AVAILABLE-RESULT
           ELSE
               MOVE "N" TO IS-AVAILABLE-RESULT
           END-IF
           CONTINUE.
       IS-AVAILABLE-EXIT.
           EXIT.
       ACCOUNT-ENQUIRY.
           IF EIBCALEN < LENGTH OF DFHCOMMAREA
               EXEC CICS ABEND ABCODE("BKNC") END-EXEC
           END-IF
           MOVE DFHCOMMAREA TO ENQUIRY-REQUEST
           MOVE ACCOUNT-ID OF ENQUIRY-REQUEST TO FETCH-ACCOUNT-H1
           EXEC SQL
               SELECT ACCOUNT_ID, BALANCE, STATUS
               INTO :ROW-ACCOUNT-ID OF ACCOUNT-BALANCE-ROW, :ROW-BALANCE
                   OF ACCOUNT-BALANCE-ROW, :ROW-STATUS OF
                   ACCOUNT-BALANCE-ROW
               FROM ACCOUNT
               WHERE ACCOUNT_ID = :FETCH-ACCOUNT-H1
           END-EXEC
           IF SQLCODE < 0
               SET OUTCOME-UNAVAILABLE-DB OF BALANCE-REPLY TO TRUE
           ELSE
               IF SQLCODE = 0
                   MOVE ROW-ACCOUNT-ID OF ACCOUNT-BALANCE-ROW TO
                       REPLY-ACCOUNT-ID OF BALANCE-REPLY
                   MOVE ROW-BALANCE OF ACCOUNT-BALANCE-ROW TO
                       REPLY-BALANCE OF BALANCE-REPLY
                   MOVE ROW-STATUS OF ACCOUNT-BALANCE-ROW TO
                       IS-AVAILABLE-P1
                   PERFORM IS-AVAILABLE THRU IS-AVAILABLE-EXIT
                   IF BANK-FAILURE-CODE NOT = SPACES
                       GO TO ACCOUNT-ENQUIRY-EXIT
                   END-IF
                   IF IS-AVAILABLE-RESULT = "Y"
                       SET OUTCOME-FOUND OF BALANCE-REPLY TO TRUE
                   ELSE
                       SET OUTCOME-UNAVAILABLE OF BALANCE-REPLY TO TRUE
                   END-IF
               ELSE
                   SET OUTCOME-NOT-FOUND OF BALANCE-REPLY TO TRUE
               END-IF
           END-IF
           EXEC CICS LINK PROGRAM("AUDITLOG") COMMAREA(BALANCE-REPLY)
               RESP(LINK-RESP) END-EXEC
           IF (LINK-RESP = DFHRESP(NORMAL)) AND (SQLCODE >= 0)
               EXEC CICS SYNCPOINT RESP(COMMIT-RESP) END-EXEC
           ELSE
               EXEC CICS SYNCPOINT ROLLBACK RESP(ROLLBACK-RESP) END-EXEC
           END-IF
           MOVE "ENQUIRY_COMPLETED" TO BANK-AUDIT-EVENT
           MOVE IDEMPOTENCY-KEY OF ENQUIRY-REQUEST TO
               BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           MOVE ENQUIRY-REQUEST TO DFHCOMMAREA
           CONTINUE.
       ACCOUNT-ENQUIRY-EXIT.
           EXIT.
