       *> Generated by bankc.
       *> Do not edit this file directly.
       01  INSTALMENT.
           05  DUE-BALANCE          PIC S9(16)V99 COMP-3.
           05  INTEREST-DUE         PIC S9(16)V99 COMP-3.
