*> Generated by bankc.
*> Do not edit this file directly.
01  LOAN.
    05  ACCOUNT-ID           PIC X(16).
    05  PRINCIPAL            PIC S9(16)V99 COMP-3.
    05  MONTHLY-RATE         PIC S9(5)V9999 COMP-3.
    05  TERM-MONTHS          PIC S9(9) COMP-3.
    05  SCHEDULE             GROUP.
    05  IDEMPOTENCY-KEY      PIC X(36).
