CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> BRANCHAC — BranchAccrualCursor
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   ACCRUE-BRANCH, the transaction this program is entered at.
      *>
      *> ENTRY
      *>   A batch program with no parameters, started by EXEC PGM in a
      *>   job.
      *>
      *> FILES
      *>   SUMMARYO output  sequential ACCRUAL-SUMMARY (64 bytes)
      *>   RESTARTF update  indexed    RESTART-POINT (24 bytes)
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>   BANKLEDG ledger posting and rollback
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>       which.
      *>   16  A sort or merge did not complete. SORT-RETURN says so.
      *>
      *> RESTART
      *>   Restartable. The position is written to RESTART-FILE and
      *>   committed after the work it covers, so a rerun resumes from
      *>   the last checkpoint.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. BRANCHAC.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT SUMMARY-OUTPUT-FILE ASSIGN TO SUMMARYO
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS SUMMARY-STATUS.
           SELECT OPTIONAL RESTART-FILE-FILE ASSIGN TO RESTARTF
               ORGANIZATION IS INDEXED
               ACCESS MODE IS DYNAMIC
               RECORD KEY IS JOB-NAME OF RESTART-FILE-RECORD
               FILE STATUS IS RESTART-STATUS.

       DATA DIVISION.
       FILE SECTION.
       FD  SUMMARY-OUTPUT-FILE
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.
       01  SUMMARY-OUTPUT-RECORD.
           05  SUMMARY-BRANCH-ID  PIC X(8).
           05  ACCOUNTS-READ      PIC S9(9) COMP-3.
           05  ACCOUNTS-ACCRUED   PIC S9(9) COMP-3.
           05  INTEREST-POSTED    PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY    PIC X(36).
       FD  RESTART-FILE-FILE.
       01  RESTART-FILE-RECORD.
           05  JOB-NAME         PIC X(8).
           05  LAST-ACCOUNT-ID  PIC X(16).
       WORKING-STORAGE SECTION.
           EXEC SQL INCLUDE SQLCA END-EXEC.
           EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01  ACCOUNTS-IN-BRANCH-H1    PIC X(8).
       01  ACCOUNTS-IN-BRANCH-H2    PIC X(16).
           EXEC SQL END DECLARE SECTION END-EXEC.
       01  ACCOUNTS-IN-BRANCH-ROWS  PIC 9(9) COMP VALUE ZERO.
       01  SUMMARY-STATUS           PIC X(2) VALUE SPACES.
           88  SUMMARY-STATUS-OK      VALUE "00" THRU "09".
           88  SUMMARY-STATUS-EOF     VALUE "10".
           88  SUMMARY-STATUS-DUPKEY  VALUE "22".
           88  SUMMARY-STATUS-NOTFND  VALUE "23".
       01  RESTART-STATUS           PIC X(2) VALUE SPACES.
           88  RESTART-STATUS-OK      VALUE "00" THRU "09".
           88  RESTART-STATUS-EOF     VALUE "10".
           88  RESTART-STATUS-DUPKEY  VALUE "22".
           88  RESTART-STATUS-NOTFND  VALUE "23".
       01  RESTART-FILE-CP-COUNT    PIC 9(9) COMP VALUE ZERO.
       01  RESTART-FILE-RS-FOUND    PIC X(1) VALUE "N".
       01  BANK-FAILURE-CODE        PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE         PIC S9(4) COMP EXTERNAL.
       01  BANK-RND-1-VALUE         PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  BANK-RND-1-STEP          PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  BANK-RND-1-UNITS         PIC S9(18) COMP-3 VALUE ZERO.
       01  BANK-RND-1-EXCESS        PIC SV9999 COMP-3 VALUE ZERO.
       01  ACCRUAL-REQUEST.
           05  BRANCH-ID        PIC X(8).
           05  ACCRUAL-RATE     PIC S9(1)V9999 COMP-3.
           05  IDEMPOTENCY-KEY  PIC X(36).
           EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01  ACCOUNT-BALANCE-ROW.
           05  ROW-ACCOUNT-ID  PIC X(16).
           05  ROW-BALANCE     PIC S9(16)V99 COMP-3.
           05  ROW-STATUS      PIC X(8).
           EXEC SQL END DECLARE SECTION END-EXEC.
       01  ACCRUAL-SUMMARY.
           05  SUMMARY-BRANCH-ID  PIC X(8).
           05  ACCOUNTS-READ      PIC S9(9) COMP-3.
           05  ACCOUNTS-ACCRUED   PIC S9(9) COMP-3.
           05  INTEREST-POSTED    PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY    PIC X(36).
       01  RESTART-POINT.
           05  JOB-NAME         PIC X(8).
           05  LAST-ACCOUNT-ID  PIC X(16).
       01  INTEREST-ON-RESULT       PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  INTEREST-ON-P1           PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  INTEREST-ON-P2           PIC S9(1)V9999 COMP-3 VALUE ZERO.
       01  INTEREST                 PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION  PIC X(6).
           05  BANK-LEDGER-ACCOUNT    PIC X(32).
           05  BANK-LEDGER-AMOUNT     PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT        PIC X(32).
           05  BANK-AUDIT-CORRELATION  PIC X(64).
           EXEC SQL
               DECLARE ACCOUNTS-IN-BRANCH CURSOR WITH HOLD FOR
               SELECT ACCOUNT_ID, BALANCE, STATUS
               FROM ACCOUNT
               WHERE BRANCH_ID = :ACCOUNTS-IN-BRANCH-H1
               AND ACCOUNT_ID > :ACCOUNTS-IN-BRANCH-H2
               ORDER BY ACCOUNT_ID
           END-EXEC.

       PROCEDURE DIVISION.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM ACCRUE-BRANCH THRU ACCRUE-BRANCH-EXIT
           MOVE BANK-RETURN-CODE TO RETURN-CODE
           GOBACK.
       INTEREST-ON.
           *> HALF_EVEN is generated. COBOL has
           *> only ROUNDED, which is HALF_UP.
           COMPUTE BANK-RND-1-VALUE = (INTEREST-ON-P1 * INTEREST-ON-P2)
               ON SIZE ERROR
                   DISPLAY "ARITHMETIC OVERFLOW INTEREST-ON-RESULT" UPON
                       SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "ARITHMETIC-OVERFLOW" TO BANK-FAILURE-CODE
                   GO TO INTEREST-ON-EXIT
           END-COMPUTE
           COMPUTE BANK-RND-1-EXCESS =
               (INTEREST-ON-P1 * INTEREST-ON-P2) - BANK-RND-1-VALUE
           COMPUTE BANK-RND-1-STEP = 0.01
           IF BANK-RND-1-EXCESS < 0
               COMPUTE BANK-RND-1-STEP = -0.01
           END-IF
           COMPUTE BANK-RND-1-UNITS = BANK-RND-1-VALUE * 100
           EVALUATE TRUE
               WHEN FUNCTION ABS (BANK-RND-1-EXCESS) > 0.005
                   ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
               WHEN FUNCTION ABS (BANK-RND-1-EXCESS) = 0.005
                   IF FUNCTION MOD (BANK-RND-1-UNITS, 2) = 1
                       ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
                   END-IF
           END-EVALUATE
           MOVE BANK-RND-1-VALUE TO INTEREST-ON-RESULT
           CONTINUE.
       INTEREST-ON-EXIT.
           EXIT.
       ACCRUE-BRANCH.
           MOVE BRANCH-ID OF ACCRUAL-REQUEST TO SUMMARY-BRANCH-ID OF
               ACCRUAL-SUMMARY
           MOVE IDEMPOTENCY-KEY OF ACCRUAL-REQUEST TO IDEMPOTENCY-KEY OF
               ACCRUAL-SUMMARY
           OPEN I-O RESTART-FILE-FILE
           IF NOT RESTART-STATUS-OK
               DISPLAY "OPEN FAILED restartFile STATUS " RESTART-STATUS
                   UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO ACCRUE-BRANCH-EXIT
           END-IF
           MOVE "BRACCRUE" TO JOB-NAME OF RESTART-POINT
           MOVE JOB-NAME OF RESTART-POINT TO JOB-NAME OF
               RESTART-FILE-RECORD
           MOVE "N" TO RESTART-FILE-RS-FOUND
           READ RESTART-FILE-FILE
               INVALID KEY CONTINUE
               NOT INVALID KEY MOVE "Y" TO RESTART-FILE-RS-FOUND
           END-READ
           IF RESTART-FILE-RS-FOUND = "Y"
               MOVE JOB-NAME OF RESTART-FILE-RECORD TO JOB-NAME OF
                   RESTART-POINT
               MOVE LAST-ACCOUNT-ID OF RESTART-FILE-RECORD TO
                   LAST-ACCOUNT-ID OF RESTART-POINT
               DISPLAY "RESUMING AFTER " LAST-ACCOUNT-ID OF
                   RESTART-POINT UPON SYSOUT
           ELSE
               DISPLAY "STARTING FROM THE TOP" UPON SYSOUT
           END-IF
           MOVE BRANCH-ID OF ACCRUAL-REQUEST TO ACCOUNTS-IN-BRANCH-H1
           MOVE LAST-ACCOUNT-ID OF RESTART-POINT TO
               ACCOUNTS-IN-BRANCH-H2
           EXEC SQL
               OPEN ACCOUNTS-IN-BRANCH
           END-EXEC
           MOVE 0 TO ACCOUNTS-IN-BRANCH-ROWS
           PERFORM UNTIL ACCOUNTS-IN-BRANCH-ROWS >= 5000
               EXEC SQL
                   FETCH ACCOUNTS-IN-BRANCH
                   INTO :ROW-ACCOUNT-ID OF ACCOUNT-BALANCE-ROW,
                       :ROW-BALANCE OF ACCOUNT-BALANCE-ROW, :ROW-STATUS
                       OF ACCOUNT-BALANCE-ROW
               END-EXEC
               IF SQLCODE < 0
                   DISPLAY "FETCH FAILED accountsInBranch SQLCODE "
                       SQLCODE UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "SQL-FETCH-FAILED" TO BANK-FAILURE-CODE
               END-IF
               IF SQLCODE NOT = 0
                   EXIT PERFORM
               END-IF
               ADD 1 TO ACCOUNTS-IN-BRANCH-ROWS
               COMPUTE ACCOUNTS-READ OF ACCRUAL-SUMMARY = (ACCOUNTS-READ
                   OF ACCRUAL-SUMMARY + 1)
                   ON SIZE ERROR
                       DISPLAY
                           "ARITHMETIC OVERFLOW ACCOUNTS-READ OF ACCRUAL
      -                    "-SUMMARY" UPON SYSOUT
                       MOVE 12 TO BANK-RETURN-CODE
                       MOVE "ARITHMETIC-OVERFLOW" TO BANK-FAILURE-CODE
                       GO TO ACCRUE-BRANCH-EXIT
               END-COMPUTE
               IF ROW-STATUS OF ACCOUNT-BALANCE-ROW = "OPEN"
                   MOVE ROW-BALANCE OF ACCOUNT-BALANCE-ROW TO
                       INTEREST-ON-P1
                   MOVE ACCRUAL-RATE OF ACCRUAL-REQUEST TO
                       INTEREST-ON-P2
                   PERFORM INTEREST-ON THRU INTEREST-ON-EXIT
                   IF BANK-FAILURE-CODE NOT = SPACES
                       GO TO ACCRUE-BRANCH-EXIT
                   END-IF
                   MOVE INTEREST-ON-RESULT TO INTEREST
                   MOVE "CREDIT" TO BANK-LEDGER-OPERATION
                   MOVE ROW-ACCOUNT-ID OF ACCOUNT-BALANCE-ROW TO
                       BANK-LEDGER-ACCOUNT
                   MOVE INTEREST TO BANK-LEDGER-AMOUNT
                   CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
                   MOVE "DEBIT" TO BANK-LEDGER-OPERATION
                   MOVE "INTEREST-EXPENSE" TO BANK-LEDGER-ACCOUNT
                   MOVE INTEREST TO BANK-LEDGER-AMOUNT
                   CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
                   COMPUTE ACCOUNTS-ACCRUED OF ACCRUAL-SUMMARY =
                       (ACCOUNTS-ACCRUED OF ACCRUAL-SUMMARY + 1)
                       ON SIZE ERROR
                           DISPLAY
                               "ARITHMETIC OVERFLOW ACCOUNTS-ACCRUED OF 
      -                        "ACCRUAL-SUMMARY" UPON SYSOUT
                           MOVE 12 TO BANK-RETURN-CODE
                           MOVE "ARITHMETIC-OVERFLOW" TO
                               BANK-FAILURE-CODE
                           GO TO ACCRUE-BRANCH-EXIT
                   END-COMPUTE
                   COMPUTE INTEREST-POSTED OF ACCRUAL-SUMMARY =
                       (INTEREST-POSTED OF ACCRUAL-SUMMARY + INTEREST)
                       ON SIZE ERROR
                           DISPLAY
                               "ARITHMETIC OVERFLOW INTEREST-POSTED OF A
      -                        "CCRUAL-SUMMARY" UPON SYSOUT
                           MOVE 12 TO BANK-RETURN-CODE
                           MOVE "ARITHMETIC-OVERFLOW" TO
                               BANK-FAILURE-CODE
                           GO TO ACCRUE-BRANCH-EXIT
                   END-COMPUTE
               END-IF
               MOVE ROW-ACCOUNT-ID OF ACCOUNT-BALANCE-ROW TO
                   LAST-ACCOUNT-ID OF RESTART-POINT
               ADD 1 TO RESTART-FILE-CP-COUNT
               IF RESTART-FILE-CP-COUNT >= 100
                   MOVE 0 TO RESTART-FILE-CP-COUNT
                   MOVE JOB-NAME OF RESTART-POINT TO JOB-NAME OF
                       RESTART-FILE-RECORD
                   MOVE LAST-ACCOUNT-ID OF RESTART-POINT TO
                       LAST-ACCOUNT-ID OF RESTART-FILE-RECORD
                   WRITE RESTART-FILE-RECORD
                       INVALID KEY REWRITE RESTART-FILE-RECORD
                   END-WRITE
                   EXEC SQL COMMIT END-EXEC
               END-IF
           END-PERFORM
           IF ACCOUNTS-IN-BRANCH-ROWS >= 5000 AND SQLCODE = 0
               DISPLAY "CURSOR LIMIT 5000 REACHED, ROWS UNREAD" UPON
                   SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "BANK-LOOP-EXHAUSTED" TO BANK-FAILURE-CODE
           END-IF
           EXEC SQL
               CLOSE ACCOUNTS-IN-BRANCH
           END-EXEC
           IF BANK-FAILURE-CODE NOT = SPACES
               GO TO ACCRUE-BRANCH-EXIT
           END-IF
           CLOSE RESTART-FILE-FILE
           IF NOT RESTART-STATUS-OK
               DISPLAY "CLOSE FAILED restartFile STATUS " RESTART-STATUS
                   UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO ACCRUE-BRANCH-EXIT
           END-IF
           OPEN OUTPUT SUMMARY-OUTPUT-FILE
           IF NOT SUMMARY-STATUS-OK
               DISPLAY "OPEN FAILED summaryOutput STATUS "
                   SUMMARY-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO ACCRUE-BRANCH-EXIT
           END-IF
           MOVE SUMMARY-BRANCH-ID OF ACCRUAL-SUMMARY TO
               SUMMARY-BRANCH-ID OF SUMMARY-OUTPUT-RECORD
           MOVE ACCOUNTS-READ OF ACCRUAL-SUMMARY TO ACCOUNTS-READ OF
               SUMMARY-OUTPUT-RECORD
           MOVE ACCOUNTS-ACCRUED OF ACCRUAL-SUMMARY TO ACCOUNTS-ACCRUED
               OF SUMMARY-OUTPUT-RECORD
           MOVE INTEREST-POSTED OF ACCRUAL-SUMMARY TO INTEREST-POSTED OF
               SUMMARY-OUTPUT-RECORD
           MOVE IDEMPOTENCY-KEY OF ACCRUAL-SUMMARY TO IDEMPOTENCY-KEY OF
               SUMMARY-OUTPUT-RECORD
           WRITE SUMMARY-OUTPUT-RECORD
           IF NOT SUMMARY-STATUS-OK
               DISPLAY "WRITE FAILED summaryOutput STATUS "
                   SUMMARY-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "WRITE-FAILED" TO BANK-FAILURE-CODE
               GO TO ACCRUE-BRANCH-EXIT
           END-IF
           CLOSE SUMMARY-OUTPUT-FILE
           IF NOT SUMMARY-STATUS-OK
               DISPLAY "CLOSE FAILED summaryOutput STATUS "
                   SUMMARY-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO ACCRUE-BRANCH-EXIT
           END-IF
           MOVE "BRANCH_ACCRUAL_COMPLETED" TO BANK-AUDIT-EVENT
           MOVE IDEMPOTENCY-KEY OF ACCRUAL-REQUEST TO
               BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       ACCRUE-BRANCH-EXIT.
           EXIT.
