import { describe, expect, it } from "vitest";

import { compile } from "../packages/compiler/src/index";
import { compileExample, flowed } from "./helpers";

/**
 * What makes a generated program read as one.
 *
 * None of this is wrong COBOL. All of it is why a reviewer says "this was
 * generated" instead of "this is fine", and the 2026-08-05 audit listed twelve
 * of them. A compiler whose whole claim is that its output goes into
 * production has to produce output a production reviewer accepts.
 */

const PREAMBLE = `module Style;

type BDT = currency<"BDT", 18, 2>;

record Account {
  accountId: string<16>;
  balance: BDT;
  idempotencyKey: string<36>;
}
`;

describe("the program prologue", () => {
  const { emit } = compileExample("examples/account-file-batch");
  const prologue = emit.cobol.slice(0, emit.cobol.indexOf("IDENTIFICATION"));

  it("names the program and what it is entered at", () => {
    expect(prologue).toContain("ACCOUNTF — AccountFileBatch");
    expect(prologue).toContain("POST-ACCOUNTS, the transaction");
  });

  /** What an operator needs when the job abends on an allocation. */
  it("tables every file under the DD name the program assigns to", () => {
    expect(prologue).toContain("FILES");
    expect(prologue).toContain("ACCOUNTI input   sequential ACCOUNT-RECORD");
    expect(prologue).toContain("POSTINGO output  sequential POSTING-RECORD");
  });

  /** What the binder has to resolve, and what the next step's COND= means. */
  it("names the modules it calls and the codes it can end with", () => {
    expect(prologue).toContain("CALLS");
    expect(prologue).toContain("BANKAUDT audit trail");
    expect(prologue).toContain("RETURN CODES");
    expect(prologue).toContain("0   The work completed.");
    expect(prologue).toContain("12  A failure the program named.");
  });

  /** What somebody decides at 3am. */
  it("says whether a rerun is safe", () => {
    expect(prologue).toContain("RESTART");
    expect(prologue).toContain("Not restartable. Rerun from the top");
  });

  /**
   * The path the compiler happened to be given is this machine's. A bundle
   * holding one cannot be reproduced anywhere else, which is the whole claim a
   * deterministic compiler makes.
   */
  it("names the source file without the path it was compiled from", () => {
    expect(prologue).toContain("Generated by bankc from main.bank.ts.");
    expect(prologue).not.toContain("/Users/");
  });
});

describe("the statements a copy becomes", () => {
  /**
   * `COMPUTE X = Y` is legal and does the same thing as `MOVE Y TO X`. It reads
   * to a COBOL programmer as arithmetic that turned out to have nothing in it.
   */
  const COPY = `${PREAMBLE}
record Mirror {
  mirrored: BDT;
}
`;

  it("moves rather than computing when there is no arithmetic", () => {
    const result = compile(`${COPY}
entry transaction go(account: Account, mirror: Mirror) {
  mirror.mirrored = account.balance;
  audit("DONE", account.idempotencyKey);
}`);

    expect(result.diagnostics).toEqual([]);
    expect(result.cobol).toContain(
      "MOVE BALANCE OF ACCOUNT TO MIRRORED OF MIRROR",
    );
    expect(result.cobol).not.toContain("COMPUTE MIRRORED OF MIRROR");
  });

  it("still computes, and still guards, when there is", () => {
    const result = compile(`${COPY}
entry transaction go(account: Account, mirror: Mirror) {
  mirror.mirrored = account.balance + account.balance;
  audit("DONE", account.idempotencyKey);
}`);

    expect(result.diagnostics).toEqual([]);
    expect(result.cobol).toContain("COMPUTE MIRRORED OF MIRROR");
    expect(result.cobol).toContain("ON SIZE ERROR");
  });
});

describe("the file status key", () => {
  const result = compile(`${PREAMBLE}
file feed sequential input record Account status feedStatus;

entry transaction go(account: Account) {
  open feed;
  read feed into account;
  close feed;
  audit("DONE", account.idempotencyKey);
}`);

  /**
   * The language has 88-levels for exactly this, the emitter already uses them
   * for enums, and file status is where they matter most: it is the one field a
   * batch program's whole error model runs through.
   */
  it("is read through condition names rather than reference modification", () => {
    expect(result.cobol).toContain(
      '88  FEED-STATUS-OK           VALUE "00" THRU "09".',
    );
    expect(result.cobol).toContain('88  FEED-STATUS-EOF          VALUE "10".');
    expect(flowed(result.cobol)).toContain(
      "IF NOT FEED-STATUS-OK AND NOT FEED-STATUS-EOF",
    );
    expect(result.cobol).not.toContain("FEED-STATUS(1:1)");
  });

  /**
   * `BLOCK CONTAINS 0 RECORDS` asks for a system-determined block size, which
   * is what the generated job's `BLKSIZE=0` is the other half of. Without
   * either the file defaults to unblocked, and an unblocked dataset of short
   * records wastes most of a track.
   */
  it("describes the dataset the FD is for", () => {
    expect(result.cobol).toContain("BLOCK CONTAINS 0 RECORDS");
    expect(result.cobol).toContain("RECORDING MODE IS F");
  });

  it("says V when the record varies", () => {
    const varying = compile(`module Varying;

record Line { payload: string<80>; }
record Note { idempotencyKey: string<36>; }

file feed sequential output record Line
  varying 10 to 80 length feedLength status feedStatus;

entry transaction go(line: Line, note: Note) {
  open feed;
  close feed;
  audit("DONE", note.idempotencyKey);
}`);

    expect(varying.cobol).toContain("RECORDING MODE IS V");
  });
});

describe("one delimiter", () => {
  /**
   * `'N'` and `"0"` in one program is two conventions where there should be
   * none, and the `CBL` statement the program opens with states `QUOTE`.
   */
  it("writes every literal with the delimiter the CBL statement names", () => {
    const result = compile(`${PREAMBLE}
entry transaction go(account: Account, flag: bool) {
  if flag {
    audit("YES", account.idempotencyKey);
  } else {
    audit("NO", account.idempotencyKey);
  }
}`);

    expect(result.cobol).toContain("QUOTE");
    expect(result.cobol).not.toMatch(/'[A-Z0-9]'/);
  });
});

describe("generated names", () => {
  /**
   * `WS-LOOP-34-3` renamed itself when somebody added a blank line above it, so
   * a diff of two generated programs showed every reference changing and a name
   * in a dump said nothing about which loop it belonged to.
   */
  it("carry the routine and an ordinal, not a source position", () => {
    const result = compile(`${PREAMBLE}
entry transaction go(account: Account) {
  let count: decimal<9, 0> = 0;
  while count < 10 limit 10 {
    count = count + 1;
  }
  while count < 20 limit 10 {
    count = count + 1;
  }
  audit("DONE", account.idempotencyKey);
}`);

    expect(result.cobol).toContain("01  GO-FLD-LOOP-1");
    expect(result.cobol).toContain("01  GO-FLD-LOOP-2");
    expect(result.cobol).not.toMatch(/WS-LOOP-\d+-\d+/);
  });

  /**
   * An index-name cannot be qualified where it is used, so two `INDEXED BY
   * LINES-IDX` clauses are two definitions of one name. Enterprise COBOL takes
   * it as an extension — "acceptance of nonunique index-names that are not
   * referenced" — and stops the day a `SEARCH` names one.
   */
  it("qualify an index shared by two records", () => {
    const result = compile(`module Tables;

record Band { cap: decimal<9, 2>; }
record Opening { rows: Band[4]; idempotencyKey: string<36>; }
record Closing { rows: Band[8]; }

entry transaction go(opening: Opening, closing: Closing) {
  audit("DONE", opening.idempotencyKey);
}`);

    expect(result.diagnostics).toEqual([]);
    expect(result.cobol).toContain("INDEXED BY OPENING-ROWS-IDX");
    expect(result.cobol).toContain("INDEXED BY CLOSING-ROWS-IDX");
  });
});

describe("the SQL declare section", () => {
  const result = compile(`${PREAMBLE}
record Row { rowAccountId: string<16>; }

sql fetchAccount(keyAccountId: string<16>): Row {
  SELECT ACCOUNT_ID INTO :rowAccountId FROM ACCOUNT WHERE ACCOUNT_ID = :keyAccountId
}

entry transaction go(row: Row, idempotencyKey: string<36>) {
  execute fetchAccount("ACC-1") into row;
  if sqlcode < 0 {
    raise "DB2_FAILED";
  } else {
    if sqlcode == 0 {
      audit("FOUND", idempotencyKey);
    } else {
      audit("MISSING", idempotencyKey);
    }
  }
}`);

  /**
   * A declare section holds host variables and nothing else. The one this
   * emitter opened used to run to the end of working storage, so the ledger and
   * audit interface groups were inside it — described to Db2 as variables the
   * SQL might name.
   */
  it("holds the host variables and closes", () => {
    const cobol = result.cobol ?? "";
    const section = cobol.slice(
      cobol.indexOf("BEGIN DECLARE SECTION"),
      cobol.indexOf("END DECLARE SECTION"),
    );

    expect(section).toContain("FETCH-ACCOUNT-H1");
    expect(section).not.toContain("BANK-LEDGER-INTERFACE");
    expect(section).not.toContain("BANK-AUDIT-INTERFACE");
    expect(section).not.toContain("BANK-FAILURE-CODE");
  });

  /** A record a statement reads a row into is host variables, so it opens one. */
  it("opens one of its own around a record the SQL names", () => {
    expect(flowed(result.cobol)).toContain(
      "EXEC SQL BEGIN DECLARE SECTION END-EXEC. 01 ROW.",
    );
  });
});

describe("a CICS program", () => {
  const result = compile(`${PREAMBLE}
cics transaction enquire(account: Account) {
  audit("ENQUIRED", account.idempotencyKey);
}`);

  /**
   * `RETURN-CODE` is a batch step's answer to JCL and nothing under CICS reads
   * it. What a transaction that has failed owes the region is an abend.
   */
  it("never writes the return code register", () => {
    expect(result.cobol).not.toContain("TO RETURN-CODE");
  });

  it("abends instead", () => {
    expect(result.cobol).toContain('EXEC CICS ABEND ABCODE("BLNG")');
  });
});

/**
 * `""` is a zero-length literal, which Enterprise COBOL does not have.
 *
 * GnuCOBOL's default dialect takes it and warns that a SPACE will be assumed;
 * `IGYCRCTL` rejects it outright. An empty alphanumeric field in COBOL holds
 * spaces — that is what a MOVE of anything shorter leaves behind — so `SPACES`
 * is not a substitution for `""` but the only thing it can mean.
 */
describe("an empty string literal", () => {
  const result = compile(`${PREAMBLE}
entry transaction blank(account: Account) {
  account.accountId = "";

  if account.accountId == "" {
    audit("BLANK", account.idempotencyKey);
  }
}`);

  it("becomes SPACES rather than a literal the target rejects", () => {
    expect(result.cobol).not.toContain('""');
    expect(flowed(result.cobol)).toContain(
      "MOVE SPACES TO ACCOUNT-ID OF ACCOUNT",
    );
    expect(flowed(result.cobol)).toContain("IF ACCOUNT-ID OF ACCOUNT = SPACES");
  });
});
