       *> Generated by bankc.
       *> Do not edit this file directly.
       01  POST-TRANSFER-REQUEST.
           05  DEBIT-ACCOUNT        PIC X(16).
           05  CREDIT-ACCOUNT       PIC X(16).
           05  AMOUNT               PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
