CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> BATCHINT — BatchInterestAccrual
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   A library of functions. Nothing here is an entry point.
      *>
      *> ENTRY
      *>   A batch program with no parameters, started by EXEC PGM in a
      *>     job.
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>     which.
      *>
      *> RESTART
      *>   Rerunnable. The program writes no dataset.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. BATCHINT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       01  INTEREST-ACCOUNT.
           05  ACCOUNT-ID           PIC X(16).
           05  BALANCE              PIC S9(16)V99 COMP-3.
       01  IS-ELIG-FOR-INTEREST-RESULT PIC X VALUE "N".
       01  IS-ELIGIBLE-FOR-INTEREST-P1 PIC S9(16)V99 COMP-3.
       01  PROJECTED-BALANCE    PIC S9(16)V99 COMP-3.

       PROCEDURE DIVISION.
       IS-ELIGIBLE-FOR-INTEREST.
           COMPUTE PROJECTED-BALANCE = (IS-ELIGIBLE-FOR-INTEREST-P1 +
               25.00)
               ON SIZE ERROR
                   DISPLAY "ARITHMETIC OVERFLOW PROJECTED-BALANCE" UPON
                       SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "ARITHMETIC-OVERFLOW" TO BANK-FAILURE-CODE
                   GO TO IS-ELIGIBLE-FOR-INTEREST-EXIT
           END-COMPUTE
           IF PROJECTED-BALANCE > 1000.00
               MOVE 'Y' TO IS-ELIG-FOR-INTEREST-RESULT
           ELSE
               MOVE 'N' TO IS-ELIG-FOR-INTEREST-RESULT
           END-IF
           CONTINUE.
       IS-ELIGIBLE-FOR-INTEREST-EXIT.
           EXIT.
