//* Generated by bankc.
//* Do not edit this file directly.
//ACCOUNTP JOB (BANKLANG),'ACCOUNT-POSTING',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/ACCOUNT-POSTING.cbl
//* COPYBOOK source: dist/copybooks/TRANSFER-REQUEST.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.ACCOUNTPOSTING
//* The compile step above is a documentation-friendly skeleton.
