//* Generated by bankc.
//* Do not edit this file directly.
//STATEMEN JOB (BANKLANG),'STATEMENT-GENERATION',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/STATEMENT-GENERATION.cbl
//* COPYBOOK source: dist/copybooks/LEDGER-ENTRY.cpy
//* COPYBOOK source: dist/copybooks/STATEMENT.cpy
//* COPYBOOK source: dist/copybooks/ACCOUNT-MASTER.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.STATEMENTGENERATION
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(STATEMEN)
//RUN      EXEC PGM=STATEMEN
//SYSOUT   DD SYSOUT=*
//ACCOUNTM DD DISP=SHR,DSN=BANKLANG.ACCOUNTM
//STATEMEN DD DSN=BANKLANG.STATEMEN,DISP=(NEW,CATLG),
//            UNIT=SYSDA,SPACE=(CYL,(1,1))
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the load library name are
//* placeholders for an installation's own standards.
