//* Generated by bankc.
//* Do not edit this file directly.
//STATEMEN JOB (BANKLANG),'STATEMENT-GENERATION',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/STATEMENT-GENERATION.cbl
//* COPYBOOK source: dist/copybooks/LEDGER-ENTRY.cpy
//* COPYBOOK source: dist/copybooks/STATEMENT.cpy
//* COPYBOOK source: dist/copybooks/ACCOUNT-MASTER.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.STATEMENTGENERATION
//* The compile step above is a documentation-friendly skeleton.
