import type { IRProgram, IRRecord, IRType } from "../../ir/src/index";
import {
  enumWidth,
  decimalPicture,
  packedDecimalByteLength,
  toCobolName,
  toCobolPicture,
  temporalLength,
  editedLength,
} from "../../cobol-ir/src/index";

export interface CopybookFieldLayout {
  name: string;
  cobolName: string;
  offset: number;
  length: number;
  picture: string;
}

export interface CopybookRecordLayout {
  name: string;
  cobolName: string;
  totalLength: number;
  fields: CopybookFieldLayout[];
}

export interface CopybookInspectionField {
  name: string;
  cobolName: string;
  offset: number;
  length: number;
  picture: string;
}

export interface CopybookInspection {
  recordName: string;
  cobolName: string;
  totalLength: number;
  fields: CopybookInspectionField[];
}

export interface CopybookDiffField {
  index: number;
  left: CopybookInspectionField | null;
  right: CopybookInspectionField | null;
}

export interface CopybookDiffResult {
  identical: boolean;
  left: CopybookInspection;
  right: CopybookInspection;
  fieldDiffs: CopybookDiffField[];
  recordNameDiffers: boolean;
  totalLengthDiffers: boolean;
}

export interface CopybookLayoutEntry {
  order: number;
  path: string;
  type: string;
  picture: string;
  usage: string;
  offset: number;
  length: number;
  bytes: number;
  /**
   * Restricted data, as the BankTS record declared it.
   *
   * Reported here so an auditor reading the layout can see which bytes of a
   * record hold data that must not reach a log, without reading the source.
   */
  sensitive: boolean;
}

export interface CopybookLayoutReport {
  recordName: string;
  cobolName: string;
  totalLength: number;
  entries: CopybookLayoutEntry[];
}

export interface CopybookLayoutDocument {
  version: number;
  backendProfile: string;
  artifact: string;
  reports: CopybookLayoutReport[];
}

export function describeRecordLayout(record: IRRecord): CopybookRecordLayout {
  const fields: CopybookFieldLayout[] = [];
  let offset = 0;

  for (const field of record.fields) {
    const length = fieldLength(field.type);
    fields.push({
      name: field.name,
      cobolName: toCobolName(field.name),
      offset,
      length,
      picture: toCobolPicture(field.type),
    });
    offset += length;
  }

  return {
    name: record.name,
    cobolName: toCobolName(record.name),
    totalLength: offset,
    fields,
  };
}

/** Db2-style null indicator: a two-byte signed halfword beside the value. */
export const NULL_INDICATOR_BYTES = 2;

export function fieldLength(type: IRType): number {
  switch (type.kind) {
    case "edited":
      return editedLength(type.style, type.precision, type.scale);
    case "temporal":
      return temporalLength(type.unit);
    case "currency":
      return packedDecimalByteLength(type.precision);
    case "enum":
      return enumWidth(type.members);
    case "nullable":
      // The value plus a two-byte null indicator, following the Db2 convention.
      return fieldLength(type.inner) + NULL_INDICATOR_BYTES;
    case "array":
      return fieldLength(type.element) * type.length;
    case "decimal":
      return packedDecimalByteLength(type.precision);
    case "string":
      return type.length;
    case "bool":
      return 1;
    case "record":
      return type.fields.reduce(
        (total, field) => total + fieldLength(field.type),
        0,
      );
  }
}

export function renderCopybook(record: IRRecord): string {
  const layout = describeRecordLayout(record);
  const lines = [
    "*> Generated by bankc.",
    "*> Do not edit this file directly.",
    `01  ${layout.cobolName}.`,
  ];

  for (const field of layout.fields) {
    lines.push(`    05  ${field.cobolName.padEnd(20)} ${field.picture}.`);
  }

  return `${lines.join("\n")}\n`;
}

export function inspectGeneratedCopybook(
  sourceText: string,
): CopybookInspection {
  const lines = sourceText
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0 && !line.startsWith("*>"));

  const recordLine = lines.find((line) => line.trimStart().startsWith("01  "));
  if (!recordLine) {
    throw new Error("No generated 01-level record was found.");
  }

  const recordMatch = recordLine.trimStart().match(/^01\s+([A-Z0-9-]+)\.$/);
  if (!recordMatch) {
    throw new Error(`Unable to parse record line: ${recordLine}`);
  }

  const fields: CopybookInspectionField[] = [];
  let offset = 0;
  for (const line of lines) {
    const trimmed = line.trimStart();
    if (!trimmed.startsWith("05  ")) {
      continue;
    }

    const match = trimmed.match(/^05\s+([A-Z0-9-]+)\s+(.+)\.$/);
    if (!match) {
      throw new Error(`Unable to parse field line: ${line}`);
    }

    const cobolName = match[1];
    const picture = match[2].trim();
    const length = inspectPictureLength(picture);

    fields.push({
      name: cobolName,
      cobolName,
      offset,
      length,
      picture,
    });
    offset += length;
  }

  return {
    recordName: recordMatch[1],
    cobolName: recordMatch[1],
    totalLength: offset,
    fields,
  };
}

export function renderCopybookInspection(
  inspection: CopybookInspection,
): string {
  const lines = [
    "Copybook inspection",
    "",
    `Record: ${inspection.cobolName}`,
    `Total length: ${inspection.totalLength}`,
    "",
    "Fields:",
    ...inspection.fields.map(
      (field) =>
        `- ${field.cobolName} | ${field.picture} | offset ${field.offset} | length ${field.length}`,
    ),
    "",
  ];

  return `${lines.join("\n")}`;
}

export function diffGeneratedCopybooks(
  leftText: string,
  rightText: string,
): CopybookDiffResult {
  const left = inspectGeneratedCopybook(leftText);
  const right = inspectGeneratedCopybook(rightText);
  const maxFields = Math.max(left.fields.length, right.fields.length);
  const fieldDiffs: CopybookDiffField[] = [];

  for (let index = 0; index < maxFields; index += 1) {
    fieldDiffs.push({
      index,
      left: left.fields[index] ?? null,
      right: right.fields[index] ?? null,
    });
  }

  const recordNameDiffers = left.cobolName !== right.cobolName;
  const totalLengthDiffers = left.totalLength !== right.totalLength;
  const fieldsDiffer = fieldDiffs.some((diff) => {
    if (!diff.left || !diff.right) {
      return true;
    }

    return (
      diff.left.cobolName !== diff.right.cobolName ||
      diff.left.offset !== diff.right.offset ||
      diff.left.length !== diff.right.length ||
      diff.left.picture !== diff.right.picture
    );
  });

  return {
    identical: !recordNameDiffers && !totalLengthDiffers && !fieldsDiffer,
    left,
    right,
    fieldDiffs,
    recordNameDiffers,
    totalLengthDiffers,
  };
}

export function renderCopybookDiff(result: CopybookDiffResult): string {
  const lines = [
    "Copybook diff",
    "",
    `Left record: ${result.left.cobolName}`,
    `Right record: ${result.right.cobolName}`,
    `Left total length: ${result.left.totalLength}`,
    `Right total length: ${result.right.totalLength}`,
    `Identical: ${result.identical ? "yes" : "no"}`,
    "",
    "Field comparison:",
    "| Index | Left | Right |",
    "| --- | --- | --- |",
  ];

  for (const diff of result.fieldDiffs) {
    lines.push(
      `| ${diff.index} | ${renderFieldSummary(diff.left)} | ${renderFieldSummary(diff.right)} |`,
    );
  }

  if (result.recordNameDiffers || result.totalLengthDiffers) {
    lines.push("");
    lines.push("Layout differences:");
    if (result.recordNameDiffers) {
      lines.push("- Record name differs.");
    }
    if (result.totalLengthDiffers) {
      lines.push("- Total length differs.");
    }
  }

  lines.push("");
  return `${lines.join("\n")}`;
}

export function renderCopybookTypes(inspection: CopybookInspection): string {
  const lines = [
    "Copybook types",
    "",
    `Record: ${inspection.cobolName}`,
    `Total length: ${inspection.totalLength}`,
    "",
    "| Field | Picture | Offset | Length |",
    "| --- | --- | --- | --- |",
  ];

  for (const field of inspection.fields) {
    lines.push(
      `| ${field.cobolName} | ${field.picture} | ${field.offset} | ${field.length} |`,
    );
  }

  lines.push("");
  return `${lines.join("\n")}`;
}

export function buildCopybookLayoutDocument(
  program: IRProgram,
  artifact: string,
): CopybookLayoutDocument {
  return {
    version: 1,
    backendProfile: "ibm-enterprise-cobol-zos",
    artifact,
    reports: program.records.map((record) => buildCopybookLayoutReport(record)),
  };
}

export function buildCopybookLayoutReport(
  record: IRRecord,
): CopybookLayoutReport {
  const entries: CopybookLayoutEntry[] = [];
  let order = 0;
  let offset = 0;

  for (const field of record.fields) {
    offset = collectLayoutEntries(
      field,
      `${toCobolName(record.name)}.${toCobolName(field.name)}`,
      offset,
      entries,
      () => {
        order += 1;
        return order;
      },
    );
  }

  return {
    recordName: record.name,
    cobolName: toCobolName(record.name),
    totalLength: offset,
    entries,
  };
}

export function renderCopybookLayoutDocument(
  document: CopybookLayoutDocument,
): string {
  const lines = [
    "# Copybook Layout Report",
    "",
    `Version: ${document.version}`,
    `Backend profile: ${document.backendProfile}`,
    "",
    `Artifact: ${document.artifact}`,
    "",
  ];

  for (const report of document.reports) {
    lines.push(
      `## ${report.cobolName}`,
      "",
      `Total length: ${report.totalLength}`,
      "",
      "| Order | Path | Type | PIC | Usage | Offset | Length | Bytes | Sensitive |",
      "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    );

    for (const entry of report.entries) {
      lines.push(
        `| ${entry.order} | ${entry.path} | ${entry.type} | ${entry.picture} | ${entry.usage} | ${entry.offset} | ${entry.length} | ${entry.bytes} | ${entry.sensitive ? "yes" : "no"} |`,
      );
    }

    lines.push("");
  }

  return `${lines.join("\n")}`;
}

function inspectPictureLength(picture: string): number {
  const normalized = picture.replace(/\s+/g, " ").trim().toUpperCase();

  const alphanumeric = normalized.match(/^PIC X\((\d+)\)(?: VALUE '.+')?$/);
  if (alphanumeric) {
    return Number(alphanumeric[1]);
  }

  const packed = normalized.match(
    /^PIC S9\((\d+)\)(?:V(9+))?\s+COMP-3(?: VALUE '.+')?$/,
  );
  if (packed) {
    const wholeDigits = Number(packed[1]);
    const scaleDigits = packed[2]?.length ?? 0;
    return packedDecimalByteLength(wholeDigits + scaleDigits);
  }

  const singleByte = normalized.match(/^PIC X(?: VALUE '.+')?$/);
  if (singleByte) {
    return 1;
  }

  throw new Error(`Unsupported generated picture clause: ${picture}`);
}

function renderFieldSummary(field: CopybookInspectionField | null): string {
  if (!field) {
    return "_missing_";
  }

  return `${field.cobolName} (${field.picture}, offset ${field.offset}, length ${field.length})`;
}

function collectLayoutEntries(
  field: IRRecord["fields"][number],
  path: string,
  offset: number,
  entries: CopybookLayoutEntry[],
  nextOrder: () => number,
): number {
  const length = fieldLength(field.type);
  const order = nextOrder();

  entries.push({
    order,
    path,
    type: formatLayoutType(field.type),
    picture: formatLayoutPicture(field.type),
    usage: formatLayoutUsage(field.type),
    offset,
    length,
    bytes: length,
    sensitive: field.sensitive,
  });

  if (field.type.kind !== "record") {
    return offset + length;
  }

  let childOffset = offset;
  for (const child of field.type.fields) {
    childOffset = collectLayoutEntries(
      child,
      `${path}.${toCobolName(child.name)}`,
      childOffset,
      entries,
      nextOrder,
    );
  }

  return offset + length;
}

function formatLayoutType(type: IRType): string {
  switch (type.kind) {
    case "edited":
      return `edited<decimal<${type.precision},${type.scale}>,"${type.style}">`;
    case "temporal":
      return type.unit;
    case "decimal":
      return `decimal<${type.precision},${type.scale}>`;
    case "string":
      return `string<${type.length}>`;
    case "bool":
      return "bool";
    case "record":
      return `record<${type.name}>`;
    case "currency":
      return `currency<"${type.code}",${type.precision},${type.scale}>`;
    case "enum":
      return `enum<${type.name}>`;
    case "nullable":
      return `nullable<${formatLayoutType(type.inner)}>`;
    case "array":
      return `${formatLayoutType(type.element)}[${type.length}]`;
  }
}

function formatLayoutPicture(type: IRType): string {
  switch (type.kind) {
    case "record":
      return "GROUP";
    default:
      return toCobolPicture(type);
  }
}

function formatLayoutUsage(type: IRType): string {
  switch (type.kind) {
    case "edited":
      return "DISPLAY";
    case "temporal":
      return "DISPLAY";
    case "decimal":
      return "COMP-3";
    case "currency":
      return "COMP-3";
    case "enum":
      return "DISPLAY";
    case "nullable":
      return formatLayoutUsage(type.inner);
    case "array":
      return formatLayoutUsage(type.element);
    case "string":
      return "DISPLAY";
    case "bool":
      return "DISPLAY";
    case "record":
      return "GROUP";
  }
}
