//* Generated by bankc.
//* Do not edit this file directly.
//WITHDRAW JOB (BANKLANG),'WITHDRAWAL-WITH-RECOVERY',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/WITHDRAWAL-WITH-RECOVERY.cbl
//* COPYBOOK source: dist/copybooks/CURRENT-ACCOUNT.cpy
//* COPYBOOK source: dist/copybooks/SAVINGS-ACCOUNT.cpy
//* COPYBOOK source: dist/copybooks/WITHDRAWAL-RESULT.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.WITHDRAWALWITHRECOVERY
//* The compile step above is a documentation-friendly skeleton.
