//* Generated by bankc.
//* Do not edit this file directly.
//WITHDRAW JOB (BANKLANG),'WITHDRAWAL-WITH-RECOVERY',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/WITHDRAWAL-WITH-RECOVERY.cbl
//* COPYBOOK source: dist/copybooks/CURRENT-ACCOUNT.cpy
//* COPYBOOK source: dist/copybooks/SAVINGS-ACCOUNT.cpy
//* COPYBOOK source: dist/copybooks/WITHDRAWAL-RESULT.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.WITHDRAWALWITHRECOVERY
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(WITHDRAW)
//RUN      EXEC PGM=WITHDRAW
//SYSOUT   DD SYSOUT=*
//REQUESTI DD DISP=SHR,DSN=BANKLANG.REQUESTI
//RESULTOU DD DSN=BANKLANG.RESULTOU,DISP=(NEW,CATLG),
//            UNIT=SYSDA,SPACE=(CYL,(1,1))
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the load library name are
//* placeholders for an installation's own standards.
