       *> Generated by bankc.
       *> Do not edit this file directly.
       01  AUDIT-ENTRY.
           05  AUDIT-ACCOUNT-ID    PIC X(16).
           05  AUDIT-REQUESTED-BY  PIC X(20).
           05  AUDIT-OUTCOME       PIC X(14).
               88  AUDIT-OUTCOME-FOUND           VALUE "FOUND".
               88  AUDIT-OUTCOME-NOT-FOUND       VALUE "NOT_FOUND".
               88  AUDIT-OUTCOME-UNAVAILABLE     VALUE "UNAVAILABLE".
               88  AUDIT-OUTCOME-UNAVAILABLE-DB  VALUE "UNAVAILABLE_DB".
