       *> Generated by bankc.
       *> Do not edit this file directly.
       01  BALANCE-REPLY.
           05  REPLY-ACCOUNT-ID     PIC X(16).
           05  REPLY-BALANCE        PIC S9(16)V99 COMP-3.
           05  OUTCOME              PIC X(14).
               88  OUTCOME-FOUND                VALUE "FOUND".
               88  OUTCOME-NOT-FOUND            VALUE "NOT_FOUND".
               88  OUTCOME-UNAVAILABLE          VALUE "UNAVAILABLE".
               88  OUTCOME-UNAVAILABLE-DB       VALUE "UNAVAILABLE_DB".
