*> Generated by bankc.
*> Do not edit this file directly.
01  ENQUIRY-REPLY.
    05  REPLY-ACCOUNT-ID     PIC X(16).
    05  REPLY-BALANCE        PIC S9(16)V99 COMP-3.
    05  OUTCOME              PIC X(11).
