       *> Generated by bankc.
       *> Do not edit this file directly.
       01  ENQUIRY-COMMAREA.
           05  CA-ACCOUNT-ID    PIC X(16).
           05  CA-REQUESTED-BY  PIC X(20).
           05  CA-BALANCE       PIC S9(16)V99 COMP-3.
           05  CA-OUTCOME       PIC X(14).
               88  CA-OUTCOME-FOUND           VALUE "FOUND".
               88  CA-OUTCOME-NOT-FOUND       VALUE "NOT_FOUND".
               88  CA-OUTCOME-UNAVAILABLE     VALUE "UNAVAILABLE".
               88  CA-OUTCOME-UNAVAILABLE-DB  VALUE "UNAVAILABLE_DB".
           05  IDEMPOTENCY-KEY  PIC X(36).
