//* Generated by bankc.
//* Do not edit this file directly.
//INTEREST JOB (BANKLANG),'INTEREST-POSTING-BATCH',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/INTEREST-POSTING-BATCH.cbl
//* COPYBOOK source: dist/copybooks/INTEREST-ACCOUNT.cpy
//* COPYBOOK source: dist/copybooks/POSTING-ADVICE.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.INTERESTPOSTINGBATCH
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(INTEREST)
//RUN      EXEC PGM=INTEREST
//SYSOUT   DD SYSOUT=*
//ACCOUNTF DD DISP=SHR,DSN=BANKLANG.ACCOUNTF
//ADVICEOU DD DSN=BANKLANG.ADVICEOU,DISP=(NEW,CATLG),
//            UNIT=SYSDA,SPACE=(CYL,(1,1))
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the load library name are
//* placeholders for an installation's own standards.
