//* Generated by bankc.
//* Do not edit this file directly.
//INTEREST JOB (BANKLANG),'INTEREST-POSTING-BATCH',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/INTEREST-POSTING-BATCH.cbl
//* COPYBOOK source: dist/copybooks/INTEREST-ACCOUNT.cpy
//* COPYBOOK source: dist/copybooks/POSTING-ADVICE.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.INTERESTPOSTINGBATCH
//* The compile step above is a documentation-friendly skeleton.
