CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> ZUNITTES: ZunitTestedPosting
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   POST-ONE, the transaction this program is entered at.
      *>
      *> ENTRY
      *>   A batch program, started by EXEC PGM and entered with the
      *>   job's PARM behind a halfword length: 71 characters,
      *>   positional.
      *>   account             X(16) (16)
      *>   amount              S9(16)V99 SIGN IS LEADING SEPARATE (19)
      *>   idempotencyKey      X(36) (36)
      *>   A PARM shorter than that ends the step with return code 12
      *>   rather than reading past what was passed.
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>   BANKLEDG ledger posting and rollback
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>       which.
      *>
      *> RESTART
      *>   Rerunnable. The program writes no dataset.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ZUNITTES.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BANK-FAILURE-CODE  PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE   PIC S9(4) COMP EXTERNAL.
       01  POST-ONE-P1        PIC X(16) VALUE SPACES.
       01  POST-ONE-P2        PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  POST-ONE-P3        PIC X(36) VALUE SPACES.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION  PIC X(6).
           05  BANK-LEDGER-ACCOUNT    PIC X(32).
           05  BANK-LEDGER-AMOUNT     PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT        PIC X(32).
           05  BANK-AUDIT-CORRELATION  PIC X(64).

       LINKAGE SECTION.
       01  BANK-PARM.
           05  BANK-PARM-LENGTH  PIC S9(4) COMP.
           05  BANK-PARM-DATA.
               10  BANK-PARM-ACCOUNT          PIC X(16).
               10  BANK-PARM-AMOUNT        PIC S9(16)V99 SIGN IS LEADING
                   SEPARATE.
               10  BANK-PARM-IDEMPOTENCY-KEY  PIC X(36).

       PROCEDURE DIVISION USING BANK-PARM.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM BANK-ACCEPT-PARM THRU BANK-ACCEPT-PARM-EXIT
           IF BANK-RETURN-CODE = 0
               PERFORM POST-ONE THRU POST-ONE-EXIT
           END-IF
           MOVE BANK-RETURN-CODE TO RETURN-CODE
           GOBACK.
       BANK-ACCEPT-PARM.
      *> The job's PARM, positional. See the JCL for the layout.
           IF ADDRESS OF BANK-PARM = NULL
               DISPLAY "NO PARM PASSED, 71 BYTES REQUIRED" UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               GO TO BANK-ACCEPT-PARM-EXIT
           END-IF
           IF BANK-PARM-LENGTH < 71
               DISPLAY "PARM IS " BANK-PARM-LENGTH " BYTES, 71 REQUIRED"
                   UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               GO TO BANK-ACCEPT-PARM-EXIT
           END-IF
           MOVE BANK-PARM-ACCOUNT TO POST-ONE-P1
           IF BANK-PARM-AMOUNT IS NOT NUMERIC
               DISPLAY "PARM AMOUNT IS NOT NUMERIC" UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               GO TO BANK-ACCEPT-PARM-EXIT
           END-IF
           MOVE BANK-PARM-AMOUNT TO POST-ONE-P2
           MOVE BANK-PARM-IDEMPOTENCY-KEY TO POST-ONE-P3
           CONTINUE.
       BANK-ACCEPT-PARM-EXIT.
           EXIT.
       POST-ONE.
           MOVE "DEBIT" TO BANK-LEDGER-OPERATION
           MOVE POST-ONE-P1 TO BANK-LEDGER-ACCOUNT
           MOVE POST-ONE-P2 TO BANK-LEDGER-AMOUNT
           CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
           MOVE "CREDIT" TO BANK-LEDGER-OPERATION
           MOVE "SUSPENSE" TO BANK-LEDGER-ACCOUNT
           MOVE POST-ONE-P2 TO BANK-LEDGER-AMOUNT
           CALL "BANKLEDG" USING BANK-LEDGER-INTERFACE
           MOVE "POSTED" TO BANK-AUDIT-EVENT
           MOVE POST-ONE-P3 TO BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       POST-ONE-EXIT.
           EXIT.
