//* Generated by bankc.
//* Do not edit this file directly.
//ONLINEEN JOB (BANKLANG),'ONLINE-ENQUIRY',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/ONLINE-ENQUIRY.cbl
//* COPYBOOK source: dist/copybooks/ENQUIRY-REQUEST.cpy
//* COPYBOOK source: dist/copybooks/ACCOUNT-ROW.cpy
//* COPYBOOK source: dist/copybooks/ENQUIRY-REPLY.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.ONLINEENQUIRY
//* The compile step above is a documentation-friendly skeleton.
