//* Generated by bankc.
//* Do not edit this file directly.
//ONLINEEN JOB (BANKLANG),'ONLINE-ENQUIRY',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Build job for the generated CICS program. It is installed, not run.
//* COBOL source: dist/cobol/ONLINE-ENQUIRY.cbl
//* COPYBOOK source: dist/copybooks/ENQUIRY-REQUEST.cpy
//* COPYBOOK source: dist/copybooks/ACCOUNT-ROW.cpy
//* COPYBOOK source: dist/copybooks/ENQUIRY-REPLY.cpy
//* EXEC CICS must be translated before any compiler reads the source.
//TRANSLAT EXEC PGM=DFHECP1$
//STEPLIB  DD DISP=SHR,DSN=CICSTS.SDFHLOAD
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.ONLINEENQUIRY
//SYSPUNCH DD DSN=&&TRANOUT,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//* EXEC SQL must be precompiled, and the resulting DBRM bound, before
//* the program can run. Neither step is optional.
//PRECOMP  EXEC PGM=DSNHPC,PARM='HOST(COB2)'
//STEPLIB  DD DISP=SHR,DSN=DSN.SDSNLOAD
//DBRMLIB  DD DISP=SHR,DSN=DIST.DBRMLIB(ONLINEEN)
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DSN=&&TRANOUT,DISP=(OLD,DELETE)
//SYSCIN   DD DSN=&&PRECOUT,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DSN=&&PRECOUT,DISP=(OLD,DELETE)
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(ONLINEEN)
//BIND     EXEC PGM=IKJEFT01,COND=(4,LT)
//STEPLIB  DD DISP=SHR,DSN=DSN.SDSNLOAD
//DBRMLIB  DD DISP=SHR,DSN=DIST.DBRMLIB
//SYSTSPRT DD SYSOUT=*
//SYSTSIN  DD *
  DSN SYSTEM(DSN)
  BIND PACKAGE(BANKLANG) MEMBER(ONLINEEN) ACT(REP) ISO(CS)
  END
/*
//* No run step: a CICS program is started by a transaction identifier
//* in a region, not by EXEC PGM in a job. Install the load module and
//* define the program and transaction to CICS instead.
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the Db2 subsystem and package names are
//* placeholders for an installation's own standards.
