*> Generated by bankc.
*> Do not edit this file directly.
*> Source maps are available in dist/maps.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCOUNT-TRANSFER.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  TRANSFER-REQUEST.
           05  DEBIT-ACCOUNT        PIC X(16).
           05  CREDIT-ACCOUNT       PIC X(16).
           05  AMOUNT               PIC S9(16)V99 COMP-3.
       01  VALIDATE-AMOUNT-RESULT PIC X VALUE 'N'.
       01  VALIDATE-AMOUNT-P1   PIC S9(16)V99 COMP-3.

       PROCEDURE DIVISION.
       VALIDATE-AMOUNT.
           IF VALIDATE-AMOUNT-P1 > 0.00
               MOVE 'Y' TO VALIDATE-AMOUNT-RESULT
           ELSE
               MOVE 'N' TO VALIDATE-AMOUNT-RESULT
           END-IF
           CONTINUE.
