       *> Generated by bankc.
       *> Do not edit this file directly.
       01  ACCOUNT-MASTER.
           05  ACCOUNT-ID           PIC X(16).
           05  STATUS-FLD           PIC X(7).
               88  STATUS-FLD-ACTIVE            VALUE "ACTIVE".
               88  STATUS-FLD-DORMANT           VALUE "DORMANT".
               88  STATUS-FLD-FROZEN            VALUE "FROZEN".
               88  STATUS-FLD-CLOSED            VALUE "CLOSED".
           05  BALANCE              PIC S9(16)V99 COMP-3.
