*> Generated by bankc.
*> Do not edit this file directly.
01  ACCOUNT-MASTER.
    05  ACCOUNT-ID           PIC X(16).
    05  STATUS               PIC X(7).
    05  BALANCE              PIC S9(16)V99 COMP-3.
