       *> Generated by bankc.
       *> Do not edit this file directly.
       01  LEDGER-ENTRY.
           05  ENTRY-KIND           PIC X(6).
               88  ENTRY-KIND-DEBIT             VALUE "DEBIT".
               88  ENTRY-KIND-CREDIT            VALUE "CREDIT".
           05  NARRATIVE            PIC X(40).
           05  AMOUNT               PIC S9(16)V99 COMP-3.
