*> Generated by bankc.
*> Do not edit this file directly.
01  STATEMENT.
    05  ACCOUNT-ID           PIC X(16).
    05  STATUS               PIC X(7).
    05  OPENING-BALANCE      PIC S9(16)V99 COMP-3.
    05  CLOSING-BALANCE      PIC S9(16)V99 COMP-3.
    05  LINES                GROUP.
    05  RELATIONSHIP-MANAGER PIC X(20).
    05  IDEMPOTENCY-KEY      PIC X(36).
