       *> Generated by bankc.
       *> Do not edit this file directly.
       01  STATEMENT.
           05  ACCOUNT-ID                PIC X(16).
           05  HOLDER-NAME               PIC X(40).
           05  NATIONAL-ID               PIC X(20).
           05  STATUS-FLD                PIC X(7).
               88  STATUS-FLD-ACTIVE   VALUE "ACTIVE".
               88  STATUS-FLD-DORMANT  VALUE "DORMANT".
               88  STATUS-FLD-FROZEN   VALUE "FROZEN".
               88  STATUS-FLD-CLOSED   VALUE "CLOSED".
           05  OPENING-BALANCE           PIC S9(16)V99 COMP-3.
           05  CLOSING-BALANCE           PIC S9(16)V99 COMP-3.
           05  LINES-FLD                 OCCURS 100 TIMES
                   INDEXED BY STATEMENT-LINES-FLD-IDX.
               10  ENTRY-KIND  PIC X(6).
                   88  ENTRY-KIND-DEBIT   VALUE "DEBIT".
                   88  ENTRY-KIND-CREDIT  VALUE "CREDIT".
               10  NARRATIVE   PIC X(40).
               10  AMOUNT      PIC S9(16)V99 COMP-3.
           05  RELATIONSHIP-MANAGER      PIC X(20).
           05  RELATIONSHIP-MANAGER-IND  PIC S9(4) COMP.
           05  IDEMPOTENCY-KEY           PIC X(36).
