//* Generated by bankc.
//* Do not edit this file directly.
//AMORTISA JOB (BANKLANG),'AMORTISATION-SCHEDULE',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/AMORTISATION-SCHEDULE.cbl
//* COPYBOOK source: dist/copybooks/INSTALMENT.cpy
//* COPYBOOK source: dist/copybooks/LOAN.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.AMORTISATIONSCHEDULE
//* The compile step above is a documentation-friendly skeleton.
