//* Generated by bankc.
//* Do not edit this file directly.
//AMORTISA JOB (BANKLANG),'AMORTISATION-SCHEDULE',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/AMORTISATION-SCHEDULE.cbl
//* COPYBOOK source: dist/copybooks/INSTALMENT.cpy
//* COPYBOOK source: dist/copybooks/LOAN.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.AMORTISATIONSCHEDULE
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(AMORTISA)
//RUN      EXEC PGM=AMORTISA
//SYSOUT   DD SYSOUT=*
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the load library name are
//* placeholders for an installation's own standards.
