*> Generated by bankc.
*> Do not edit this file directly.
01  ACCOUNT-ROW.
    05  ROW-ACCOUNT-ID       PIC X(16).
    05  ROW-BALANCE          PIC S9(16)V99 COMP-3.
    05  ROW-STATUS           PIC X(8).
