*> Generated by bankc.
*> Do not edit this file directly.
01  ACCRUAL-SUMMARY.
    05  SUMMARY-BRANCH-ID    PIC X(8).
    05  ACCOUNTS-READ        PIC S9(9) COMP-3.
    05  ACCOUNTS-ACCRUED     PIC S9(9) COMP-3.
    05  INTEREST-POSTED      PIC S9(16)V99 COMP-3.
    05  IDEMPOTENCY-KEY      PIC X(36).
