       *> Generated by bankc.
       *> Do not edit this file directly.
       01  ACCRUAL-REQUEST.
           05  BRANCH-ID            PIC X(8).
           05  ACCRUAL-RATE         PIC S9(1)V9999 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
