CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> ACCOUNTT — AccountTransfer
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   A library of functions. Nothing here is an entry point.
      *>
      *> ENTRY
      *>   A batch program with no parameters, started by EXEC PGM in a
      *>     job.
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>     which.
      *>
      *> RESTART
      *>   Rerunnable. The program writes no dataset.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCOUNTT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       01  TRANSFER-REQUEST.
           05  DEBIT-ACCOUNT        PIC X(16).
           05  CREDIT-ACCOUNT       PIC X(16).
           05  AMOUNT               PIC S9(16)V99 COMP-3.
       01  VALIDATE-AMOUNT-RESULT PIC X VALUE "N".
       01  VALIDATE-AMOUNT-P1   PIC S9(16)V99 COMP-3.

       PROCEDURE DIVISION.
       VALIDATE-AMOUNT.
           IF VALIDATE-AMOUNT-P1 > 0.00
               MOVE "Y" TO VALIDATE-AMOUNT-RESULT
           ELSE
               MOVE "N" TO VALIDATE-AMOUNT-RESULT
           END-IF
           CONTINUE.
       VALIDATE-AMOUNT-EXIT.
           EXIT.
