CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> ACCOUNTF — AccountFileBatch
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   POST-ACCOUNTS, the transaction this program is entered at.
      *>
      *> ENTRY
      *>   A batch program, started by EXEC PGM and entered with the
      *>   job's PARM behind a halfword length: 36 characters,
      *>   positional.
      *>   idempotencyKey      X(36) (36)
      *>   A PARM shorter than that ends the step with return code 12
      *>   rather than reading past what was passed.
      *>
      *> FILES
      *>   ACCOUNTI input   sequential ACCOUNT-RECORD (26 bytes)
      *>   POSTINGO output  sequential POSTING-RECORD (27 bytes)
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>       which.
      *>   16  A sort or merge did not complete. SORT-RETURN says so.
      *>
      *> RESTART
      *>   Not restartable. Rerun from the top: the generated job
      *>   deletes a half-written output dataset rather than cataloguing
      *>   it, so there is nothing for a second run to read as though it
      *>   were complete.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCOUNTF.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT ACCOUNT-INPUT-FILE ASSIGN TO ACCOUNTI
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS ACCOUNT-INPUT-STATUS.
           SELECT POSTING-OUTPUT-FILE ASSIGN TO POSTINGO
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS POSTING-OUTPUT-STATUS.

       DATA DIVISION.
       FILE SECTION.
       FD  ACCOUNT-INPUT-FILE
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.
       01  ACCOUNT-INPUT-RECORD.
           05  ACCOUNT-ID  PIC X(16).
           05  BALANCE     PIC S9(16)V99 COMP-3.
       FD  POSTING-OUTPUT-FILE
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.
       01  POSTING-OUTPUT-RECORD.
           05  POSTING-ACCOUNT-ID  PIC X(16).
           05  POSTING-BALANCE     PIC S9(16)V99 COMP-3.
           05  POSTING-FLAG        PIC X(1).
       WORKING-STORAGE SECTION.
       01  BANK-FILE-OPEN-1       PIC X(1) VALUE "N".
       01  ACCOUNT-INPUT-STATUS   PIC X(2) VALUE SPACES.
           88  ACCOUNT-INPUT-STATUS-OK      VALUE "00" THRU "09".
           88  ACCOUNT-INPUT-STATUS-EOF     VALUE "10".
           88  ACCOUNT-INPUT-STATUS-DUPKEY  VALUE "22".
           88  ACCOUNT-INPUT-STATUS-NOTFND  VALUE "23".
       01  BANK-FILE-OPEN-2       PIC X(1) VALUE "N".
       01  POSTING-OUTPUT-STATUS  PIC X(2) VALUE SPACES.
           88  POSTING-OUTPUT-STATUS-OK      VALUE "00" THRU "09".
           88  POSTING-OUTPUT-STATUS-EOF     VALUE "10".
           88  POSTING-OUTPUT-STATUS-DUPKEY  VALUE "22".
           88  POSTING-OUTPUT-STATUS-NOTFND  VALUE "23".
       01  BANK-FAILURE-CODE      PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE       PIC S9(4) COMP EXTERNAL.
       01  ACCOUNT-RECORD.
           05  ACCOUNT-ID  PIC X(16).
           05  BALANCE     PIC S9(16)V99 COMP-3.
       01  POSTING-RECORD.
           05  POSTING-ACCOUNT-ID  PIC X(16).
           05  POSTING-BALANCE     PIC S9(16)V99 COMP-3.
           05  POSTING-FLAG        PIC X(1).
       01  IS-OVERDRAWN-RESULT    PIC X(1) VALUE "N".
       01  IS-OVERDRAWN-P1        PIC S9(16)V99 COMP-3 VALUE ZERO.
       01  POST-ACCOUNTS-P3       PIC X(36) VALUE SPACES.
       01  POST-ACCOUNTS-LOOP-1   PIC 9(9) COMP VALUE ZERO.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT        PIC X(32).
           05  BANK-AUDIT-CORRELATION  PIC X(64).

       LINKAGE SECTION.
       01  BANK-PARM.
           05  BANK-PARM-LENGTH  PIC S9(4) COMP.
           05  BANK-PARM-DATA.
               10  BANK-PARM-IDEMPOTENCY-KEY  PIC X(36).

       PROCEDURE DIVISION USING BANK-PARM.
       DECLARATIVES.
       POSTING-OUTPUT-ERROR-SECTION SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON POSTING-OUTPUT-FILE.
       POSTING-OUTPUT-ERROR.
           DISPLAY "POSTINGOUTPUT FAILED, STATUS " POSTING-OUTPUT-STATUS
               UPON SYSOUT
           MOVE 12 TO BANK-RETURN-CODE
           CONTINUE.
       END DECLARATIVES.
       BANK-BODY SECTION.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM BANK-ACCEPT-PARM THRU BANK-ACCEPT-PARM-EXIT
           IF BANK-RETURN-CODE = 0
               PERFORM POST-ACCOUNTS THRU POST-ACCOUNTS-EXIT
           END-IF
           IF BANK-FILE-OPEN-1 = "Y"
               CLOSE ACCOUNT-INPUT-FILE
               IF NOT ACCOUNT-INPUT-STATUS-OK
                   DISPLAY "CLOSE FAILED accountInput STATUS "
                       ACCOUNT-INPUT-STATUS UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   IF BANK-FAILURE-CODE = SPACES
                       MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
                   END-IF
               END-IF
               MOVE "N" TO BANK-FILE-OPEN-1
           END-IF
           IF BANK-FILE-OPEN-2 = "Y"
               CLOSE POSTING-OUTPUT-FILE
               IF NOT POSTING-OUTPUT-STATUS-OK
                   DISPLAY "CLOSE FAILED postingOutput STATUS "
                       POSTING-OUTPUT-STATUS UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   IF BANK-FAILURE-CODE = SPACES
                       MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
                   END-IF
               END-IF
               MOVE "N" TO BANK-FILE-OPEN-2
           END-IF
           MOVE BANK-RETURN-CODE TO RETURN-CODE
           GOBACK.
       BANK-ACCEPT-PARM.
      *> The job's PARM, positional. See the JCL for the layout.
           IF ADDRESS OF BANK-PARM = NULL
               DISPLAY "NO PARM PASSED, 36 BYTES REQUIRED" UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               GO TO BANK-ACCEPT-PARM-EXIT
           END-IF
           IF BANK-PARM-LENGTH < 36
               DISPLAY "PARM IS " BANK-PARM-LENGTH " BYTES, 36 REQUIRED"
                   UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               GO TO BANK-ACCEPT-PARM-EXIT
           END-IF
           MOVE BANK-PARM-IDEMPOTENCY-KEY TO POST-ACCOUNTS-P3
           CONTINUE.
       BANK-ACCEPT-PARM-EXIT.
           EXIT.
       IS-OVERDRAWN.
           IF 0.00 > IS-OVERDRAWN-P1
               MOVE "Y" TO IS-OVERDRAWN-RESULT
           ELSE
               MOVE "N" TO IS-OVERDRAWN-RESULT
           END-IF
           CONTINUE.
       IS-OVERDRAWN-EXIT.
           EXIT.
       POST-ACCOUNTS.
           OPEN INPUT ACCOUNT-INPUT-FILE
           IF NOT ACCOUNT-INPUT-STATUS-OK
               DISPLAY "OPEN FAILED accountInput STATUS "
                   ACCOUNT-INPUT-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO POST-ACCOUNTS-EXIT
           END-IF
           MOVE "Y" TO BANK-FILE-OPEN-1
           OPEN OUTPUT POSTING-OUTPUT-FILE
           IF NOT POSTING-OUTPUT-STATUS-OK
               DISPLAY "OPEN FAILED postingOutput STATUS "
                   POSTING-OUTPUT-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO POST-ACCOUNTS-EXIT
           END-IF
           MOVE "Y" TO BANK-FILE-OPEN-2
           MOVE 0 TO POST-ACCOUNTS-LOOP-1
           PERFORM UNTIL POST-ACCOUNTS-LOOP-1 >= 1000000 OR NOT
               (ACCOUNT-INPUT-STATUS = "00")
               ADD 1 TO POST-ACCOUNTS-LOOP-1
               READ ACCOUNT-INPUT-FILE
                   AT END MOVE "10" TO ACCOUNT-INPUT-STATUS
                   NOT AT END
                       MOVE ACCOUNT-ID OF ACCOUNT-INPUT-RECORD TO
                           ACCOUNT-ID OF ACCOUNT-RECORD
                       MOVE BALANCE OF ACCOUNT-INPUT-RECORD TO BALANCE
                           OF ACCOUNT-RECORD
               END-READ
               IF NOT ACCOUNT-INPUT-STATUS-OK AND NOT
                   ACCOUNT-INPUT-STATUS-EOF
                   DISPLAY "READ FAILED accountInput STATUS "
                       ACCOUNT-INPUT-STATUS UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "READ-FAILED" TO BANK-FAILURE-CODE
                   GO TO POST-ACCOUNTS-EXIT
               END-IF
               IF ACCOUNT-INPUT-STATUS = "00"
                   MOVE ACCOUNT-ID OF ACCOUNT-RECORD TO
                       POSTING-ACCOUNT-ID OF POSTING-RECORD
                   MOVE BALANCE OF ACCOUNT-RECORD TO POSTING-BALANCE OF
                       POSTING-RECORD
                   MOVE BALANCE OF ACCOUNT-RECORD TO IS-OVERDRAWN-P1
                   PERFORM IS-OVERDRAWN THRU IS-OVERDRAWN-EXIT
                   IF BANK-FAILURE-CODE NOT = SPACES
                       GO TO POST-ACCOUNTS-EXIT
                   END-IF
                   IF IS-OVERDRAWN-RESULT = "Y"
                       MOVE "O" TO POSTING-FLAG OF POSTING-RECORD
                   ELSE
                       MOVE " " TO POSTING-FLAG OF POSTING-RECORD
                   END-IF
                   MOVE POSTING-ACCOUNT-ID OF POSTING-RECORD TO
                       POSTING-ACCOUNT-ID OF POSTING-OUTPUT-RECORD
                   MOVE POSTING-BALANCE OF POSTING-RECORD TO
                       POSTING-BALANCE OF POSTING-OUTPUT-RECORD
                   MOVE POSTING-FLAG OF POSTING-RECORD TO POSTING-FLAG
                       OF POSTING-OUTPUT-RECORD
                   WRITE POSTING-OUTPUT-RECORD
                   IF NOT POSTING-OUTPUT-STATUS-OK
                       DISPLAY "WRITE FAILED postingOutput STATUS "
                           POSTING-OUTPUT-STATUS UPON SYSOUT
                       MOVE 12 TO BANK-RETURN-CODE
                       MOVE "WRITE-FAILED" TO BANK-FAILURE-CODE
                       GO TO POST-ACCOUNTS-EXIT
                   END-IF
               END-IF
           END-PERFORM
           IF POST-ACCOUNTS-LOOP-1 >= 1000000 AND (ACCOUNT-INPUT-STATUS
               = "00")
               DISPLAY "LOOP LIMIT 1000000 REACHED, WORK UNFINISHED"
                   UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "BANK-LOOP-EXHAUSTED" TO BANK-FAILURE-CODE
               GO TO POST-ACCOUNTS-EXIT
           END-IF
           CLOSE POSTING-OUTPUT-FILE
           IF NOT POSTING-OUTPUT-STATUS-OK
               DISPLAY "CLOSE FAILED postingOutput STATUS "
                   POSTING-OUTPUT-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO POST-ACCOUNTS-EXIT
           END-IF
           MOVE "N" TO BANK-FILE-OPEN-2
           CLOSE ACCOUNT-INPUT-FILE
           IF NOT ACCOUNT-INPUT-STATUS-OK
               DISPLAY "CLOSE FAILED accountInput STATUS "
                   ACCOUNT-INPUT-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO POST-ACCOUNTS-EXIT
           END-IF
           MOVE "N" TO BANK-FILE-OPEN-1
           MOVE "ACCOUNTS_POSTED" TO BANK-AUDIT-EVENT
           MOVE POST-ACCOUNTS-P3 TO BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       POST-ACCOUNTS-EXIT.
           EXIT.
