       *> Generated by bankc.
       *> Do not edit this file directly.
       *> Source maps are available in dist/maps.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCOUNT-FILE-BATCH.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT ACCOUNT-INPUT-FILE ASSIGN TO ACCOUNTI
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS ACCOUNT-INPUT-STATUS.
           SELECT POSTING-OUTPUT-FILE ASSIGN TO POSTINGO
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS POSTING-OUTPUT-STATUS.

       DATA DIVISION.
       FILE SECTION.
       FD  ACCOUNT-INPUT-FILE.
       01  ACCOUNT-INPUT-RECORD.
           05  ACCOUNT-ID           PIC X(16).
           05  BALANCE              PIC S9(16)V99 COMP-3.
       FD  POSTING-OUTPUT-FILE.
       01  POSTING-OUTPUT-RECORD.
           05  POSTING-ACCOUNT-ID   PIC X(16).
           05  POSTING-BALANCE      PIC S9(16)V99 COMP-3.
           05  POSTING-FLAG         PIC X(1).
       WORKING-STORAGE SECTION.
       01  ACCOUNT-INPUT-STATUS PIC XX.
       01  POSTING-OUTPUT-STATUS PIC XX.
       01  ACCOUNT-RECORD.
           05  ACCOUNT-ID           PIC X(16).
           05  BALANCE              PIC S9(16)V99 COMP-3.
       01  POSTING-RECORD.
           05  POSTING-ACCOUNT-ID   PIC X(16).
           05  POSTING-BALANCE      PIC S9(16)V99 COMP-3.
           05  POSTING-FLAG         PIC X(1).
       01  IS-OVERDRAWN-RESULT PIC X VALUE 'N'.
       01  IS-OVERDRAWN-P1      PIC S9(16)V99 COMP-3.
       01  POST-ACCOUNTS-P3     PIC X(36).
       01  WS-LOOP-34-3         PIC 9(9) COMP.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION    PIC X(6).
           05  BANK-LEDGER-ACCOUNT      PIC X(32).
           05  BANK-LEDGER-AMOUNT       PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT         PIC X(32).
           05  BANK-AUDIT-CORRELATION   PIC X(64).

       PROCEDURE DIVISION.
       BANK-MAIN.
           PERFORM POST-ACCOUNTS
           GOBACK.
       IS-OVERDRAWN.
           IF 0.00 > IS-OVERDRAWN-P1
               MOVE 'Y' TO IS-OVERDRAWN-RESULT
           ELSE
               MOVE 'N' TO IS-OVERDRAWN-RESULT
           END-IF
           CONTINUE.
       POST-ACCOUNTS.
           OPEN INPUT ACCOUNT-INPUT-FILE
           IF ACCOUNT-INPUT-STATUS(1:1) NOT = "0"
               DISPLAY "OPEN FAILED accountInput STATUS "
                   ACCOUNT-INPUT-STATUS UPON SYSOUT
               MOVE 12 TO RETURN-CODE
               GOBACK
           END-IF
           OPEN OUTPUT POSTING-OUTPUT-FILE
           IF POSTING-OUTPUT-STATUS(1:1) NOT = "0"
               DISPLAY "OPEN FAILED postingOutput STATUS "
                   POSTING-OUTPUT-STATUS UPON SYSOUT
               MOVE 12 TO RETURN-CODE
               GOBACK
           END-IF
           MOVE 0 TO WS-LOOP-34-3
           PERFORM UNTIL WS-LOOP-34-3 >= 1000000 OR NOT
               (ACCOUNT-INPUT-STATUS = "00")
               ADD 1 TO WS-LOOP-34-3
               READ ACCOUNT-INPUT-FILE
                   AT END MOVE "10" TO ACCOUNT-INPUT-STATUS
               END-READ
               IF ACCOUNT-INPUT-STATUS(1:1) NOT = "0" AND
                   ACCOUNT-INPUT-STATUS NOT = "10"
                   DISPLAY "READ FAILED accountInput STATUS "
                       ACCOUNT-INPUT-STATUS UPON SYSOUT
                   MOVE 12 TO RETURN-CODE
                   GOBACK
               END-IF
               MOVE ACCOUNT-ID OF ACCOUNT-INPUT-RECORD TO ACCOUNT-ID OF
                   ACCOUNT-RECORD
               MOVE BALANCE OF ACCOUNT-INPUT-RECORD TO BALANCE OF
                   ACCOUNT-RECORD
               IF ACCOUNT-INPUT-STATUS = "00"
                   MOVE ACCOUNT-ID OF ACCOUNT-RECORD TO
                       POSTING-ACCOUNT-ID OF POSTING-RECORD
                   COMPUTE POSTING-BALANCE OF POSTING-RECORD = BALANCE
                       OF ACCOUNT-RECORD
                   MOVE BALANCE OF ACCOUNT-RECORD TO IS-OVERDRAWN-P1
                   PERFORM IS-OVERDRAWN
                   IF IS-OVERDRAWN-RESULT = 'Y'
                       MOVE "O" TO POSTING-FLAG OF POSTING-RECORD
                   ELSE
                       MOVE " " TO POSTING-FLAG OF POSTING-RECORD
                   END-IF
                   MOVE POSTING-ACCOUNT-ID OF POSTING-RECORD TO
                       POSTING-ACCOUNT-ID OF POSTING-OUTPUT-RECORD
                   MOVE POSTING-BALANCE OF POSTING-RECORD TO
                       POSTING-BALANCE OF POSTING-OUTPUT-RECORD
                   MOVE POSTING-FLAG OF POSTING-RECORD TO POSTING-FLAG
                       OF POSTING-OUTPUT-RECORD
                   WRITE POSTING-OUTPUT-RECORD
                   IF POSTING-OUTPUT-STATUS(1:1) NOT = "0"
                       DISPLAY "WRITE FAILED postingOutput STATUS "
                           POSTING-OUTPUT-STATUS UPON SYSOUT
                       MOVE 12 TO RETURN-CODE
                       GOBACK
                   END-IF
               END-IF
           END-PERFORM
           CLOSE POSTING-OUTPUT-FILE
           IF POSTING-OUTPUT-STATUS(1:1) NOT = "0"
               DISPLAY "CLOSE FAILED postingOutput STATUS "
                   POSTING-OUTPUT-STATUS UPON SYSOUT
               MOVE 12 TO RETURN-CODE
               GOBACK
           END-IF
           CLOSE ACCOUNT-INPUT-FILE
           IF ACCOUNT-INPUT-STATUS(1:1) NOT = "0"
               DISPLAY "CLOSE FAILED accountInput STATUS "
                   ACCOUNT-INPUT-STATUS UPON SYSOUT
               MOVE 12 TO RETURN-CODE
               GOBACK
           END-IF
           MOVE "ACCOUNTS_POSTED" TO BANK-AUDIT-EVENT
           MOVE POST-ACCOUNTS-P3 TO BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           GOBACK.
