*> Generated by bankc.
*> Do not edit this file directly.
*> Source maps are available in dist/maps.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. BATCH-INTEREST-ACCRUAL.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  INTEREST-ACCOUNT.
           05  ACCOUNT-ID           PIC X(16).
           05  BALANCE              PIC S9(16)V99 COMP-3.
       01  IS-ELIGIBLE-FOR-INTEREST-RESULT PIC X VALUE 'N'.

       PROCEDURE DIVISION.
       IS-ELIGIBLE-FOR-INTEREST.
           IF BALANCE > 1000.00
               MOVE 'Y' TO IS-ELIGIBLE-FOR-INTEREST-RESULT
               GOBACK.
           ELSE
               MOVE 'N' TO IS-ELIGIBLE-FOR-INTEREST-RESULT
               GOBACK.
           END-IF
