//* Generated by bankc.
//* Do not edit this file directly.
//BATCHINT JOB (BANKLANG),'BATCH-INTEREST-ACCRUAL',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/BATCH-INTEREST-ACCRUAL.cbl
//* COPYBOOK source: dist/copybooks/INTEREST-ACCOUNT.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.BATCHINTERESTACCRUAL
//* The compile step above is a documentation-friendly skeleton.
