//* Generated by bankc. Do not edit this file directly.
//ZUNITTES JOB (BANKLANG),'ZUNIT-TESTED-POSTING',
//             CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID,REGION=0M
//* Compile, link-edit, and run the generated COBOL program.
//* Source member:   BANKLANG.COBOL(ZUNITTES)
//* Load module:     BANKLANG.LOADLIB(ZUNITTES)
//* Dataset names, unit and space parameters are placeholders for a
//* site's own standards. See docs/jcl-model.md.
//* IGYWCL is IBM's compile-and-link cataloged procedure. It supplies
//* STEPLIB, SYSUT1-SYSUT15, SYSMDECK, the LE link libraries, and
//* REGION=0M. Only the site-specific DDs are overridden here.
//* PGMLIB must name a load library that already exists: the
//* procedure allocates SYSLMOD DISP=(MOD,PASS), so a library that
//* does not exist is created, passed, and gone at end of job.
//COMPILE  EXEC IGYWCL,
//             LNGPRFX='IGY.V6R4M0',LIBPRFX='CEE',
//             PGMLIB='BANKLANG.LOADLIB',GOPGM=ZUNITTES
//COBOL.SYSIN    DD DISP=SHR,DSN=BANKLANG.COBOL(ZUNITTES)
//LKED.SYSLIB    DD DISP=SHR,DSN=BANKLANG.OBJLIB
//               DD DISP=SHR,DSN=CEE.SCEELKEX
//               DD DISP=SHR,DSN=CEE.SCEELKED
//* PARM layout, positional, one field per entry parameter:
//*   account X(16) (16)
//*   amount S9(16)V99 SIGN IS LEADING SEPARATE (19)
//*   idempotencyKey X(36) (36)
//RUN      EXEC PGM=ZUNITTES,
//             PARM='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//             xxxxxxxxxxxxxxxxxxxxx',
//             REGION=0M,COND=(4,LT)
//STEPLIB  DD DISP=SHR,DSN=BANKLANG.LOADLIB
//         DD DISP=SHR,DSN=CEE.SCEERUN
//         DD DISP=SHR,DSN=CEE.SCEERUN2
//SYSOUT   DD SYSOUT=*
//CEEOPTS  DD *
  TERMTHDACT(UADUMP)
  TRAP(ON)
/*
//CEEDUMP  DD SYSOUT=*
//SYSUDUMP DD SYSOUT=*
