/**
 * Build the whole site: landing page, playground, assets.
 *
 * The 2026-08-06 audit's central finding was that this project has no front
 * door — a visitor arriving from a link lands in a split-pane editor with no
 * context. This is that front door.
 *
 * **Every claim on the page is generated, not written.** The diagnostics in the
 * refusal section come from running the compiler over the program printed
 * beside them. The COBOL comes from compiling the BankTS printed beside it, cut
 * to the paragraph by name. The counts come from counting. Nothing on the page
 * is a string somebody typed and nobody checked again, which is the failure
 * mode a landing page has: it ages into a claim the software stopped making.
 *
 * `tests/site.test.ts` holds that: it builds the page and asserts the COBOL on
 * it is the COBOL the compiler emits today.
 *
 * Output:
 *
 *     dist/site/
 *       index.html          the landing page
 *       assets/site.css     its stylesheet, and nothing else
 *       docs/               every page under docs/, rendered
 *       playground/         the existing bundle, unchanged
 *       schema/banklang.json  the config schema `bankc init` points at
 *       favicon.svg  og.png  robots.txt  sitemap.xml
 *       _headers            response headers, read by Cloudflare Pages
 *
 * Usage: pnpm build:site
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildAbout, buildBlog, buildFeed, posts } from "./build-blog";
import { buildDocs, directoriesOf, docFiles } from "./build-docs";
import { checkPlaygroundBudget } from "./bundle-budget";
import { compile } from "../packages/compiler/src/index";
import { SCHEMA_URL } from "../packages/config/src/index";
import { configJsonSchema } from "../packages/config/src/schema";
import {
  DIAGNOSTICS,
  isBankingSafetyRule,
} from "../packages/diagnostics/src/index";
import { gradeExamples } from "./evidence-grades";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "dist/site");
const SITE = join(ROOT, "packages/site/src");

/** The domain the site is served from, for canonical and Open Graph URLs. */
export const SITE_ORIGIN = "https://banklang.mwhassan.com";

/**
 * The URL a built file is actually served at.
 *
 * Cloudflare Pages does not serve `.html`. A request for `/docs/glossary.html`
 * is answered with a 308 to `/docs/glossary`, and `/docs/index.html` with a 308
 * to `/docs/`. Everything this build writes lands on disk as `.html`, so the
 * path a file has and the URL it answers on are two different strings — and
 * every canonical, `og:url`, sitemap entry and feed link has to use the second.
 *
 * F11 is what happens when they are written out by hand instead. Forty-seven of
 * fifty-one sitemap entries named the redirecting form, which Search Console
 * reports as "Page with redirect, not indexed", and the two indexes disagreed
 * with each other: the docs index declared `…/docs/index.html` canonical while
 * its own sitemap entry said `…/docs/`. One page, two URLs, and a search engine
 * choosing between them.
 *
 * Derived here so there is one rule. `tests/docs-site.test.ts` holds every
 * sitemap entry to the canonical of the page it names, which is the invariant
 * that was broken rather than a restatement of this function.
 */
export function servedPath(builtPath: string): string {
  const path = builtPath.replace(/\\/g, "/").replace(/^\/+/, "");
  if (path === "index.html") {
    return "/";
  }
  if (path.endsWith("/index.html")) {
    return `/${path.slice(0, -"index.html".length)}`;
  }
  return `/${path.replace(/\.html$/, "")}`;
}

/** The absolute URL a built file is served at. */
export function servedUrl(builtPath: string): string {
  return `${SITE_ORIGIN}${servedPath(builtPath)}`;
}

/**
 * The theme control, which is a toggle button rather than an action.
 *
 * E5. It read `Theme` with an `aria-label` of "Switch between light and dark",
 * no `aria-pressed`, and a label that never changed — so neither a sighted nor
 * a screen-reader user could tell the current mode from the control.
 *
 * The label names what is being toggled and `aria-pressed` says whether it is
 * on. The ticket's other suggestion was a label naming the destination, "Dark"
 * while light and "Light" while dark, and the two cannot both be right: a
 * control whose label is where it takes you is an action, and `aria-pressed` on
 * an action announces a state its own label contradicts.
 *
 * Held here, so the documentation and blog shells cannot drift from each other.
 * `packages/site/src/index.html` and the playground carry their own copy —
 * neither is generated by this file — and `tests/site.test.ts` holds all four
 * to the same behaviour.
 */
export const THEME_BUTTON = `<button id="theme" type="button" class="ghost" aria-pressed="false">Dark mode</button>`;

export const THEME_SCRIPT = `    <script>
      (() => {
        const button = document.getElementById("theme");
        const root = document.documentElement;
        const dark = matchMedia("(prefers-color-scheme: dark)");
        const isDark = () =>
          root.dataset.theme === "dark" || (!root.dataset.theme && dark.matches);
        const sync = () => button.setAttribute("aria-pressed", String(isDark()));
        sync();
        // The preference can change without a click, and then the button is
        // announcing a state that is no longer true.
        dark.addEventListener("change", sync);
        button.addEventListener("click", () => {
          root.dataset.theme = isDark() ? "light" : "dark";
          localStorage.setItem("banklang-theme", root.dataset.theme);
          sync();
        });
      })();
    </script>`;

/* ------------------------------------------------------------------ *
 * Syntax highlighting, at build time.
 *
 * L2: no runtime JavaScript beyond the theme toggle. A highlighter shipped to
 * the browser to colour four code blocks is 40 KB to do what a build can do
 * once. These are deliberately small — enough for the constructs on this page.
 * ------------------------------------------------------------------ */

export const escapeHtml = (text: string): string =>
  text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const BANKTS_KEYWORDS =
  /\b(module|type|record|function|transaction|return|let|if|else|for|each|in|raise|on|failure|file|test|currency|decimal|string|bool|date|enum|extends)\b/g;

export function highlightBankTs(code: string): string {
  return escapeHtml(code)
    .replace(/(\/\/[^\n]*)/g, '<span class="c-com">$1</span>')
    .replace(/(&quot;[^&]*?&quot;)/g, '<span class="c-str">$1</span>')
    .replace(BANKTS_KEYWORDS, '<span class="c-kw">$1</span>')
    .replace(/\b(\d+(?:\.\d+)?)\b/g, '<span class="c-num">$1</span>');
}

/**
 * COBOL in fixed reference format.
 *
 * The indicator area matters: an asterisk or `*>` in column 7 is a comment, and
 * colouring it as code would misrepresent the output on the one page where a
 * mainframe engineer is deciding whether the output is readable.
 */
export function highlightCobol(code: string): string {
  return code
    .split("\n")
    .map((line) => {
      const escaped = escapeHtml(line);
      if (/^.{6}[*/]/.test(line) || /^\s*\*>/.test(line)) {
        return `<span class="c-com">${escaped}</span>`;
      }
      return escaped
        .replace(/(&quot;[^&]*?&quot;)/g, '<span class="c-str">$1</span>')
        .replace(
          /\b(IDENTIFICATION|ENVIRONMENT|DATA|PROCEDURE|DIVISION|SECTION|PROGRAM-ID|MOVE|COMPUTE|IF|ELSE|END-IF|EVALUATE|WHEN|END-EVALUATE|PERFORM|CALL|GO TO|GOBACK|ADD|SUBTRACT|MULTIPLY|DIVIDE|OPEN|CLOSE|READ|WRITE|EXEC|END-EXEC|PIC|VALUE|COMP-3|OCCURS|FUNCTION|ON SIZE ERROR|END-COMPUTE|DISPLAY|UPON|THRU|USING|TO|FROM|BY|INTO)\b/g,
          '<span class="c-kw">$1</span>',
        )
        .replace(/\b(\d+(?:\.\d+)?)\b/g, '<span class="c-num">$1</span>');
    })
    .join("\n");
}

/* ------------------------------------------------------------------ *
 * The content, taken from the compiler.
 * ------------------------------------------------------------------ */

/** The program the refusal section shows, and the diagnostics it earns. */
const UNSAFE = `transaction postTransfer(request: TransferRequest) {
  debit(request.debitAccount, request.amount);
  credit(request.creditAccount, request.fee);
}`;

const UNSAFE_MODULE = `module Unsafe;

type MoneyBDT = decimal<18, 2>;

record TransferRequest {
  debitAccount: string<16>;
  creditAccount: string<16>;
  amount: MoneyBDT;
  fee: MoneyBDT;
}

${UNSAFE}
`;

/** One paragraph of a compiled program, found by its own label. */
function paragraph(cobol: string, label: string): string {
  const lines = cobol.split("\n");
  const start = lines.findIndex((line) => line.trim() === `${label}.`);
  if (start < 0) {
    throw new Error(`No paragraph ${label} in the generated COBOL.`);
  }
  const end = lines.findIndex(
    (line, index) =>
      index > start && /^ {7}[A-Z][A-Z0-9-]*\.\s*$/.test(line.trimEnd()),
  );
  return lines
    .slice(start, end < 0 ? lines.length : end)
    .join("\n")
    .trimEnd();
}

export interface SiteContent {
  diagnostics: string;
  /** Examples run against the reference runtime, counted from the grades. */
  executed: number;
  /** Of those, the ones with hand-written expected values. */
  asserted: number;
  accrueSource: string;
  accrueCobol: string;
  originalCobol: string;
  convertedBankTs: string;
  examples: number;
  diagnosticCount: number;
  /** Of those, the ones about what the program does with money. */
  safetyRuleCount: number;
}

export function siteContent(): SiteContent {
  const grades = gradeExamples(ROOT);
  const unsafe = compile(UNSAFE_MODULE, { sourceFile: "unsafe.bank.ts" });
  if (unsafe.diagnostics.length === 0) {
    throw new Error(
      "The refusal example compiled cleanly. The page would be showing a claim the compiler no longer makes.",
    );
  }

  const interest = readFileSync(
    join(ROOT, "examples/interest-posting-batch/src/main.bank.ts"),
    "utf8",
  );
  const compiled = compile(interest, { sourceFile: "main.bank.ts" });
  if (!compiled.cobol) {
    throw new Error("interest-posting-batch no longer compiles.");
  }

  // The `accrue` function as it is written, with the comment above it: it says
  // why the rounding mode is required, which is the point of the section.
  const accrueStart = interest.indexOf("function accrue(");
  const lines = interest.slice(0, accrueStart).split("\n");
  let comment = lines.length - 1;
  while (comment > 0 && lines[comment - 1]!.startsWith("//")) {
    comment -= 1;
  }
  const accrueSource = (
    lines.slice(comment).join("\n") +
    interest.slice(accrueStart, interest.indexOf("\n}\n", accrueStart) + 2)
  ).trim();

  const original = readFileSync(
    join(ROOT, "conversions/01-sequential-update/original/ACCTUPDT.cbl"),
    "utf8",
  );
  const converted = readFileSync(
    join(ROOT, "conversions/01-sequential-update/banklang/src/main.bank.ts"),
    "utf8",
  );

  return {
    diagnostics: unsafe.diagnostics
      .map((entry) => `${entry.id.padEnd(14)}${entry.message}`)
      .join("\n"),
    accrueSource,
    accrueCobol: paragraph(compiled.cobol, "ACCRUE"),
    originalCobol: fileHandling(original),
    convertedBankTs: fileDeclarations(converted),
    // Both counts from the same list, or the sentence is nonsense. `examples/`
    // holds 21 directories and 23 programs, because one of them is a job of
    // several; counting directories for the denominator and programs for the
    // numerator read as "21 of 21 are executed" when two are not.
    examples: grades.length,
    // Counted from the same grader `evidence/GRADES.md` is generated by, not
    // written on the page. The landing page said "three of 22 are executed"
    // for as long as that was true and for a while after it stopped being.
    executed: grades.filter((entry) => entry.grade === "executed").length,
    asserted: grades.filter(
      (entry) => entry.grade === "executed" && entry.reason === "",
    ).length,
    diagnosticCount: DIAGNOSTICS.filter((entry) => entry.implemented).length,
    // Both counts, because the sentence they appear in is about the banking
    // safety rules and the page used the whole catalogue for it — 94 where the
    // claim was 16. `isBankingSafetyRule` is what decides, next to the
    // catalogue, so a new diagnostic is classified by where it is filed.
    safetyRuleCount: DIAGNOSTICS.filter(
      (entry) => entry.implemented && isBankingSafetyRule(entry.id),
    ).length,
  };
}

/**
 * Everything the original says about its four files, which is both halves.
 *
 * F29. This was six lines from `0000-MAIN.` — the `OPEN` — under a paragraph
 * arguing "no `FILE STATUS` field declared for any of them". A reader who has
 * written COBOL assumes the clauses are in the `FILE-CONTROL` paragraph that is
 * not being shown, because that is exactly where they would be. The argument
 * was sound and the exhibit did not support it.
 *
 * So both are on screen: the `SELECT` statements, where a `FILE STATUS` would
 * be and is not, and the `OPEN` whose outcome nothing then tests. They are
 * forty lines apart in the file, and the elision is marked rather than closed
 * up, because a listing that silently joins two places is its own small lie.
 */
function fileHandling(text: string): string {
  const lines = text.split("\n");
  const at = (marker: string): number => {
    const index = lines.findIndex((line) => line.includes(marker));
    if (index < 0) {
      throw new Error(`No line contains ${marker}.`);
    }
    return index;
  };

  // `FILE-CONTROL.` and its four `SELECT`s; `0000-MAIN.` and the `OPEN` that
  // names all four files in one statement.
  const selects = at("FILE-CONTROL.");
  const open = at("0000-MAIN.");
  const elided = open - (selects + 5);

  return [
    lines.slice(selects, selects + 5).join("\n"),
    // Column 7, which is where this program's own comments are, so the
    // highlighter reads it as one.
    `      *    ${String(elided)} lines: the FDs and WORKING-STORAGE`,
    lines.slice(open, open + 5).join("\n"),
  ].join("\n");
}

/** The `file` declarations of the converted program, which carry the status. */
function fileDeclarations(source: string): string {
  const lines = source.split("\n");
  const start = lines.findIndex((line) => line.startsWith("file "));
  if (start < 0) {
    throw new Error("The converted program declares no files.");
  }
  const end = lines.findIndex(
    (line, index) => index > start && line.startsWith("}"),
  );
  return lines
    .slice(start, end + 1)
    .join("\n")
    .trimEnd();
}

/* ------------------------------------------------------------------ *
 * The page.
 * ------------------------------------------------------------------ */

export function renderLanding(content: SiteContent): string {
  const template = readFileSync(join(SITE, "index.html"), "utf8");
  const fills: Record<string, string> = {
    UNSAFE_BANKTS: highlightBankTs(UNSAFE),
    DIAGNOSTICS: escapeHtml(content.diagnostics),
    ACCRUE_BANKTS: highlightBankTs(content.accrueSource),
    ACCRUE_COBOL: highlightCobol(content.accrueCobol),
    ORIGINAL_COBOL: highlightCobol(content.originalCobol),
    CONVERTED_BANKTS: highlightBankTs(content.convertedBankTs),
    EXAMPLE_COUNT: String(content.examples),
    EXECUTED_COUNT: String(content.executed),
    ASSERTED_COUNT: String(content.asserted),
    DIAGNOSTIC_COUNT: String(content.diagnosticCount),
    SAFETY_RULE_COUNT: String(content.safetyRuleCount),
    ORIGIN: SITE_ORIGIN,
  };

  let page = template;
  for (const [key, value] of Object.entries(fills)) {
    if (!page.includes(`{{${key}}}`)) {
      throw new Error(`The template has no {{${key}}} to fill.`);
    }
    page = page.replaceAll(`{{${key}}}`, value);
  }
  const leftover = /\{\{([A-Z_]+)\}\}/.exec(page);
  if (leftover) {
    throw new Error(`{{${leftover[1]}}} was never filled.`);
  }
  return page;
}

/**
 * Every page this build writes, as the path it lands on disk.
 *
 * One list, so the sitemap cannot fall behind what is rendered. It already had:
 * `buildDocs` writes an index for `docs/language/` and `docs/adr/` — two real
 * pages a link can land on — and neither was in the sitemap, because the
 * sitemap held its own idea of what the site contains.
 *
 * `tests/docs-site.test.ts` walks `dist/site` and holds this list to the HTML
 * actually on disk, in both directions.
 */
export function builtPages(): string[] {
  const files = docFiles();
  return [
    "index.html",
    "about/index.html",
    "playground/index.html",
    "docs/index.html",
    ...directoriesOf(files).map((directory) => `docs/${directory}/index.html`),
    ...files.map((file) => `docs/${file.replace(/\.md$/, ".html")}`),
    "blog/index.html",
    ...posts().map((post) => `blog/${post.slug}.html`),
  ];
}

/**
 * The `'sha256-…'` sources that allow one page's inline scripts.
 *
 * A CSP hash is taken over the exact bytes between `<script>` and `</script>`
 * — leading and trailing whitespace included — so this reads the built page
 * rather than the template that produced it. Anything with a `src` is a file
 * and is already covered by `'self'`.
 */
export function inlineScriptHashes(html: string): string[] {
  const inline = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g;
  return [...html.matchAll(inline)].map(
    (match) =>
      `'sha256-${createHash("sha256")
        .update(match[1] ?? "", "utf8")
        .digest("base64")}'`,
  );
}

/**
 * Cloudflare's limit on one line of `_headers`. The policy is a single line and
 * grows by one hash per blog post, so this is a wall worth hitting in a build
 * rather than in a deployment that silently drops the header.
 */
const HEADER_LINE_LIMIT = 2000;

/** Where the script hashes go in `packages/site/src/_headers`. */
const PLACEHOLDER = "__SCRIPT_HASHES__";

/** `_headers` with the script hashes filled in, and held to that limit. */
export function responseHeaders(template: string, hashes: string[]): string {
  /*
   * Exactly one placeholder, checked rather than assumed.
   *
   * `String.replace` with a string pattern substitutes the *first* occurrence,
   * and the first draft of the comment above the policy named the placeholder
   * while explaining it — so the hashes were written into a comment and the
   * policy line shipped the literal token. A CSP source expression nothing
   * matches is not a loud failure: it is every inline script on all fifty-four
   * pages silently refusing to run, which is the theme on each of them and the
   * documentation search.
   */
  const occurrences = template.split(PLACEHOLDER).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `_headers names ${String(occurrences)} ${PLACEHOLDER} placeholders and the ` +
        `policy needs exactly one. Mention it in prose and the hashes land in a comment.`,
    );
  }

  // Sorted, because the set comes from walking a directory and a build that
  // reorders a header is a build that is not deterministic.
  const filled = template.replace(
    PLACEHOLDER,
    [...new Set(hashes)].sort().join(" "),
  );

  const longest = Math.max(
    ...filled.split("\n").map((line) => line.trimStart().length),
  );
  if (longest > HEADER_LINE_LIMIT) {
    throw new Error(
      `_headers has a ${String(longest)}-character line and Cloudflare's limit ` +
        `is ${String(HEADER_LINE_LIMIT)}. The content policy names one hash per ` +
        `distinct inline script; the way down is fewer of them, not a longer line.`,
    );
  }
  return filled;
}

function sitemap(): string {
  const today = new Date().toISOString().slice(0, 10);
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    // `servedUrl`, not the file path. F11: every one of these named the `.html`
    // form, which the host answers with a redirect rather than with the page.
    ...builtPages().map(
      (page) =>
        `  <url><loc>${servedUrl(page)}</loc><lastmod>${today}</lastmod></url>`,
    ),
    "</urlset>",
    "",
  ].join("\n");
}

function main(): void {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(join(OUT, "assets"), { recursive: true });

  const content = siteContent();
  writeFileSync(join(OUT, "index.html"), renderLanding(content));
  cpSync(join(SITE, "site.css"), join(OUT, "assets/site.css"));
  cpSync(join(SITE, "docs.css"), join(OUT, "assets/docs.css"));
  cpSync(join(SITE, "docs.js"), join(OUT, "assets/docs.js"));
  cpSync(join(SITE, "blog.css"), join(OUT, "assets/blog.css"));

  // D1: every document under `docs/`, rendered, with the sidebar grouped as the
  // README groups it and a search index built from the same pass.
  const documents = buildDocs(OUT);

  // And the writing, which is the front door for a reader who arrives from a
  // search rather than from the repository. The feed is how they come back
  // without one, and `/about/` is where the byline on each post lands.
  const written = buildBlog(OUT);
  buildFeed(OUT, written);
  buildAbout(OUT);

  // The playground, built by its own tooling and copied in unchanged. Its
  // `base: "./"` is what lets it work from `/playground/`.
  execFileSync("pnpm", ["playground:build"], { cwd: ROOT, stdio: "inherit" });

  // D4's half that prevents recurrence. Vite has printed "(!) Some chunks are
  // larger than 500 kB" on every build for as long as there has been a
  // playground, and a warning nobody acts on is not a check. Before the copy,
  // so an over-budget bundle stops the build rather than being published and
  // then reported.
  const budget = checkPlaygroundBudget(ROOT);
  process.stdout.write(budget.report);
  for (const note of budget.slack) {
    process.stdout.write(`\n${note}\n`);
  }

  cpSync(join(ROOT, "packages/playground/dist"), join(OUT, "playground"), {
    recursive: true,
  });

  cpSync(
    join(ROOT, "packages/playground/public/favicon.svg"),
    join(OUT, "favicon.svg"),
  );
  const og = join(SITE, "og.png");
  if (existsSync(og)) {
    cpSync(og, join(OUT, "og.png"));
  } else {
    console.warn("No og.png; run tools/build-og.ts to regenerate it.");
  }

  // The schema `bankc init` writes into every generated `banklang.json`.
  //
  // The path comes from the URL rather than being written out again beside it:
  // a generated config points an editor at `SCHEMA_URL`, and the only thing
  // that makes that resolve is this file landing at exactly that path. Deriving
  // it means the two cannot be changed apart.
  const schemaPath = join(OUT, new URL(SCHEMA_URL).pathname);
  mkdirSync(dirname(schemaPath), { recursive: true });
  writeFileSync(schemaPath, `${JSON.stringify(configJsonSchema(), null, 2)}\n`);

  writeFileSync(
    join(OUT, "robots.txt"),
    [
      "User-agent: *",
      "Allow: /",
      "",
      `Sitemap: ${SITE_ORIGIN}/sitemap.xml`,
      // Not a directive any crawler acts on, and the conventional place to
      // leave it: a reader who fetches robots.txt to find the feed finds it.
      `# Feed: ${SITE_ORIGIN}/blog/feed.xml`,
      "",
    ].join("\n"),
  );
  writeFileSync(join(OUT, "sitemap.xml"), sitemap());

  // Response headers, which are the only part of the site nothing renders: a
  // security policy, the cache lifetimes, and `noindex` on the preview
  // hostname. Last, because the content policy names the sha256 of every inline
  // script on the finished site — read off the built pages, including the
  // playground's, which Vite writes rather than this file.
  const pages = readdirSync(OUT, { recursive: true, encoding: "utf8" }).filter(
    (file) => file.endsWith(".html"),
  );
  writeFileSync(
    join(OUT, "_headers"),
    responseHeaders(
      readFileSync(join(SITE, "_headers"), "utf8"),
      pages.flatMap((page) =>
        inlineScriptHashes(readFileSync(join(OUT, page), "utf8")),
      ),
    ),
  );

  console.log(
    `Built ${OUT} (${String(documents)} documents, ${String(written.length)} posts)`,
  );
}

if (process.argv[1]?.endsWith("build-site.ts")) {
  main();
}
