/**
 * Extract Enterprise COBOL's own vocabulary from the Language Reference.
 *
 * `packages/conformance-lint/src/ibm-words.ts` is generated by this and checked
 * in, so the linter needs no vendor document at run time and a change to the
 * list arrives as a reviewable diff rather than as a silent difference between
 * two machines.
 *
 * Two tables:
 *
 * Appendix E, "Reserved words", has three columns. Only the first — words
 * "reserved for function implemented in Enterprise COBOL" — is the target's
 * vocabulary. The second is 85 Standard words for function Enterprise COBOL
 * does not implement, and the third is words that "might be reserved in a
 * future release", which includes the 2002 Standard. `NEAREST-EVEN` is in none
 * of the three, which is the whole point: `ROUNDED MODE IS NEAREST-EVEN`
 * compiled locally and named a word Enterprise COBOL has never heard of.
 *
 * Table 59, "Table of functions", is the intrinsic function names. They are not
 * reserved words — a program may declare a data item called `LENGTH` — but they
 * are words a generated program may use, so the linter has to know them.
 *
 *   pnpm tsx tools/extract-ibm-words.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const LANGUAGE_REFERENCE = "vendor-docs/cobol-language-reference.txt";
const OUTPUT = "packages/conformance-lint/src/ibm-words.ts";

/**
 * Words in the leftmost column of Appendix E's table.
 *
 * The three columns are told apart by where the X sits, and the column
 * positions differ from page to page — the extracted text alternates between
 * two indentations. Each page reprints the header, so the header on the page
 * above a row is what says which column that row's X is in.
 */
export function extractReservedWords(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex(
    (line) => line.trim() === "Appendix E. Reserved words",
  );
  const end = lines.findIndex(
    (line, index) => index > start && line.trim().startsWith("Appendix F."),
  );
  if (start === -1 || end === -1) {
    throw new Error("Appendix E not found in the Language Reference.");
  }

  const words = new Set<string>();
  let columns: number[] | null = null;

  for (const line of lines.slice(start, end)) {
    if (
      line.includes("Reserved") &&
      line.includes("Standard only") &&
      line.includes("Potential")
    ) {
      columns = [
        line.indexOf("Reserved"),
        line.indexOf("Standard only"),
        line.indexOf("Potential"),
      ];
      continue;
    }
    const row = /^\s*([A-Z][A-Z0-9-]*)\s+X\s*$/.exec(line);
    if (!row || !columns) {
      continue;
    }
    const mark = line.lastIndexOf("X");
    const at = columns;
    const nearest = at.reduce(
      (best, column, index) =>
        Math.abs(mark - column) < Math.abs(mark - at[best]!) ? index : best,
      0,
    );
    if (nearest === 0) {
      words.add(row[1]!);
    }
  }

  return [...words].sort();
}

/** Intrinsic function names, from Table 59. */
export function extractFunctionNames(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex((line) =>
    line.includes("Table 59. Table of functions"),
  );
  if (start === -1) {
    throw new Error("Table 59 not found in the Language Reference.");
  }

  const words = new Set<string>();
  for (const line of lines.slice(start, start + 330)) {
    const row = /^\s*([A-Z][A-Z0-9-]{2,30})\s{2,}\S/.exec(line);
    if (!row) {
      continue;
    }
    const name = row[1]!;
    if (["FUNCTION", "TABLE", "TYPE", "ARGUMENT", "VALUE"].includes(name)) {
      continue;
    }
    words.add(name);
  }

  // The page break lands mid-name here, and a name the extractor invents is
  // worse than one it misses: without the correction the linter would accept
  // `FUNCTION SECONDS-FROM-FORMATTED-` and reject the real one.
  if (words.delete("SECONDS-FROM-FORMATTED-")) {
    words.add("SECONDS-FROM-FORMATTED-TIME");
  }

  return [...words].sort();
}

export function renderIbmWords(text: string): string {
  const reserved = extractReservedWords(text);
  const functions = extractFunctionNames(text);

  return [
    "/**",
    " * Enterprise COBOL 6.4's own vocabulary.",
    " *",
    ` * Generated from ${LANGUAGE_REFERENCE} by tools/extract-ibm-words.ts.`,
    " * Do not edit by hand: run the extractor, and review the diff.",
    " *",
    " * RESERVED_WORDS is the leftmost column of Appendix E, Table 83 — the words",
    " * reserved for function Enterprise COBOL actually implements. It is not the",
    " * whole table. The 85 Standard words it does not implement and the words that",
    " * might be reserved in a future release are deliberately excluded, because a",
    " * generated program using one of those is using something the target has no",
    " * meaning for.",
    " *",
    " * FUNCTION_NAMES is Table 59, the intrinsic functions.",
    " */",
    "",
    `export const RESERVED_WORDS: ReadonlySet<string> = new Set([`,
    ...reserved.map((word) => `  "${word}",`),
    "]);",
    "",
    `export const FUNCTION_NAMES: ReadonlySet<string> = new Set([`,
    ...functions.map((word) => `  "${word}",`),
    "]);",
    "",
  ].join("\n");
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const cwd = process.cwd();
  const text = readFileSync(resolve(cwd, LANGUAGE_REFERENCE), "utf8");
  writeFileSync(resolve(cwd, OUTPUT), renderIbmWords(text), "utf8");
  process.stdout.write(`wrote ${OUTPUT}\n`);
}
