/**
 * The reports, generated from result JSON and never maintained by hand.
 *
 *   pnpm horizontal:report
 *
 * Writes `docs/validation/horizontal-validation-results.md` and the OpenCBS
 * defect matrix from whatever the lanes last measured. Nothing here computes a
 * result; it renders `evidence/horizontal/*` and says so, which is the only way
 * a published number and a measured number stay the same number.
 *
 * A lane that has not run is reported as not run. That is deliberate and it is
 * the reason this tool is separate from the lanes: a report that silently
 * carried yesterday's figure for a corpus nobody measured today would be worse
 * than one with a gap in it.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import {
  CORPORA,
  DEFECT_DEMONSTRATIONS,
  DEFECT_FAMILIES,
  corpus,
  familyOf,
  formatRate,
  parseDefect,
  supportFor,
  type CorpusTally,
  type DefectCase,
  type DefectCoverage,
  type RunEnvironment,
} from "../packages/horizontal-validation/src/index";
import { corpusDir } from "./horizontal-fetch";

const EVIDENCE = "evidence/horizontal";

function readJson<T>(path: string): T | null {
  return existsSync(path)
    ? (JSON.parse(readFileSync(path, "utf8")) as T)
    : null;
}

/* ------------------------------------------------------------------ *
 * The OpenCBS defect matrix
 * ------------------------------------------------------------------ */

export interface DefectRow {
  defect: string;
  title: string;
  family: string;
  coverage: DefectCoverage;
  /** The diagnostic proving it, where a demonstration exists. */
  diagnostic: string | null;
}

/**
 * One row per upstream defect, with what this repository has shown about it.
 *
 * The only route to `prevented-at-compile-time` is a demonstration in
 * `packages/horizontal-validation/src/defect-demonstrations.ts`, which
 * `tests/horizontal-defects.test.ts` compiles on every run. Everything else is
 * `not-demonstrated`, however obvious the answer looks — a defect family whose
 * mechanism is named but never exercised is a claim, and this matrix does not
 * print claims.
 */
export function defectMatrix(cwd = process.cwd()): DefectRow[] {
  const programs = join(corpusDir("opencbs", cwd), "COBOL_Programs");
  if (!existsSync(programs)) {
    return [];
  }
  const demonstrated = new Map(
    DEFECT_DEMONSTRATIONS.map((entry) => [entry.defect, entry]),
  );

  const rows: DefectRow[] = [];
  const seen = new Set<string>();
  for (const file of readdirSync(programs).sort()) {
    const defect: DefectCase | null = parseDefect(
      file,
      readFileSync(join(programs, file)).toString("latin1"),
    );
    if (!defect || defect.title === "" || seen.has(defect.id)) {
      continue;
    }
    seen.add(defect.id);
    const shown = demonstrated.get(defect.id);
    const family = familyOf(defect);
    rows.push({
      defect: defect.id,
      title: defect.title,
      family: family?.family ?? "unclassified",
      coverage: shown?.coverage ?? "not-demonstrated",
      diagnostic: shown?.expectDiagnostic ?? null,
    });
  }
  return rows;
}

function renderDefectMatrix(rows: DefectRow[]): string {
  if (rows.length === 0) {
    return [
      "# OpenCBS defect coverage",
      "",
      "_The corpus is not in the local cache, so no matrix was produced._",
      "Run `pnpm horizontal:fetch opencbs` and then `pnpm horizontal:report`.",
      "",
    ].join("\n");
  }

  const count = (coverage: DefectCoverage): number =>
    rows.filter((row) => row.coverage === coverage).length;

  const definition = corpus("opencbs");
  return `${[
    "# OpenCBS defect coverage",
    "",
    "<!-- Generated by `pnpm horizontal:report`. Do not edit. -->",
    "",
    `**Upstream** ${definition.upstream}`,
    "",
    `**Citation** ${definition.citation}`,
    "",
    "Defects real COBOL developers reported on public forums, reconstructed as",
    "programs. Each carries the defective code as comments and the corrected code",
    "live, so both halves are recoverable.",
    "",
    "## What this repository has shown",
    "",
    "`prevented-at-compile-time` requires a BankTS program that the compiler",
    "refuses, named in `packages/horizontal-validation/src/defect-demonstrations.ts`",
    "and compiled by `tests/horizontal-defects.test.ts` on every run. Nothing else",
    "may claim it. `not-demonstrated` means exactly that — not that BankLang",
    "would fail to catch the defect, but that this repository has not shown it.",
    "",
    "| Coverage | Defects |",
    "| --- | --- |",
    `| prevented at compile time | ${formatRate(count("prevented-at-compile-time"), rows.length)} |`,
    `| not expressible in BankTS at all | ${formatRate(count("not-expressible-in-bankts"), rows.length)} |`,
    `| outside BankLang's model | ${formatRate(count("outside-banklang-model"), rows.length)} |`,
    `| not demonstrated | ${formatRate(count("not-demonstrated"), rows.length)} |`,
    "",
    "## Every defect",
    "",
    "| Defect | Family | What went wrong | Coverage | Diagnostic |",
    "| --- | --- | --- | --- | --- |",
    ...rows.map(
      (row) =>
        `| ${row.defect} | ${row.family} | ${row.title.toLowerCase()} | ${row.coverage} | ${row.diagnostic ? `\`${row.diagnostic}\`` : "—"} |`,
    ),
    "",
    "## Families, and what BankLang says about each",
    "",
    ...DEFECT_FAMILIES.flatMap((family) => [
      `### ${family.family}`,
      "",
      family.mechanism
        ? `**Mechanism** ${family.mechanism}`
        : "**Mechanism** none — see below.",
      "",
      family.banklangPosition,
      "",
    ]),
  ].join("\n")}\n`;
}

/* ------------------------------------------------------------------ *
 * The overall results page
 * ------------------------------------------------------------------ */

interface CoverageSummary {
  corpus: string;
  discovered: number;
  analysed: number;
  analyserFailures: number;
  representability: Record<string, number>;
}

function renderResults(cwd: string): string {
  const environment = readJson<RunEnvironment>(
    resolve(cwd, EVIDENCE, "xcobol-v2", "environment.json"),
  );

  const lines: string[] = [
    "# Horizontal validation — results",
    "",
    "<!-- Generated by `pnpm horizontal:report`. Do not edit. -->",
    "",
    "What happens when this compiler is confronted with COBOL, specifications and",
    "defects that were not written for it. The method is in",
    "[horizontal-validation.md](horizontal-validation.md); this page is the",
    "measurement, and every number on it is read out of `evidence/horizontal/`.",
    "",
    "## The compiler these numbers came from",
    "",
  ];

  if (environment) {
    lines.push(
      "| | |",
      "| --- | --- |",
      `| BankLang | ${environment.banklangVersion} |`,
      `| commit | \`${environment.gitCommit.slice(0, 12)}\` |`,
      `| Node | ${environment.nodeVersion} |`,
      `| COBOL compiler | ${environment.gnucobolVersion ?? "not available — nothing was executed"} |`,
      `| platform | ${environment.platform}/${environment.arch} |`,
      `| corpus lock | \`${environment.corpusLockHash.slice(0, 12)}\` |`,
      "",
    );
  } else {
    lines.push("_No lane has been run on this checkout._", "");
  }

  lines.push(
    "**Target: IBM Enterprise COBOL 6.4. Runtime validation: GnuCOBOL. Native IBM",
    "Enterprise COBOL execution: not yet performed.** Nothing on this page was",
    "produced by an IBM compiler, and no result here establishes behaviour under",
    "one.",
    "",
    "## Corpora",
    "",
    "| Corpus | Version | Licence | Redistribution |",
    "| --- | --- | --- | --- |",
    ...CORPORA.map(
      (entry) =>
        `| ${entry.name} | ${describeRevision(entry.id)} | ${entry.licence} | ${entry.redistribution} |`,
    ),
    "",
  );

  // ---- semantic ------------------------------------------------------
  lines.push("## Independent semantic benchmarks", "");
  let anySemantic = false;
  for (const id of ["cobolcodebench", "coboleval"]) {
    const summary = readJson<CorpusTally>(
      resolve(cwd, EVIDENCE, id, "summary.json"),
    );
    if (!summary) {
      continue;
    }
    anySemantic = true;
    const definition = corpus(id);
    lines.push(
      `### ${definition.name}`,
      "",
      `${definition.establishes}`,
      "",
      "| | |",
      "| --- | --- |",
      `| tasks discovered | ${String(summary.discovered)} |`,
      `| imported into the harness | ${String(summary.imported)} |`,
      `| applicable — BankTS can express it *and* an implementation exists | ${String(summary.applicable)} |`,
      `| expressible, not yet written | ${String(summary.notYetAuthored)} |`,
      `| unsupported by design | ${String(summary.unsupportedByDesign)} |`,
      `| unsupported, not yet implemented | ${String(summary.unsupportedNotYetImplemented)} |`,
      `| **passed, of applicable** | **${summary.passOfApplicable}** |`,
      `| **passed, of all discovered** | **${summary.passOfDiscovered}** |`,
      "",
    );
    if (Object.keys(summary.failures).length > 0) {
      lines.push(
        "| Failure | Tasks |",
        "| --- | --- |",
        ...Object.entries(summary.failures)
          .sort((a, b) => b[1] - a[1])
          .map(([outcome, count]) => `| ${outcome} | ${String(count)} |`),
        "",
      );
    }
  }
  if (!anySemantic) {
    lines.push("_Not run on this checkout._", "");
  }

  // ---- coverage ------------------------------------------------------
  lines.push("## Real-world coverage", "");
  let anyCoverage = false;
  for (const id of ["xcobol-v2", "opencbs"]) {
    const summary = readJson<CoverageSummary>(
      resolve(cwd, EVIDENCE, id, "summary.json"),
    );
    if (!summary) {
      continue;
    }
    anyCoverage = true;
    const definition = corpus(id);
    lines.push(
      `### ${definition.name}`,
      "",
      definition.limits,
      "",
      "| | |",
      "| --- | --- |",
      `| COBOL files discovered | ${String(summary.discovered)} |`,
      `| read without error | ${formatRate(summary.analysed, summary.discovered)} |`,
      `| analyser failures | ${String(summary.analyserFailures)} |`,
      "",
      "| Representability | Files |",
      "| --- | --- |",
      ...Object.entries(summary.representability).map(
        ([verdict, count]) =>
          `| ${verdict} | ${formatRate(count, summary.discovered)} |`,
      ),
      "",
    );

    const gaps = readJson<
      { feature: string; support: string; files: number; share: string }[]
    >(resolve(cwd, EVIDENCE, id, "gaps.json"));
    if (gaps && gaps.length > 0) {
      lines.push(
        "Constructs BankTS cannot express, ranked by how often they occur:",
        "",
        "| Construct | Support | Files | Share |",
        "| --- | --- | --- | --- |",
        ...gaps
          .slice(0, 15)
          .map(
            (gap) =>
              `| \`${gap.feature}\` | ${gap.support} | ${String(gap.files)} | ${gap.share} |`,
          ),
        "",
        `The rules behind each verdict are in \`packages/horizontal-validation/src/representability.ts\`, one row per construct. ${supportFor("inspect")?.note ?? ""}`,
        "",
      );
    }
  }
  if (!anyCoverage) {
    lines.push("_Not run on this checkout._", "");
  }

  // ---- defects and conformance ---------------------------------------
  const matrix = defectMatrix(cwd);
  lines.push(
    "## Defect benchmark",
    "",
    matrix.length === 0
      ? "_Not run on this checkout._"
      : `${String(matrix.length)} reconstructed defects. ${String(matrix.filter((row) => row.coverage === "prevented-at-compile-time").length)} are prevented at compile time by a BankTS program the compiler refuses; see [the matrix](horizontal-defect-coverage.md).`,
    "",
    "## COBOL conformance",
    "",
  );
  const ccvs = readJson<{
    available: boolean;
    location: string;
    discovered: number;
    applicable: number;
  }>(resolve(cwd, EVIDENCE, "ccvs85-local", "summary.json"));
  lines.push(
    ccvs?.available
      ? `NIST COBOL-85, supplied locally: ${String(ccvs.discovered)} sources discovered, ${String(ccvs.applicable)} in modules this backend emits.`
      : "NIST COBOL-85 is never downloaded or redistributed by this repository. No local copy was supplied, so this lane is **unavailable** — which is not the same as passing.",
    "",
  );

  return `${lines.join("\n")}\n`;
}

function describeRevision(id: string): string {
  const entry = corpus(id).fetch;
  switch (entry.kind) {
    case "github":
      return `\`${entry.ref.slice(0, 12)}\``;
    case "huggingface":
      return `\`${entry.revision.slice(0, 12)}\``;
    case "zenodo":
      return `DOI 10.5281/zenodo.${entry.record}`;
    case "local":
      return "operator-supplied";
  }
}

function main(): number {
  const cwd = process.cwd();
  const docs = resolve(cwd, "docs", "validation");
  mkdirSync(docs, { recursive: true });

  const results = join(docs, "horizontal-validation-results.md");
  writeFileSync(results, renderResults(cwd), "utf8");

  const matrix = join(docs, "horizontal-defect-coverage.md");
  writeFileSync(matrix, renderDefectMatrix(defectMatrix(cwd)), "utf8");

  process.stdout.write(`Wrote ${results}\nWrote ${matrix}\n`);
  return 0;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  process.exitCode = main();
}
