import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { runBankc } from "../packages/bankc-cli/src/index";

/**
 * Regenerates every conversion's `generated/` directory and its measurements.
 *
 * A conversion is the argument the external audit said would change how this
 * project is received: existing COBOL on one side, the BankTS it becomes on the
 * other, and what the compiler produces from that BankTS underneath. The
 * regenerated COBOL is checked in because a reader has to be able to see it
 * without a toolchain, and it is generated by this tool rather than pasted,
 * because a checked-in artifact that drifted from the compiler is worse than no
 * artifact at all. `pnpm conversions:check` fails when it has.
 *
 * The measurements are the part that has to be honest. A conversion that only
 * reported "180 lines became 240" invites the reading that the output is
 * bloated; one that reported only "no GO TOs" invites the reading that this is
 * a style argument. Both numbers are printed, with what the extra lines are.
 */
export interface ConversionMeasurement {
  /** Directory name, e.g. `01-sequential-update`. */
  name: string;
  originalLines: number;
  bankTsLines: number;
  generatedLines: number;
  /**
   * `GO TO`s that leave the paragraph they are in for somewhere that is not
   * its own exit.
   *
   * Counted this way because a raw total would be dishonest in both
   * directions. `GO TO <routine>-EXIT` is the single-exit convention IBM's own
   * Programming Guide writes, and a generated program is full of them: one per
   * failure path. A `GO TO` to *another* paragraph is the thing that makes
   * control flow something a reader has to trace, and it is what the originals
   * here use to reach their reject handling from the middle of a paragraph.
   */
  originalJumps: number;
  generatedJumps: number;
  /** Every `GO TO`, including the exits, so the other number can be checked. */
  originalGoTos: number;
  generatedGoTos: number;
  /** I/O statements, and how many of them are followed by a status test. */
  originalIoStatements: number;
  originalIoChecked: number;
  generatedIoStatements: number;
  generatedIoChecked: number;
}

const ROOT = "conversions";

export function conversionDirectories(cwd = process.cwd()): string[] {
  const root = resolve(cwd, ROOT);
  if (!existsSync(root)) {
    return [];
  }
  return readdirSync(root, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isDirectory() &&
        existsSync(join(root, entry.name, "banklang", "src", "main.bank.ts")),
    )
    .map((entry) => entry.name)
    .sort();
}

export function refreshConversions(
  cwd = process.cwd(),
): ConversionMeasurement[] {
  return conversionDirectories(cwd).map((name) => refreshOne(name, cwd));
}

function refreshOne(name: string, cwd: string): ConversionMeasurement {
  const directory = join(ROOT, name);
  const generated = join(directory, "generated");

  // Removed rather than written over: a record renamed in the BankTS leaves a
  // copybook behind under its old name, and a stale member in a library is the
  // defect this whole project is about.
  rmSync(resolve(cwd, generated), { recursive: true, force: true });
  mkdirSync(resolve(cwd, generated), { recursive: true });

  const built = runBankc(
    ["build", join(directory, "banklang"), "--out", generated],
    cwd,
  );
  if (built.exitCode !== 0) {
    throw new Error(`${directory}: ${built.stderr}`);
  }

  // The audit bundle is a per-run report rather than part of the argument, and
  // checking one in per conversion is four hundred lines nobody reads.
  rmSync(resolve(cwd, generated, "audit"), { recursive: true, force: true });

  const measurement = measure(name, cwd);
  writeMeasurements(name, measurement, cwd);
  return measurement;
}

/** The markers a conversion page puts around its measurement table. */
const OPEN_MARKER = "<!-- measurements -->";
const CLOSE_MARKER = "<!-- /measurements -->";

/**
 * Writes the measurement table into the conversion's page.
 *
 * Between two markers rather than at the end, so the numbers sit where the
 * argument needs them and a reader never meets a hand-typed count that stopped
 * being true. A page with no markers gets nothing and is not an error: not
 * every conversion's point is a number.
 */
function writeMeasurements(
  name: string,
  measurement: ConversionMeasurement,
  cwd: string,
): void {
  const path = resolve(cwd, ROOT, name, "README.md");
  if (!existsSync(path)) {
    return;
  }
  const page = readFileSync(path, "utf8");
  const open = page.indexOf(OPEN_MARKER);
  const close = page.indexOf(CLOSE_MARKER);
  if (open === -1 || close === -1 || close < open) {
    return;
  }

  writeFileSync(
    path,
    [
      page.slice(0, open + OPEN_MARKER.length),
      "",
      measurementTable(measurement),
      "",
      page.slice(close),
    ].join("\n"),
    "utf8",
  );
}

export function measure(
  name: string,
  cwd = process.cwd(),
): ConversionMeasurement {
  const directory = resolve(cwd, ROOT, name);
  const original = `${readAll(join(directory, "original"), ".cbl")}\n${readAll(join(directory, "original"), ".cpy")}`;
  const bankTs = readFileSync(
    join(directory, "banklang", "src", "main.bank.ts"),
    "utf8",
  );
  const generated = readAll(join(directory, "generated", "cobol"), ".cbl");

  const originalIo = ioStatements(original);
  const generatedIo = ioStatements(generated);

  return {
    name,
    originalLines: countLines(original),
    bankTsLines: countLines(bankTs),
    generatedLines: countLines(generated),
    originalJumps: jumps(original),
    generatedJumps: jumps(generated),
    originalGoTos: (original.match(/\bGO\s+TO\b/g) ?? []).length,
    generatedGoTos: (generated.match(/\bGO\s+TO\b/g) ?? []).length,
    originalIoStatements: originalIo.total,
    originalIoChecked: originalIo.checked,
    generatedIoStatements: generatedIo.total,
    generatedIoChecked: generatedIo.checked,
  };
}

function readAll(directory: string, extension: string): string {
  if (!existsSync(directory)) {
    return "";
  }
  return readdirSync(directory)
    .filter((entry) => entry.endsWith(extension))
    .sort()
    .map((entry) => readFileSync(join(directory, entry), "utf8"))
    .join("\n");
}

/**
 * `GO TO`s to somewhere other than a paragraph named `...-EXIT`.
 *
 * The single-exit convention needs one `GO TO` per failure path and IBM's own
 * Programming Guide writes them, so counting those against a generated program
 * measures the convention rather than the program. What is worth counting is a
 * jump to a paragraph that is not an exit: that is control flow a reader has to
 * follow rather than a return.
 */
function jumps(text: string): number {
  return (text.match(/\bGO\s+TO\s+([A-Z0-9-]+)/g) ?? []).filter(
    (statement) => !/-EXIT$/.test(statement),
  ).length;
}

/** Lines that are neither blank nor a comment. */
function countLines(text: string): number {
  return text
    .split("\n")
    .filter(
      (line) =>
        line.trim().length > 0 &&
        line[6] !== "*" &&
        !line.trimStart().startsWith("*") &&
        !line.trimStart().startsWith("//"),
    ).length;
}

/**
 * How many file operations there are, and how many of them are followed by
 * something that looks at the result.
 *
 * The measurement that matters. An `OPEN` whose status nothing reads is a step
 * that reports success over a dataset that was never allocated, and it is the
 * single most common thing in the originals here: four `OPEN`s in one
 * statement and no `FILE STATUS` field declared at all.
 *
 * Approximate on purpose: it counts a status test in the five lines after the
 * statement, which is where one is if there is one. It is a measurement of the
 * conversions in this directory, not a general-purpose analyser.
 */
function ioStatements(text: string): { total: number; checked: number } {
  const lines = text.split("\n");
  let total = 0;
  let checked = 0;
  let inExec = false;

  lines.forEach((line, index) => {
    const content = line.slice(6);
    // `EXEC SQL OPEN <cursor>` is not a file operation and its result is
    // reported in SQLCODE rather than in a file status. Counting it here would
    // put every Db2 program in the wrong column of the table.
    if (/\bEXEC\s+(SQL|CICS|DLI)\b/.test(content)) {
      inExec = true;
    }
    if (inExec) {
      if (/\bEND-EXEC\b/.test(content)) {
        inExec = false;
      }
      return;
    }
    // A space after the verb, not a word boundary: `READ-CUSTOMERS.` is a
    // paragraph and `READ-TOTALS` is a field, and both start with `READ`
    // followed by something a `\b` is happy with.
    if (!/^\s*(OPEN|CLOSE|READ|WRITE|REWRITE|DELETE|START)\s/.test(content)) {
      return;
    }
    total += 1;
    const window = lines.slice(index, index + 6).join("\n");
    // `-STATUS` and `-STATUS-OK`: the second is the 88-level condition name,
    // which is how a generated program tests one.
    if (
      /-STATUS(-[A-Z]+)?\b/.test(window) ||
      /\bAT\s+END\b/.test(window) ||
      /\bINVALID\s+KEY\b/.test(window)
    ) {
      checked += 1;
    }
  });

  return { total, checked };
}

/** The measurement table each conversion's page prints. */
export function measurementTable(measurement: ConversionMeasurement): string {
  const rows = [
    [
      "Lines of code, comments and blanks excluded",
      `${measurement.originalLines}`,
      `${measurement.generatedLines}`,
    ],
    [
      "`GO TO` a paragraph that is not an exit",
      `${measurement.originalJumps}`,
      `${measurement.generatedJumps}`,
    ],
    [
      "`GO TO` in total, single-exit returns included",
      `${measurement.originalGoTos}`,
      `${measurement.generatedGoTos}`,
    ],
    [
      "File operations whose result is tested",
      `${measurement.originalIoChecked} of ${measurement.originalIoStatements}`,
      `${measurement.generatedIoChecked} of ${measurement.generatedIoStatements}`,
    ],
  ];

  return [
    "| | Original | Regenerated |",
    "| --- | --- | --- |",
    ...rows.map((row) => `| ${row.join(" | ")} |`),
    "",
    `The BankTS in between is ${measurement.bankTsLines} lines.`,
  ].join("\n");
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  for (const measurement of refreshConversions()) {
    process.stdout.write(`${measurement.name}\n`);
    process.stdout.write(`${measurementTable(measurement)}\n\n`);
  }
}
