CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> STATEMEN — StatementGeneration
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   GENERATE-STATEMENT, the transaction this program is entered
      *>     at.
      *>
      *> ENTRY
      *>   A batch program with no parameters, started by EXEC PGM in a
      *>     job.
      *>
      *> FILES
      *>   ACCOUNTM input   indexed    ACCOUNT-MASTER (33 bytes)
      *>   STATEMEN output  sequential STATEMENT (5761 bytes)
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>     which.
      *>   16  A sort or merge did not complete. SORT-RETURN says so.
      *>
      *> RESTART
      *>   Not restartable. Rerun from the top: the generated job
      *>     deletes a half-written output dataset rather than
      *>     cataloguing it, so there is nothing for a second run to
      *>     read as though it were complete.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. STATEMEN.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT ACCOUNT-MASTER-FILE ASSIGN TO ACCOUNTM
               ORGANIZATION IS INDEXED
               ACCESS MODE IS DYNAMIC
               RECORD KEY IS ACCOUNT-ID OF ACCOUNT-MASTER-RECORD
               FILE STATUS IS ACCOUNT-MASTER-STATUS.
           SELECT STATEMENT-OUTPUT-FILE ASSIGN TO STATEMEN
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS STATEMENT-OUTPUT-STATUS.

       DATA DIVISION.
       FILE SECTION.
       FD  ACCOUNT-MASTER-FILE.
       01  ACCOUNT-MASTER-RECORD.
           05  ACCOUNT-ID           PIC X(16).
           05  STATUS-FLD           PIC X(7).
               88  STATUS-FLD-ACTIVE            VALUE "ACTIVE".
               88  STATUS-FLD-DORMANT           VALUE "DORMANT".
               88  STATUS-FLD-FROZEN            VALUE "FROZEN".
               88  STATUS-FLD-CLOSED            VALUE "CLOSED".
           05  BALANCE              PIC S9(16)V99 COMP-3.
       FD  STATEMENT-OUTPUT-FILE
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.
       01  STATEMENT-OUTPUT-RECORD.
           05  ACCOUNT-ID           PIC X(16).
           05  HOLDER-NAME          PIC X(40).
           05  NATIONAL-ID          PIC X(20).
           05  STATUS-FLD           PIC X(7).
               88  STATUS-FLD-ACTIVE            VALUE "ACTIVE".
               88  STATUS-FLD-DORMANT           VALUE "DORMANT".
               88  STATUS-FLD-FROZEN            VALUE "FROZEN".
               88  STATUS-FLD-CLOSED            VALUE "CLOSED".
           05  OPENING-BALANCE      PIC S9(16)V99 COMP-3.
           05  CLOSING-BALANCE      PIC S9(16)V99 COMP-3.
           05  LINES-FLD OCCURS 100 TIMES
                   INDEXED BY STAT-OUTP-RECORD-LINES-FLD-IDX.
               10  ENTRY-KIND           PIC X(6).
                   88  ENTRY-KIND-DEBIT             VALUE "DEBIT".
                   88  ENTRY-KIND-CREDIT            VALUE "CREDIT".
               10  NARRATIVE            PIC X(40).
               10  AMOUNT               PIC S9(16)V99 COMP-3.
           05  RELATIONSHIP-MANAGER PIC X(20).
           05  RELATIONSHIP-MANAGER-IND PIC S9(4) COMP.
           05  IDEMPOTENCY-KEY      PIC X(36).
       WORKING-STORAGE SECTION.
       01  ACCOUNT-MASTER-STATUS PIC X(2).
           88  ACCOUNT-MASTER-STATUS-OK VALUE "00" THRU "09".
           88  ACCOUNT-MASTER-STATUS-EOF VALUE "10".
           88  ACCOUNT-MASTER-STATUS-DUPKEY VALUE "22".
           88  ACCOUNT-MASTER-STATUS-NOTFND VALUE "23".
       01  STATEMENT-OUTPUT-STATUS PIC X(2).
           88  STATEMENT-OUTPUT-STATUS-OK VALUE "00" THRU "09".
           88  STATEMENT-OUTPUT-STATUS-EOF VALUE "10".
           88  STATEMENT-OUTPUT-STATUS-DUPKEY VALUE "22".
           88  STATEMENT-OUTPUT-STATUS-NOTFND VALUE "23".
       01  BANK-BOUNDS-STATUS   PIC X(2) VALUE "00".
       01  BANK-COPY-INDEX      PIC 9(9) COMP.
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       01  LEDGER-ENTRY.
           05  ENTRY-KIND           PIC X(6).
               88  ENTRY-KIND-DEBIT             VALUE "DEBIT".
               88  ENTRY-KIND-CREDIT            VALUE "CREDIT".
           05  NARRATIVE            PIC X(40).
           05  AMOUNT               PIC S9(16)V99 COMP-3.
       01  STATEMENT.
           05  ACCOUNT-ID           PIC X(16).
           05  HOLDER-NAME          PIC X(40).
           05  NATIONAL-ID          PIC X(20).
           05  STATUS-FLD           PIC X(7).
               88  STATUS-FLD-ACTIVE            VALUE "ACTIVE".
               88  STATUS-FLD-DORMANT           VALUE "DORMANT".
               88  STATUS-FLD-FROZEN            VALUE "FROZEN".
               88  STATUS-FLD-CLOSED            VALUE "CLOSED".
           05  OPENING-BALANCE      PIC S9(16)V99 COMP-3.
           05  CLOSING-BALANCE      PIC S9(16)V99 COMP-3.
           05  LINES-FLD OCCURS 100 TIMES
                   INDEXED BY STATEMENT-LINES-FLD-IDX.
               10  ENTRY-KIND           PIC X(6).
                   88  ENTRY-KIND-DEBIT             VALUE "DEBIT".
                   88  ENTRY-KIND-CREDIT            VALUE "CREDIT".
               10  NARRATIVE            PIC X(40).
               10  AMOUNT               PIC S9(16)V99 COMP-3.
           05  RELATIONSHIP-MANAGER PIC X(20).
           05  RELATIONSHIP-MANAGER-IND PIC S9(4) COMP.
           05  IDEMPOTENCY-KEY      PIC X(36).
       01  ACCOUNT-MASTER.
           05  ACCOUNT-ID           PIC X(16).
           05  STATUS-FLD           PIC X(7).
               88  STATUS-FLD-ACTIVE            VALUE "ACTIVE".
               88  STATUS-FLD-DORMANT           VALUE "DORMANT".
               88  STATUS-FLD-FROZEN            VALUE "FROZEN".
               88  STATUS-FLD-CLOSED            VALUE "CLOSED".
           05  BALANCE              PIC S9(16)V99 COMP-3.
       01  IS-STATEMENTABLE-RESULT PIC X(1) VALUE "N".
       01  IS-STATEMENTABLE-P1  PIC X(7).
       01  SUPPRESSION-REASON-RESULT PIC X(16).
       01  SUPPRESSION-REASON-P1 PIC X(7).
       01  LINE-INDEX           PIC S9(4) COMP-3.
       01  RUNNING              PIC S9(16)V99 COMP-3.
       01  MANAGER              PIC X(20).
       01  GENERATE-STATEMENT-LOOP-1 PIC 9(9) COMP.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION    PIC X(6).
           05  BANK-LEDGER-ACCOUNT      PIC X(32).
           05  BANK-LEDGER-AMOUNT       PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT         PIC X(32).
           05  BANK-AUDIT-CORRELATION   PIC X(64).

       PROCEDURE DIVISION.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM GENERATE-STATEMENT THRU GENERATE-STATEMENT-EXIT
           MOVE BANK-RETURN-CODE TO RETURN-CODE
           GOBACK.
       IS-STATEMENTABLE.
           IF (IS-STATEMENTABLE-P1 = "ACTIVE") OR (IS-STATEMENTABLE-P1 =
               "DORMANT")
               MOVE "Y" TO IS-STATEMENTABLE-RESULT
           ELSE
               MOVE "N" TO IS-STATEMENTABLE-RESULT
           END-IF
           CONTINUE.
       IS-STATEMENTABLE-EXIT.
           EXIT.
       SUPPRESSION-REASON.
           IF SUPPRESSION-REASON-P1 = "FROZEN"
               MOVE "FROZEN" TO SUPPRESSION-REASON-RESULT
           ELSE
               IF SUPPRESSION-REASON-P1 = "CLOSED"
                   MOVE "CLOSED" TO SUPPRESSION-REASON-RESULT
               ELSE
                   MOVE "NONE" TO SUPPRESSION-REASON-RESULT
               END-IF
           END-IF
           CONTINUE.
       SUPPRESSION-REASON-EXIT.
           EXIT.
       GENERATE-STATEMENT.
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM GENERATE-STATEMENT-BODY THRU
               GENERATE-STATEMENT-BODY-EXIT
           IF BANK-FAILURE-CODE NOT = SPACES
               PERFORM GENERATE-STATEMENT-FAILURE THRU
                   GENERATE-STAT-FAILURE-EXIT
           END-IF
           CONTINUE.
       GENERATE-STATEMENT-EXIT.
           EXIT.
       GENERATE-STATEMENT-BODY.
           MOVE 1 TO LINE-INDEX
           MOVE OPENING-BALANCE OF STATEMENT TO RUNNING
           MOVE "UNASSIGNED" TO MANAGER
           OPEN INPUT ACCOUNT-MASTER-FILE
           IF NOT ACCOUNT-MASTER-STATUS-OK
               DISPLAY "OPEN FAILED accountMaster STATUS "
                   ACCOUNT-MASTER-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "OPEN-FAILED" TO BANK-FAILURE-CODE
               GO TO GENERATE-STATEMENT-BODY-EXIT
           END-IF
           MOVE ACCOUNT-ID OF STATEMENT TO ACCOUNT-ID OF
               ACCOUNT-MASTER-RECORD
           READ ACCOUNT-MASTER-FILE
               INVALID KEY MOVE "23" TO ACCOUNT-MASTER-STATUS
               NOT INVALID KEY
                   MOVE ACCOUNT-ID OF ACCOUNT-MASTER-RECORD TO
                       ACCOUNT-ID OF ACCOUNT-MASTER
                   MOVE STATUS-FLD OF ACCOUNT-MASTER-RECORD TO
                       STATUS-FLD OF ACCOUNT-MASTER
                   MOVE BALANCE OF ACCOUNT-MASTER-RECORD TO BALANCE OF
                       ACCOUNT-MASTER
           END-READ
           IF NOT ACCOUNT-MASTER-STATUS-OK AND NOT
               ACCOUNT-MASTER-STATUS-NOTFND
               DISPLAY "READ FAILED accountMaster STATUS "
                   ACCOUNT-MASTER-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "READ-FAILED" TO BANK-FAILURE-CODE
               GO TO GENERATE-STATEMENT-BODY-EXIT
           END-IF
           IF RELATIONSHIP-MANAGER-IND OF STATEMENT = 0
               MOVE RELATIONSHIP-MANAGER OF STATEMENT TO MANAGER
           END-IF
           MOVE STATUS-FLD OF ACCOUNT-MASTER TO IS-STATEMENTABLE-P1
           PERFORM IS-STATEMENTABLE THRU IS-STATEMENTABLE-EXIT
           IF BANK-FAILURE-CODE NOT = SPACES
               GO TO GENERATE-STATEMENT-BODY-EXIT
           END-IF
           IF IS-STATEMENTABLE-RESULT = "Y"
               MOVE 0 TO GENERATE-STATEMENT-LOOP-1
               PERFORM UNTIL GENERATE-STATEMENT-LOOP-1 >= 100 OR NOT
                   (LINE-INDEX <= 100)
                   ADD 1 TO GENERATE-STATEMENT-LOOP-1
                   IF LINE-INDEX < 1 OR LINE-INDEX > 100
                       MOVE "23" TO BANK-BOUNDS-STATUS
                       DISPLAY "SUBSCRIPT OUT OF RANGE " LINE-INDEX UPON
                           SYSOUT
                       MOVE 12 TO BANK-RETURN-CODE
                       MOVE "BANK-BOUNDS-VIOLATION" TO BANK-FAILURE-CODE
                       GO TO GENERATE-STATEMENT-BODY-EXIT
                   END-IF
                   EVALUATE ENTRY-KIND OF STATEMENT (LINE-INDEX)
                       WHEN "DEBIT"
                           IF LINE-INDEX < 1 OR LINE-INDEX > 100
                               MOVE "23" TO BANK-BOUNDS-STATUS
                               DISPLAY "SUBSCRIPT OUT OF RANGE "
                                   LINE-INDEX UPON SYSOUT
                               MOVE 12 TO BANK-RETURN-CODE
                               MOVE "BANK-BOUNDS-VIOLATION" TO
                                   BANK-FAILURE-CODE
                               GO TO GENERATE-STATEMENT-BODY-EXIT
                           END-IF
                           COMPUTE RUNNING = (RUNNING - AMOUNT OF
                               STATEMENT (LINE-INDEX))
                               ON SIZE ERROR
                                   DISPLAY "ARITHMETIC OVERFLOW RUNNING"
                                       UPON SYSOUT
                                   MOVE 12 TO BANK-RETURN-CODE
                                   MOVE "ARITHMETIC-OVERFLOW" TO
                                       BANK-FAILURE-CODE
                                   GO TO GENERATE-STATEMENT-BODY-EXIT
                           END-COMPUTE
                       WHEN "CREDIT"
                           IF LINE-INDEX < 1 OR LINE-INDEX > 100
                               MOVE "23" TO BANK-BOUNDS-STATUS
                               DISPLAY "SUBSCRIPT OUT OF RANGE "
                                   LINE-INDEX UPON SYSOUT
                               MOVE 12 TO BANK-RETURN-CODE
                               MOVE "BANK-BOUNDS-VIOLATION" TO
                                   BANK-FAILURE-CODE
                               GO TO GENERATE-STATEMENT-BODY-EXIT
                           END-IF
                           COMPUTE RUNNING = (RUNNING + AMOUNT OF
                               STATEMENT (LINE-INDEX))
                               ON SIZE ERROR
                                   DISPLAY "ARITHMETIC OVERFLOW RUNNING"
                                       UPON SYSOUT
                                   MOVE 12 TO BANK-RETURN-CODE
                                   MOVE "ARITHMETIC-OVERFLOW" TO
                                       BANK-FAILURE-CODE
                                   GO TO GENERATE-STATEMENT-BODY-EXIT
                           END-COMPUTE
                   END-EVALUATE
                   COMPUTE LINE-INDEX = (LINE-INDEX + 1)
                       ON SIZE ERROR
                           DISPLAY "ARITHMETIC OVERFLOW LINE-INDEX" UPON
                               SYSOUT
                           MOVE 12 TO BANK-RETURN-CODE
                           MOVE "ARITHMETIC-OVERFLOW" TO
                               BANK-FAILURE-CODE
                           GO TO GENERATE-STATEMENT-BODY-EXIT
                   END-COMPUTE
               END-PERFORM
               IF GENERATE-STATEMENT-LOOP-1 >= 100 AND (LINE-INDEX <=
                   100)
                   DISPLAY "LOOP LIMIT 100 REACHED, WORK UNFINISHED"
                       UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "BANK-LOOP-EXHAUSTED" TO BANK-FAILURE-CODE
                   GO TO GENERATE-STATEMENT-BODY-EXIT
               END-IF
               MOVE RUNNING TO CLOSING-BALANCE OF STATEMENT
               MOVE ACCOUNT-ID OF STATEMENT TO ACCOUNT-ID OF
                   STATEMENT-OUTPUT-RECORD
               MOVE HOLDER-NAME OF STATEMENT TO HOLDER-NAME OF
                   STATEMENT-OUTPUT-RECORD
               MOVE NATIONAL-ID OF STATEMENT TO NATIONAL-ID OF
                   STATEMENT-OUTPUT-RECORD
               MOVE STATUS-FLD OF STATEMENT TO STATUS-FLD OF
                   STATEMENT-OUTPUT-RECORD
               MOVE OPENING-BALANCE OF STATEMENT TO OPENING-BALANCE OF
                   STATEMENT-OUTPUT-RECORD
               MOVE CLOSING-BALANCE OF STATEMENT TO CLOSING-BALANCE OF
                   STATEMENT-OUTPUT-RECORD
               PERFORM VARYING BANK-COPY-INDEX FROM 1 BY 1 UNTIL
                   BANK-COPY-INDEX > 100
                   MOVE LINES-FLD OF STATEMENT (BANK-COPY-INDEX) TO
                       LINES-FLD OF STATEMENT-OUTPUT-RECORD
                       (BANK-COPY-INDEX)
               END-PERFORM
               MOVE RELATIONSHIP-MANAGER OF STATEMENT TO
                   RELATIONSHIP-MANAGER OF STATEMENT-OUTPUT-RECORD
               MOVE IDEMPOTENCY-KEY OF STATEMENT TO IDEMPOTENCY-KEY OF
                   STATEMENT-OUTPUT-RECORD
               WRITE STATEMENT-OUTPUT-RECORD
               IF NOT STATEMENT-OUTPUT-STATUS-OK
                   DISPLAY "WRITE FAILED statementOutput STATUS "
                       STATEMENT-OUTPUT-STATUS UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "WRITE-FAILED" TO BANK-FAILURE-CODE
                   GO TO GENERATE-STATEMENT-BODY-EXIT
               END-IF
           END-IF
           CLOSE ACCOUNT-MASTER-FILE
           IF NOT ACCOUNT-MASTER-STATUS-OK
               DISPLAY "CLOSE FAILED accountMaster STATUS "
                   ACCOUNT-MASTER-STATUS UPON SYSOUT
               MOVE 12 TO BANK-RETURN-CODE
               MOVE "CLOSE-FAILED" TO BANK-FAILURE-CODE
               GO TO GENERATE-STATEMENT-BODY-EXIT
           END-IF
           MOVE "STATEMENT_GENERATED" TO BANK-AUDIT-EVENT
           MOVE IDEMPOTENCY-KEY OF STATEMENT TO BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       GENERATE-STATEMENT-BODY-EXIT.
           EXIT.
       GENERATE-STATEMENT-FAILURE.
           DISPLAY "TRANSACTION FAILED generateStatement "
               BANK-FAILURE-CODE UPON SYSOUT
           MOVE 12 TO BANK-RETURN-CODE
           CONTINUE.
       GENERATE-STAT-FAILURE-EXIT.
           EXIT.
