//* Generated by bankc.
//* Do not edit this file directly.
//ACCOUNTF JOB (BANKLANG),'ACCOUNT-FILE-BATCH',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/ACCOUNT-FILE-BATCH.cbl
//* COPYBOOK source: dist/copybooks/ACCOUNT-RECORD.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.ACCOUNTFILEBATCH
//SYSLIN   DD DSN=&&OBJ,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(CYL,(1,1))
//LKED     EXEC PGM=IEWL,COND=(4,LT)
//SYSPRINT DD SYSOUT=*
//SYSLIN   DD DSN=&&OBJ,DISP=(OLD,DELETE)
//SYSLMOD  DD DISP=SHR,DSN=BANKLANG.LOADLIB(ACCOUNTF)
//RUN      EXEC PGM=ACCOUNTF
//SYSOUT   DD SYSOUT=*
//ACCOUNTI DD DISP=SHR,DSN=BANKLANG.ACCOUNTI
//POSTINGO DD DSN=BANKLANG.POSTINGO,DISP=(NEW,CATLG),
//            UNIT=SYSDA,SPACE=(CYL,(1,1))
//* This job is a documentation-friendly skeleton. Dataset names, unit
//* and space parameters, and the load library name are
//* placeholders for an installation's own standards.
