//* Generated by bankc.
//* Do not edit this file directly.
//ACCOUNTF JOB (BANKLANG),'ACCOUNT-FILE-BATCH',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID
//* Batch job example for the generated COBOL artifact.
//* COBOL source: dist/cobol/ACCOUNT-FILE-BATCH.cbl
//* COPYBOOK source: dist/copybooks/ACCOUNT-RECORD.cpy
//COMPILE  EXEC PGM=IGYCRCTL
//SYSPRINT DD SYSOUT=*
//SYSIN    DD DISP=SHR,DSN=DIST.COBOL.ACCOUNTFILEBATCH
//* The compile step above is a documentation-friendly skeleton.
