import type { SourcePosition, SourceSpan } from "../../ast/src/index";
import type {
  IRBinaryComparisonExpression,
  IRBinaryArithmeticExpression,
  IRBlock,
  IRBooleanLiteralExpression,
  IRDecimalLiteralExpression,
  IRExpression,
  IRField,
  IRIfStatement,
  IRFunction,
  IRIdentifierExpression,
  IRLetStatement,
  IRProgram,
  IRRecord,
  IRType,
  IRStatement,
  IRLedgerStatement,
  IRAuditStatement,
  IRMemberAccessExpression,
} from "../../ir/src/index";
import {
  decimalPicture,
  packedDecimalByteLength,
  toCobolFieldName,
  toCobolName,
  toCobolParagraphName,
  toCobolPicture,
  toCobolProgramId,
} from "../../cobol-ir/src/index";
import {
  describeRecordLayout,
  type CopybookRecordLayout,
} from "../../copybook/src/index";

/**
 * BankLang ledger and audit calling convention. See ADR-0003. The field widths
 * are fixed so the generated group items stay layout-stable across programs.
 */
const LEDGER_PROGRAM = "BANKLEDG";
const AUDIT_PROGRAM = "BANKAUDT";
const LEDGER_INTERFACE_GROUP = "BANK-LEDGER-INTERFACE";
const AUDIT_INTERFACE_GROUP = "BANK-AUDIT-INTERFACE";
const LEDGER_OPERATION_FIELD = "BANK-LEDGER-OPERATION";
const LEDGER_ACCOUNT_FIELD = "BANK-LEDGER-ACCOUNT";
const LEDGER_AMOUNT_FIELD = "BANK-LEDGER-AMOUNT";
const AUDIT_EVENT_FIELD = "BANK-AUDIT-EVENT";
const AUDIT_CORRELATION_FIELD = "BANK-AUDIT-CORRELATION";
const LEDGER_ACCOUNT_LENGTH = 32;
const LEDGER_AMOUNT_PICTURE = "PIC S9(16)V99 COMP-3";
const AUDIT_EVENT_LENGTH = 32;
const AUDIT_CORRELATION_LENGTH = 64;

export interface SourceMapEntry {
  sourceFile: string;
  sourceStart: SourcePosition;
  sourceEnd: SourcePosition;
  artifact: string;
  targetStartLine: number;
  targetEndLine: number;
  category: "module" | "record" | "field" | "function" | "transaction";
  symbol: string;
}

export interface SourceMapDocument {
  version: number;
  backendProfile: string;
  sourceFile: string;
  artifact: string;
  entries: SourceMapEntry[];
}

export interface CobolEmitResult {
  cobol: string;
  sourceMap: SourceMapDocument;
  recordLayouts: CopybookRecordLayout[];
  cobolArtifactPath: string;
  sourceMapArtifactPath: string;
}

export interface CobolEmitOptions {
  cobolArtifactPath?: string;
  sourceMapArtifactPath?: string;
}

export interface JclEmitResult {
  jcl: string;
  jclArtifactPath: string;
}

export interface JclEmitOptions {
  jclArtifactPath?: string;
}

export function emitCobol(
  program: IRProgram,
  options: CobolEmitOptions = {},
): CobolEmitResult {
  const backendProfile = "ibm-enterprise-cobol-zos";
  const cobolArtifactPath =
    options.cobolArtifactPath ?? defaultCobolArtifactPath(program.moduleName);
  const sourceMapArtifactPath =
    options.sourceMapArtifactPath ?? "dist/maps/source-map.json";
  const lines: string[] = [];
  const entries: SourceMapEntry[] = [];

  const addLine = (line = "") => {
    lines.push(line);
  };

  const lineNumber = () => lines.length + 1;

  addLine("*> Generated by bankc.");
  addLine("*> Do not edit this file directly.");
  addLine("*> Source maps are available in dist/maps.");
  const moduleLine = lineNumber();
  addLine(`       IDENTIFICATION DIVISION.`);
  addLine(`       PROGRAM-ID. ${toCobolProgramId(program.moduleName)}.`);
  addLine("");
  addLine(`       DATA DIVISION.`);
  addLine(`       WORKING-STORAGE SECTION.`);

  const recordLayouts: CopybookRecordLayout[] = [];
  for (const record of program.records) {
    const recordStart = lineNumber();
    const layout = describeRecordLayout(record);
    recordLayouts.push(layout);
    addLine(`       01  ${layout.cobolName}.`);
    emitRecordFields(record.fields, 1, addLine);
    const recordEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: record.span.start,
      sourceEnd: record.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: recordStart,
      targetEndLine: recordEnd,
      category: "record",
      symbol: record.name,
    });

    const fieldEntries = layout.fields;
    for (let index = 0; index < fieldEntries.length; index += 1) {
      const field = record.fields[index];
      const fieldLayout = fieldEntries[index];
      entries.push({
        sourceFile: program.sourceFile,
        sourceStart: field.span.start,
        sourceEnd: field.span.end,
        artifact: cobolArtifactPath,
        targetStartLine: recordStart + 1 + index,
        targetEndLine: recordStart + 1 + index,
        category: "field",
        symbol: field.name,
      });
      void fieldLayout;
    }
  }

  for (const fn of program.functions) {
    addLine(
      `       01  ${functionResultName(fn.name)} ${formatCobolType(fn.returnType)}.`,
    );
    for (const local of collectFunctionLocals(fn.body)) {
      addLine(
        `       01  ${toCobolFieldName(local.name).padEnd(20)} ${formatCobolType(local.declaredType)}.`,
      );
    }
  }
  if (program.transactions.length > 0) {
    emitLedgerInterfaceStorage(addLine);
  }

  addLine("");
  addLine(`       PROCEDURE DIVISION.`);

  for (const fn of program.functions) {
    const functionStart = lineNumber();
    addLine(`       ${toCobolParagraphName(fn.name)}.`);
    emitFunctionBody(fn, addLine);
    const functionEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: fn.span.start,
      sourceEnd: fn.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: functionStart,
      targetEndLine: functionEnd,
      category: "function",
      symbol: fn.name,
    });
  }

  for (const transaction of program.transactions) {
    const transactionStart = lineNumber();
    addLine(`       ${toCobolParagraphName(transaction.name)}.`);
    emitTransactionBody(transaction.body, addLine, 11);
    addLine(`           GOBACK.`);
    const transactionEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: transaction.span.start,
      sourceEnd: transaction.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: transactionStart,
      targetEndLine: transactionEnd,
      category: "transaction",
      symbol: transaction.name,
    });
  }

  entries.unshift({
    sourceFile: program.sourceFile,
    sourceStart: program.moduleSpan.start,
    sourceEnd: program.moduleSpan.end,
    artifact: cobolArtifactPath,
    targetStartLine: moduleLine,
    targetEndLine: moduleLine + 1,
    category: "module",
    symbol: program.moduleName,
  });

  return {
    cobol: `${lines.join("\n")}\n`,
    sourceMap: {
      version: 1,
      backendProfile,
      sourceFile: program.sourceFile,
      artifact: sourceMapArtifactPath,
      entries,
    },
    recordLayouts,
    cobolArtifactPath,
    sourceMapArtifactPath,
  };
}

export function emitJcl(
  program: IRProgram,
  options: JclEmitOptions = {},
): JclEmitResult {
  const jclArtifactPath =
    options.jclArtifactPath ?? defaultJclArtifactPath(program.moduleName);
  const jobName = toJclJobName(program.moduleName);
  const cobolArtifactPath = defaultCobolArtifactPath(program.moduleName);
  const copybookArtifactPaths = program.records.map(
    (record) => `dist/copybooks/${toCobolName(record.name)}.cpy`,
  );

  const lines = [
    "//* Generated by bankc.",
    "//* Do not edit this file directly.",
    `//${jobName} JOB (BANKLANG),'${toCobolName(program.moduleName)}',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID`,
    "//* Batch job example for the generated COBOL artifact.",
    `//* COBOL source: ${cobolArtifactPath}`,
    ...copybookArtifactPaths.map(
      (copybookPath) => `//* COPYBOOK source: ${copybookPath}`,
    ),
    `//COMPILE  EXEC PGM=IGYCRCTL`,
    `//SYSPRINT DD SYSOUT=*`,
    `//SYSIN    DD DISP=SHR,DSN=${toJclDatasetName(cobolArtifactPath)}`,
    `//* The compile step above is a documentation-friendly skeleton.`,
  ];

  return {
    jcl: `${lines.join("\n")}\n`,
    jclArtifactPath,
  };
}

function emitLedgerInterfaceStorage(addLine: (line?: string) => void): void {
  addLine(`       01  ${LEDGER_INTERFACE_GROUP}.`);
  addLine(`           05  ${LEDGER_OPERATION_FIELD.padEnd(24)} PIC X(6).`);
  addLine(
    `           05  ${LEDGER_ACCOUNT_FIELD.padEnd(24)} PIC X(${LEDGER_ACCOUNT_LENGTH}).`,
  );
  addLine(
    `           05  ${LEDGER_AMOUNT_FIELD.padEnd(24)} ${LEDGER_AMOUNT_PICTURE}.`,
  );
  addLine(`       01  ${AUDIT_INTERFACE_GROUP}.`);
  addLine(
    `           05  ${AUDIT_EVENT_FIELD.padEnd(24)} PIC X(${AUDIT_EVENT_LENGTH}).`,
  );
  addLine(
    `           05  ${AUDIT_CORRELATION_FIELD.padEnd(24)} PIC X(${AUDIT_CORRELATION_LENGTH}).`,
  );
}

function emitRecordFields(
  fields: IRRecord["fields"],
  level: number,
  addLine: (line?: string) => void,
): void {
  const indent = " ".repeat(7 + level * 4);
  for (const field of fields) {
    if (field.type.kind === "record") {
      addLine(`${indent}05  ${toCobolFieldName(field.name)}.`);
      emitRecordFields(field.type.fields, level + 1, addLine);
      continue;
    }

    addLine(
      `${indent}05  ${toCobolFieldName(field.name).padEnd(20)} ${formatCobolType(field.type)}.`,
    );
  }
}

function emitFunctionBody(
  fn: IRFunction,
  addLine: (line?: string) => void,
): void {
  emitStatement(fn.body, addLine, 11, functionResultName(fn.name));
}

function emitStatement(
  block: IRBlock,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  for (const statement of block.statements) {
    switch (statement.kind) {
      case "LetStatement":
        emitLetStatement(statement, addLine, indent);
        break;
      case "ReturnStatement":
        emitReturnStatement(statement, addLine, indent, resultName);
        break;
      case "IfStatement":
        emitIfStatement(statement, addLine, indentLevel, resultName);
        break;
      default:
        throw new Error(
          `Unsupported statement in function body: ${statement.kind}`,
        );
    }
  }
}

/**
 * Transaction bodies carry effects rather than a return value, so they emit
 * through their own path. The typechecker restricts them to let, debit, credit,
 * and audit statements.
 */
function emitTransactionBody(
  block: IRBlock,
  addLine: (line?: string) => void,
  indentLevel: number,
): void {
  const indent = " ".repeat(indentLevel);
  for (const statement of block.statements) {
    switch (statement.kind) {
      case "LetStatement":
        emitLetStatement(statement, addLine, indent);
        break;
      case "LedgerStatement":
        emitLedgerStatement(statement, addLine, indent);
        break;
      case "AuditStatement":
        emitAuditStatement(statement, addLine, indent);
        break;
      default:
        throw new Error(
          `Unsupported statement in transaction body: ${statement.kind}`,
        );
    }
  }
}

/**
 * Ledger postings are delegated to the BankLang ledger interface described in
 * ADR-0003. The generated COBOL fills a fixed group item and calls a named
 * program rather than inlining any posting logic.
 */
function emitLedgerStatement(
  statement: IRLedgerStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  addLine(
    `${indent}MOVE "${statement.operation.toUpperCase()}" TO ${LEDGER_OPERATION_FIELD}`,
  );
  addLine(
    `${indent}MOVE ${renderExpression(statement.account)} TO ${LEDGER_ACCOUNT_FIELD}`,
  );
  addLine(
    `${indent}MOVE ${renderDecimalExpression(statement.amount)} TO ${LEDGER_AMOUNT_FIELD}`,
  );
  addLine(`${indent}CALL "${LEDGER_PROGRAM}" USING ${LEDGER_INTERFACE_GROUP}`);
}

function emitAuditStatement(
  statement: IRAuditStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  addLine(
    `${indent}MOVE ${renderExpression(statement.eventName)} TO ${AUDIT_EVENT_FIELD}`,
  );
  addLine(
    `${indent}MOVE ${renderExpression(statement.correlation)} TO ${AUDIT_CORRELATION_FIELD}`,
  );
  addLine(`${indent}CALL "${AUDIT_PROGRAM}" USING ${AUDIT_INTERFACE_GROUP}`);
}

function emitLetStatement(
  statement: IRLetStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  if (statement.declaredType.kind === "bool") {
    emitBooleanAssignment(
      indent,
      toCobolFieldName(statement.name),
      statement.initializer,
      addLine,
    );
    return;
  }

  addLine(
    `${indent}COMPUTE ${toCobolFieldName(statement.name)} = ${renderDecimalExpression(statement.initializer)}`,
  );
}

function emitIfStatement(
  statement: IRIfStatement,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  addLine(`${indent}IF ${renderCondition(statement.condition)}`);
  emitStatement(statement.thenBranch, addLine, indentLevel + 4, resultName);
  if (statement.elseBranch) {
    addLine(`${indent}ELSE`);
    emitStatement(statement.elseBranch, addLine, indentLevel + 4, resultName);
  }
  addLine(`${indent}END-IF`);
}

function emitReturnStatement(
  statement: { expression: IRExpression },
  addLine: (line?: string) => void,
  indent: string,
  resultName: string,
): void {
  const expression = statement.expression;
  if (expression.resolvedType.kind === "bool") {
    emitBooleanAssignment(indent, resultName, expression, addLine);
    addLine(`${indent}GOBACK.`);
    return;
  }

  addLine(
    `${indent}COMPUTE ${resultName} = ${renderDecimalExpression(expression)}`,
  );
  addLine(`${indent}GOBACK.`);
}

function renderExpression(expression: IRExpression): string {
  switch (expression.kind) {
    case "Identifier":
      return toCobolFieldName(expression.name);
    case "DecimalLiteral":
      return expression.text;
    case "BooleanLiteral":
      return expression.value ? "TRUE" : "FALSE";
    case "StringLiteral":
      return `"${expression.value}"`;
    case "MemberAccess":
      return renderQualifiedFieldReference(expression);
    case "BinaryComparison":
      return `${renderExpression(expression.left)} ${expression.operator} ${renderExpression(expression.right)}`;
    case "BinaryArithmetic":
      return `${renderExpression(expression.left)} ${expression.operator} ${renderExpression(expression.right)}`;
  }
}

/**
 * COBOL qualifies a field with the group item that contains it, so
 * `request.amount` becomes `AMOUNT OF TRANSFER-REQUEST`.
 */
function renderQualifiedFieldReference(
  expression: IRMemberAccessExpression,
): string {
  return `${toCobolFieldName(expression.member)} OF ${toCobolName(expression.recordName)}`;
}

function renderDecimalExpression(expression: IRExpression): string {
  switch (expression.kind) {
    case "Identifier":
      return toCobolFieldName(expression.name);
    case "DecimalLiteral":
      return expression.text;
    case "MemberAccess":
      return renderQualifiedFieldReference(expression);
    case "BinaryArithmetic":
      return `${renderDecimalExpression(expression.left)} ${expression.operator} ${renderDecimalExpression(expression.right)}`;
    default:
      return renderExpression(expression);
  }
}

function renderCondition(expression: IRExpression): string {
  switch (expression.kind) {
    case "BooleanLiteral":
      return expression.value ? "1 = 1" : "1 = 0";
    case "Identifier":
      return expression.resolvedType.kind === "bool"
        ? `${toCobolFieldName(expression.name)} = 'Y'`
        : toCobolFieldName(expression.name);
    case "BinaryComparison":
      return `${renderDecimalExpression(expression.left)} ${expression.operator} ${renderDecimalExpression(expression.right)}`;
    default:
      return renderExpression(expression);
  }
}

function emitBooleanAssignment(
  indent: string,
  targetName: string,
  expression: IRExpression,
  addLine: (line?: string) => void,
): void {
  if (expression.kind === "BooleanLiteral") {
    addLine(`${indent}MOVE '${expression.value ? "Y" : "N"}' TO ${targetName}`);
    return;
  }

  addLine(`${indent}IF ${renderCondition(expression)}`);
  addLine(`${indent}    MOVE 'Y' TO ${targetName}`);
  addLine(`${indent}ELSE`);
  addLine(`${indent}    MOVE 'N' TO ${targetName}`);
  addLine(`${indent}END-IF`);
}

function collectFunctionLocals(block: IRBlock): IRLetStatement[] {
  const locals: IRLetStatement[] = [];
  const seen = new Set<string>();

  const visit = (current: IRBlock): void => {
    for (const statement of current.statements) {
      if (statement.kind === "LetStatement") {
        if (!seen.has(statement.name)) {
          seen.add(statement.name);
          locals.push(statement);
        }
        continue;
      }

      if (statement.kind === "IfStatement") {
        visit(statement.thenBranch);
        if (statement.elseBranch) {
          visit(statement.elseBranch);
        }
      }
    }
  };

  visit(block);
  return locals;
}

function functionResultName(functionName: string): string {
  return toCobolName(`${functionName}Result`);
}

function defaultCobolArtifactPath(moduleName: string): string {
  return `dist/cobol/${toCobolProgramId(moduleName)}.cbl`;
}

function defaultJclArtifactPath(moduleName: string): string {
  return `dist/jcl/${toCobolProgramId(moduleName)}.jcl`;
}

function toJclJobName(moduleName: string): string {
  return toCobolProgramId(moduleName).replace(/-/g, "").slice(0, 8);
}

function toJclDatasetName(cobolArtifactPath: string): string {
  return cobolArtifactPath
    .replace(/\.cbl$/i, "")
    .replace(/\//g, ".")
    .replace(/-/g, "")
    .toUpperCase();
}

function formatCobolType(type: IRType): string {
  switch (type.kind) {
    case "decimal":
      return decimalPicture(type.precision, type.scale);
    case "string":
      return `PIC X(${type.length})`;
    case "bool":
      return "PIC X VALUE 'N'";
    case "record":
      return toCobolName(type.name);
  }
}

export function renderCopybook(record: IRRecord): string {
  const layout = describeRecordLayout(record);
  const lines = [
    "*> Generated by bankc.",
    "*> Do not edit this file directly.",
    `01  ${layout.cobolName}.`,
    ...layout.fields.map(
      (field) => `    05  ${field.cobolName.padEnd(20)} ${field.picture}.`,
    ),
  ];

  return `${lines.join("\n")}\n`;
}

export function countPackedDecimalBytes(precision: number): number {
  return packedDecimalByteLength(precision);
}
