import type { SourcePosition, SourceSpan } from "../../ast/src/index";
import type {
  IRBinaryComparisonExpression,
  IRBlock,
  IRBooleanLiteralExpression,
  IRDecimalLiteralExpression,
  IRExpression,
  IRField,
  IRIfStatement,
  IRFunction,
  IRIdentifierExpression,
  IRProgram,
  IRRecord,
  IRType,
  IRStatement,
} from "../../ir/src/index";
import {
  decimalPicture,
  packedDecimalByteLength,
  toCobolFieldName,
  toCobolName,
  toCobolParagraphName,
  toCobolPicture,
  toCobolProgramId,
} from "../../cobol-ir/src/index";
import {
  describeRecordLayout,
  type CopybookRecordLayout,
} from "../../copybook/src/index";

export interface SourceMapEntry {
  sourceFile: string;
  sourceStart: SourcePosition;
  sourceEnd: SourcePosition;
  artifact: string;
  targetStartLine: number;
  targetEndLine: number;
  category: "module" | "record" | "field" | "function";
  symbol: string;
}

export interface SourceMapDocument {
  version: number;
  backendProfile: string;
  sourceFile: string;
  artifact: string;
  entries: SourceMapEntry[];
}

export interface CobolEmitResult {
  cobol: string;
  sourceMap: SourceMapDocument;
  recordLayouts: CopybookRecordLayout[];
  cobolArtifactPath: string;
  sourceMapArtifactPath: string;
}

export interface CobolEmitOptions {
  cobolArtifactPath?: string;
  sourceMapArtifactPath?: string;
}

export interface JclEmitResult {
  jcl: string;
  jclArtifactPath: string;
}

export interface JclEmitOptions {
  jclArtifactPath?: string;
}

export function emitCobol(
  program: IRProgram,
  options: CobolEmitOptions = {},
): CobolEmitResult {
  const backendProfile = "ibm-enterprise-cobol-zos";
  const cobolArtifactPath =
    options.cobolArtifactPath ?? defaultCobolArtifactPath(program.moduleName);
  const sourceMapArtifactPath =
    options.sourceMapArtifactPath ?? "dist/maps/source-map.json";
  const lines: string[] = [];
  const entries: SourceMapEntry[] = [];

  const addLine = (line = "") => {
    lines.push(line);
  };

  const lineNumber = () => lines.length + 1;

  addLine("*> Generated by bankc.");
  addLine("*> Do not edit this file directly.");
  addLine("*> Source maps are available in dist/maps.");
  const moduleLine = lineNumber();
  addLine(`       IDENTIFICATION DIVISION.`);
  addLine(`       PROGRAM-ID. ${toCobolProgramId(program.moduleName)}.`);
  addLine("");
  addLine(`       DATA DIVISION.`);
  addLine(`       WORKING-STORAGE SECTION.`);

  const recordLayouts: CopybookRecordLayout[] = [];
  for (const record of program.records) {
    const recordStart = lineNumber();
    const layout = describeRecordLayout(record);
    recordLayouts.push(layout);
    addLine(`       01  ${layout.cobolName}.`);
    emitRecordFields(record.fields, 1, addLine);
    const recordEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: record.span.start,
      sourceEnd: record.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: recordStart,
      targetEndLine: recordEnd,
      category: "record",
      symbol: record.name,
    });

    const fieldEntries = layout.fields;
    for (let index = 0; index < fieldEntries.length; index += 1) {
      const field = record.fields[index];
      const fieldLayout = fieldEntries[index];
      entries.push({
        sourceFile: program.sourceFile,
        sourceStart: field.span.start,
        sourceEnd: field.span.end,
        artifact: cobolArtifactPath,
        targetStartLine: recordStart + 1 + index,
        targetEndLine: recordStart + 1 + index,
        category: "field",
        symbol: field.name,
      });
      void fieldLayout;
    }
  }

  for (const fn of program.functions) {
    addLine(`       01  ${functionResultName(fn.name)} PIC X VALUE 'N'.`);
  }
  addLine("");
  addLine(`       PROCEDURE DIVISION.`);

  for (const fn of program.functions) {
    const functionStart = lineNumber();
    addLine(`       ${toCobolParagraphName(fn.name)}.`);
    emitFunctionBody(fn, addLine);
    const functionEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: fn.span.start,
      sourceEnd: fn.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: functionStart,
      targetEndLine: functionEnd,
      category: "function",
      symbol: fn.name,
    });
  }

  entries.unshift({
    sourceFile: program.sourceFile,
    sourceStart: program.moduleSpan.start,
    sourceEnd: program.moduleSpan.end,
    artifact: cobolArtifactPath,
    targetStartLine: moduleLine,
    targetEndLine: moduleLine + 1,
    category: "module",
    symbol: program.moduleName,
  });

  return {
    cobol: `${lines.join("\n")}\n`,
    sourceMap: {
      version: 1,
      backendProfile,
      sourceFile: program.sourceFile,
      artifact: sourceMapArtifactPath,
      entries,
    },
    recordLayouts,
    cobolArtifactPath,
    sourceMapArtifactPath,
  };
}

export function emitJcl(
  program: IRProgram,
  options: JclEmitOptions = {},
): JclEmitResult {
  const jclArtifactPath =
    options.jclArtifactPath ?? defaultJclArtifactPath(program.moduleName);
  const jobName = toJclJobName(program.moduleName);
  const cobolArtifactPath = defaultCobolArtifactPath(program.moduleName);
  const copybookArtifactPaths = program.records.map(
    (record) => `dist/copybooks/${toCobolName(record.name)}.cpy`,
  );

  const lines = [
    "//* Generated by bankc.",
    "//* Do not edit this file directly.",
    `//${jobName} JOB (BANKLANG),'${toCobolName(program.moduleName)}',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID`,
    "//* Batch job example for the generated COBOL artifact.",
    `//* COBOL source: ${cobolArtifactPath}`,
    ...copybookArtifactPaths.map(
      (copybookPath) => `//* COPYBOOK source: ${copybookPath}`,
    ),
    `//COMPILE  EXEC PGM=IGYCRCTL`,
    `//SYSPRINT DD SYSOUT=*`,
    `//SYSIN    DD DISP=SHR,DSN=${toJclDatasetName(cobolArtifactPath)}`,
    `//* The compile step above is a documentation-friendly skeleton.`,
  ];

  return {
    jcl: `${lines.join("\n")}\n`,
    jclArtifactPath,
  };
}

function emitRecordFields(
  fields: IRRecord["fields"],
  level: number,
  addLine: (line?: string) => void,
): void {
  const indent = " ".repeat(7 + level * 4);
  for (const field of fields) {
    if (field.type.kind === "record") {
      addLine(`${indent}05  ${toCobolFieldName(field.name)}.`);
      emitRecordFields(field.type.fields, level + 1, addLine);
      continue;
    }

    addLine(
      `${indent}05  ${toCobolFieldName(field.name).padEnd(20)} ${formatCobolType(field.type)}.`,
    );
  }
}

function emitFunctionBody(
  fn: IRFunction,
  addLine: (line?: string) => void,
): void {
  emitStatement(fn.body, addLine, 11, functionResultName(fn.name));
}

function emitStatement(
  block: IRBlock,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  for (const statement of block.statements) {
    switch (statement.kind) {
      case "ReturnStatement":
        emitReturnStatement(statement, addLine, indent, resultName);
        break;
      case "IfStatement":
        emitIfStatement(statement, addLine, indentLevel, resultName);
        break;
    }
  }
}

function emitIfStatement(
  statement: IRIfStatement,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  addLine(`${indent}IF ${renderExpression(statement.condition)}`);
  emitStatement(statement.thenBranch, addLine, indentLevel + 4, resultName);
  if (statement.elseBranch) {
    addLine(`${indent}ELSE`);
    emitStatement(statement.elseBranch, addLine, indentLevel + 4, resultName);
  }
  addLine(`${indent}END-IF`);
}

function emitReturnStatement(
  statement: { expression: IRExpression },
  addLine: (line?: string) => void,
  indent: string,
  resultName: string,
): void {
  const expression = statement.expression;
  if (expression.kind === "BooleanLiteral") {
    addLine(`${indent}MOVE '${expression.value ? "Y" : "N"}' TO ${resultName}`);
    addLine(`${indent}GOBACK.`);
    return;
  }

  if (expression.kind === "BinaryComparison") {
    const left = renderExpression(expression.left);
    const right = renderExpression(expression.right);
    addLine(`${indent}IF ${left} ${expression.operator} ${right}`);
    addLine(`${indent}    MOVE 'Y' TO ${resultName}`);
    addLine(`${indent}ELSE`);
    addLine(`${indent}    MOVE 'N' TO ${resultName}`);
    addLine(`${indent}END-IF`);
    addLine(`${indent}GOBACK.`);
    return;
  }

  addLine(`${indent}MOVE ${renderExpression(expression)} TO ${resultName}`);
  addLine(`${indent}GOBACK.`);
}

function renderExpression(expression: IRExpression): string {
  switch (expression.kind) {
    case "Identifier":
      return toCobolFieldName(expression.name);
    case "DecimalLiteral":
      return expression.text;
    case "BooleanLiteral":
      return expression.value ? "TRUE" : "FALSE";
    case "BinaryComparison":
      return `${renderExpression(expression.left)} ${expression.operator} ${renderExpression(expression.right)}`;
  }
}

function functionResultName(functionName: string): string {
  return toCobolName(`${functionName}Result`);
}

function defaultCobolArtifactPath(moduleName: string): string {
  return `dist/cobol/${toCobolProgramId(moduleName)}.cbl`;
}

function defaultJclArtifactPath(moduleName: string): string {
  return `dist/jcl/${toCobolProgramId(moduleName)}.jcl`;
}

function toJclJobName(moduleName: string): string {
  return toCobolProgramId(moduleName).replace(/-/g, "").slice(0, 8);
}

function toJclDatasetName(cobolArtifactPath: string): string {
  return cobolArtifactPath
    .replace(/\.cbl$/i, "")
    .replace(/\//g, ".")
    .replace(/-/g, "")
    .toUpperCase();
}

function formatCobolType(type: IRType): string {
  switch (type.kind) {
    case "decimal":
      return decimalPicture(type.precision, type.scale);
    case "string":
      return `PIC X(${type.length})`;
    case "bool":
      return "PIC X VALUE 'N'";
    case "record":
      return toCobolName(type.name);
  }
}

export function renderCopybook(record: IRRecord): string {
  const layout = describeRecordLayout(record);
  const lines = [
    "*> Generated by bankc.",
    "*> Do not edit this file directly.",
    `01  ${layout.cobolName}.`,
    ...layout.fields.map(
      (field) => `    05  ${field.cobolName.padEnd(20)} ${field.picture}.`,
    ),
  ];

  return `${lines.join("\n")}\n`;
}

export function countPackedDecimalBytes(precision: number): number {
  return packedDecimalByteLength(precision);
}
