import type { SourcePosition, SourceSpan } from "../../ast/src/index";
import type {
  IRBinaryComparisonExpression,
  IRBinaryArithmeticExpression,
  IRBlock,
  IRBooleanLiteralExpression,
  IRDecimalLiteralExpression,
  IRExpression,
  IRField,
  IRIfStatement,
  IRFunction,
  IRIdentifierExpression,
  IRLetStatement,
  IRProgram,
  IRRecord,
  IRType,
  IRStatement,
  IRLedgerStatement,
  IRAuditStatement,
  IRMemberAccessExpression,
  IRFile,
  IRWhileStatement,
  IRAssignStatement,
  IRExpressionStatement,
  IRFileStatement,
  IRSwitchStatement,
} from "../../ir/src/index";
import {
  decimalPicture,
  packedDecimalByteLength,
  toCobolFieldName,
  toCobolName,
  toCobolParagraphName,
  toCobolPicture,
  toCobolProgramId,
  enumWidth,
} from "../../cobol-ir/src/index";
import {
  describeRecordLayout,
  type CopybookRecordLayout,
} from "../../copybook/src/index";

/**
 * BankLang ledger and audit calling convention. See ADR-0003. The field widths
 * are fixed so the generated group items stay layout-stable across programs.
 */
const LEDGER_PROGRAM = "BANKLEDG";
const AUDIT_PROGRAM = "BANKAUDT";
const LEDGER_INTERFACE_GROUP = "BANK-LEDGER-INTERFACE";
const AUDIT_INTERFACE_GROUP = "BANK-AUDIT-INTERFACE";
const LEDGER_OPERATION_FIELD = "BANK-LEDGER-OPERATION";
const LEDGER_ACCOUNT_FIELD = "BANK-LEDGER-ACCOUNT";
const LEDGER_AMOUNT_FIELD = "BANK-LEDGER-AMOUNT";
const AUDIT_EVENT_FIELD = "BANK-AUDIT-EVENT";
const AUDIT_CORRELATION_FIELD = "BANK-AUDIT-CORRELATION";
const LEDGER_ACCOUNT_LENGTH = 32;
const LEDGER_AMOUNT_PICTURE = "PIC S9(16)V99 COMP-3";
const AUDIT_EVENT_LENGTH = 32;
const AUDIT_CORRELATION_LENGTH = 64;
const FILE_STATUS_PICTURE = "PIC XX";

/**
 * Parameter name to COBOL field, for the function currently being emitted.
 *
 * Parameters live in their own storage so calls can pass arguments, so a
 * reference to `amount` inside `validateAmount` must render as
 * `VALIDATE-AMOUNT-P1` rather than `AMOUNT`.
 */
let currentParameters = new Map<string, string>();

/** BankTS comparison operators to COBOL relational operators. */
const COBOL_COMPARISONS: Record<string, string> = {
  "<": "<",
  "<=": "<=",
  ">": ">",
  ">=": ">=",
  "==": "=",
  "!=": "NOT =",
};

/** BankTS rounding modes to COBOL `ROUNDED MODE IS` phrases. */
const COBOL_ROUNDING_MODES: Record<string, string> = {
  HALF_EVEN: "NEAREST-EVEN",
  HALF_UP: "NEAREST-AWAY-FROM-ZERO",
  HALF_DOWN: "NEAREST-TOWARD-ZERO",
  UP: "AWAY-FROM-ZERO",
  DOWN: "TRUNCATION",
  CEILING: "TOWARD-GREATER",
  FLOOR: "TOWARD-LESSER",
};

export interface SourceMapEntry {
  sourceFile: string;
  sourceStart: SourcePosition;
  sourceEnd: SourcePosition;
  artifact: string;
  targetStartLine: number;
  targetEndLine: number;
  category: "module" | "record" | "field" | "function" | "transaction";
  symbol: string;
}

export interface SourceMapDocument {
  version: number;
  backendProfile: string;
  sourceFile: string;
  artifact: string;
  entries: SourceMapEntry[];
}

export interface CobolEmitResult {
  cobol: string;
  sourceMap: SourceMapDocument;
  recordLayouts: CopybookRecordLayout[];
  cobolArtifactPath: string;
  sourceMapArtifactPath: string;
}

export interface CobolEmitOptions {
  cobolArtifactPath?: string;
  sourceMapArtifactPath?: string;
}

export interface JclEmitResult {
  jcl: string;
  jclArtifactPath: string;
}

export interface JclEmitOptions {
  jclArtifactPath?: string;
}

export function emitCobol(
  program: IRProgram,
  options: CobolEmitOptions = {},
): CobolEmitResult {
  const backendProfile = "ibm-enterprise-cobol-zos";
  const cobolArtifactPath =
    options.cobolArtifactPath ?? defaultCobolArtifactPath(program.moduleName);
  const sourceMapArtifactPath =
    options.sourceMapArtifactPath ?? "dist/maps/source-map.json";
  const lines: string[] = [];
  const entries: SourceMapEntry[] = [];

  const addLine = (line = "") => {
    lines.push(line);
  };

  const lineNumber = () => lines.length + 1;

  addLine("*> Generated by bankc.");
  addLine("*> Do not edit this file directly.");
  addLine("*> Source maps are available in dist/maps.");
  const moduleLine = lineNumber();
  addLine(`       IDENTIFICATION DIVISION.`);
  addLine(`       PROGRAM-ID. ${toCobolProgramId(program.moduleName)}.`);
  addLine("");

  if (program.files.length > 0) {
    addLine(`       ENVIRONMENT DIVISION.`);
    addLine(`       INPUT-OUTPUT SECTION.`);
    addLine(`       FILE-CONTROL.`);
    for (const file of program.files) {
      emitFileControlEntry(file, addLine);
    }
    addLine("");
  }

  addLine(`       DATA DIVISION.`);

  if (program.files.length > 0) {
    addLine(`       FILE SECTION.`);
    for (const file of program.files) {
      // The FD record carries the real field structure, with names prefixed by
      // the file so they cannot collide with the working-storage record. That
      // is what makes per-field access and a RECORD KEY possible.
      addLine(`       FD  ${fileCobolName(file.name)}.`);
      addLine(`       01  ${fileRecordName(file)}.`);
      emitRecordFields(file.record.fields, 1, addLine);
    }
  }

  addLine(`       WORKING-STORAGE SECTION.`);

  for (const file of program.files) {
    if (file.statusName) {
      addLine(
        `       01  ${toCobolFieldName(file.statusName).padEnd(20)} ${FILE_STATUS_PICTURE}.`,
      );
    }
  }
  emitRelativeKeys(program.files, addLine);

  const recordLayouts: CopybookRecordLayout[] = [];
  for (const record of program.records) {
    const recordStart = lineNumber();
    const layout = describeRecordLayout(record);
    recordLayouts.push(layout);
    addLine(`       01  ${layout.cobolName}.`);
    // Field start lines are recorded as they are emitted, because a field can
    // span several lines: an enum adds level-88 entries, a nullable adds an
    // indicator, and an array of records nests its own fields.
    const fieldLines: number[] = [];
    for (const field of record.fields) {
      fieldLines.push(lineNumber());
      emitField(field.name, field.type, 1, " ".repeat(11), addLine);
    }
    const recordEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: record.span.start,
      sourceEnd: record.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: recordStart,
      targetEndLine: recordEnd,
      category: "record",
      symbol: record.name,
    });

    for (let index = 0; index < record.fields.length; index += 1) {
      const field = record.fields[index];
      const start = fieldLines[index];
      const end = (fieldLines[index + 1] ?? recordEnd + 1) - 1;
      entries.push({
        sourceFile: program.sourceFile,
        sourceStart: field.span.start,
        sourceEnd: field.span.end,
        artifact: cobolArtifactPath,
        targetStartLine: start,
        targetEndLine: Math.max(start, end),
        category: "field",
        symbol: field.name,
      });
    }
  }

  for (const fn of program.functions) {
    addLine(
      `       01  ${functionResultName(fn.name)} ${formatCobolType(fn.returnType)}.`,
    );
    // Parameters get their own storage so a call can move arguments in.
    // Without this, a parameter reference only resolved by coinciding with a
    // record field name.
    fn.parameters.forEach((parameter, index) => {
      // A record parameter refers to the record's group item, which is already
      // declared once. Only scalars need their own storage.
      if (parameter.type.kind === "record") {
        return;
      }
      addLine(
        `       01  ${parameterFieldName(fn.name, index).padEnd(20)} ${formatCobolType(parameter.type)}.`,
      );
    });
    for (const local of collectFunctionLocals(fn.body)) {
      addLine(
        `       01  ${toCobolFieldName(local.name).padEnd(20)} ${formatCobolType(local.declaredType)}.`,
      );
    }
  }

  for (const transaction of program.transactions) {
    transaction.parameters.forEach((parameter, index) => {
      if (parameter.type.kind === "record") {
        return;
      }
      addLine(
        `       01  ${parameterFieldName(transaction.name, index).padEnd(20)} ${formatCobolType(parameter.type)}.`,
      );
    });
    for (const local of collectFunctionLocals(transaction.body)) {
      addLine(
        `       01  ${toCobolFieldName(local.name).padEnd(20)} ${formatCobolType(local.declaredType)}.`,
      );
    }
  }

  // Loop guard counters, one per loop, named from its source position.
  const counters = [
    ...program.functions.map((fn) => fn.body),
    ...program.transactions.map((transaction) => transaction.body),
  ].flatMap((body) => collectLoops(body));
  for (const loop of counters) {
    addLine(`       01  ${loopCounterName(loop).padEnd(20)} PIC 9(9) COMP.`);
  }
  if (program.transactions.length > 0) {
    emitLedgerInterfaceStorage(addLine);
  }

  addLine("");
  addLine(`       PROCEDURE DIVISION.`);

  for (const fn of program.functions) {
    const functionStart = lineNumber();
    addLine(`       ${toCobolParagraphName(fn.name)}.`);
    emitFunctionBody(fn, addLine);
    const functionEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: fn.span.start,
      sourceEnd: fn.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: functionStart,
      targetEndLine: functionEnd,
      category: "function",
      symbol: fn.name,
    });
  }

  for (const transaction of program.transactions) {
    const transactionStart = lineNumber();
    addLine(`       ${toCobolParagraphName(transaction.name)}.`);
    currentParameters = parameterBindings(
      transaction.name,
      transaction.parameters,
    );
    emitTransactionBody(transaction.body, addLine, 11);
    currentParameters = new Map();
    addLine(`           GOBACK.`);
    const transactionEnd = lineNumber() - 1;
    entries.push({
      sourceFile: program.sourceFile,
      sourceStart: transaction.span.start,
      sourceEnd: transaction.span.end,
      artifact: cobolArtifactPath,
      targetStartLine: transactionStart,
      targetEndLine: transactionEnd,
      category: "transaction",
      symbol: transaction.name,
    });
  }

  entries.unshift({
    sourceFile: program.sourceFile,
    sourceStart: program.moduleSpan.start,
    sourceEnd: program.moduleSpan.end,
    artifact: cobolArtifactPath,
    targetStartLine: moduleLine,
    targetEndLine: moduleLine + 1,
    category: "module",
    symbol: program.moduleName,
  });

  return {
    cobol: `${lines.join("\n")}\n`,
    sourceMap: {
      version: 1,
      backendProfile,
      sourceFile: program.sourceFile,
      artifact: sourceMapArtifactPath,
      entries,
    },
    recordLayouts,
    cobolArtifactPath,
    sourceMapArtifactPath,
  };
}

export function emitJcl(
  program: IRProgram,
  options: JclEmitOptions = {},
): JclEmitResult {
  const jclArtifactPath =
    options.jclArtifactPath ?? defaultJclArtifactPath(program.moduleName);
  const jobName = toJclJobName(program.moduleName);
  const cobolArtifactPath = defaultCobolArtifactPath(program.moduleName);
  const copybookArtifactPaths = program.records.map(
    (record) => `dist/copybooks/${toCobolName(record.name)}.cpy`,
  );

  const lines = [
    "//* Generated by bankc.",
    "//* Do not edit this file directly.",
    `//${jobName} JOB (BANKLANG),'${toCobolName(program.moduleName)}',CLASS=A,MSGCLASS=X,NOTIFY=&SYSUID`,
    "//* Batch job example for the generated COBOL artifact.",
    `//* COBOL source: ${cobolArtifactPath}`,
    ...copybookArtifactPaths.map(
      (copybookPath) => `//* COPYBOOK source: ${copybookPath}`,
    ),
    `//COMPILE  EXEC PGM=IGYCRCTL`,
    `//SYSPRINT DD SYSOUT=*`,
    `//SYSIN    DD DISP=SHR,DSN=${toJclDatasetName(cobolArtifactPath)}`,
    `//* The compile step above is a documentation-friendly skeleton.`,
  ];

  return {
    jcl: `${lines.join("\n")}\n`,
    jclArtifactPath,
  };
}

/**
 * A SELECT entry binding the BankTS file declaration to a DD name, with the
 * FILE STATUS clause when the declaration provides a status field. A missing
 * status is reported by the analyzer as BANK-FILE-001 rather than silently
 * omitted here.
 */
function emitFileControlEntry(
  file: IRFile,
  addLine: (line?: string) => void,
): void {
  const cobolName = fileCobolName(file.name);
  const clauses: string[] = [
    `               ORGANIZATION IS ${file.organization.toUpperCase()}`,
  ];

  // An indexed file is read by key, so it uses random access and names its
  // record key. Sequential and relative files stay sequential.
  if (file.organization === "indexed") {
    clauses.push(`               ACCESS MODE IS RANDOM`);
    if (file.keyFieldName) {
      clauses.push(
        `               RECORD KEY IS ${fdFieldName(file, file.keyFieldName)}`,
      );
    }
  } else if (file.organization === "relative") {
    clauses.push(`               ACCESS MODE IS SEQUENTIAL`);
    clauses.push(`               RELATIVE KEY IS ${relativeKeyName(file)}`);
  } else {
    clauses.push(`               ACCESS MODE IS SEQUENTIAL`);
  }

  if (file.statusName) {
    clauses.push(
      `               FILE STATUS IS ${toCobolFieldName(file.statusName)}`,
    );
  }

  addLine(`           SELECT ${cobolName} ASSIGN TO ${toDdName(file.name)}`);
  clauses.forEach((clause, index) => {
    addLine(index === clauses.length - 1 ? `${clause}.` : clause);
  });
}

/**
 * A field of the FD record, qualified by the FD record name.
 *
 * The FD record is structured rather than an opaque buffer, so per-field access
 * works. Field names are not prefixed: COBOL permits duplicate data names as
 * long as every reference is qualified, and prefixing would collide with the
 * conventional `<file>Status` name for the file status field.
 */
function fdFieldName(file: IRFile, fieldName: string): string {
  return `${toCobolFieldName(fieldName)} OF ${fileRecordName(file)}`;
}

function relativeKeyName(file: IRFile): string {
  return `${toCobolName(file.name)}-RRN`;
}

/** Relative files need their record number declared in working storage. */
function emitRelativeKeys(
  files: IRFile[],
  addLine: (line?: string) => void,
): void {
  for (const file of files) {
    if (file.organization === "relative") {
      addLine(`       01  ${relativeKeyName(file).padEnd(20)} PIC 9(9) COMP.`);
    }
  }
}

/**
 * COBOL file names are suffixed with -FILE.
 *
 * A BankTS file and record type often share a name (`accountMaster` carrying
 * `AccountMaster`), which would otherwise produce two COBOL items with the same
 * data name. The suffix is also the conventional COBOL spelling.
 */
function fileCobolName(fileName: string): string {
  return `${toCobolName(fileName)}-FILE`;
}

function fileRecordName(file: IRFile): string {
  return `${toCobolName(file.name)}-RECORD`;
}

/**
 * z/OS DD names are at most eight characters, so the file name is folded to a
 * deterministic uppercase alphanumeric prefix.
 */
function toDdName(fileName: string): string {
  return toCobolName(fileName).replace(/-/g, "").slice(0, 8);
}

function emitLedgerInterfaceStorage(addLine: (line?: string) => void): void {
  addLine(`       01  ${LEDGER_INTERFACE_GROUP}.`);
  addLine(`           05  ${LEDGER_OPERATION_FIELD.padEnd(24)} PIC X(6).`);
  addLine(
    `           05  ${LEDGER_ACCOUNT_FIELD.padEnd(24)} PIC X(${LEDGER_ACCOUNT_LENGTH}).`,
  );
  addLine(
    `           05  ${LEDGER_AMOUNT_FIELD.padEnd(24)} ${LEDGER_AMOUNT_PICTURE}.`,
  );
  addLine(`       01  ${AUDIT_INTERFACE_GROUP}.`);
  addLine(
    `           05  ${AUDIT_EVENT_FIELD.padEnd(24)} PIC X(${AUDIT_EVENT_LENGTH}).`,
  );
  addLine(
    `           05  ${AUDIT_CORRELATION_FIELD.padEnd(24)} PIC X(${AUDIT_CORRELATION_LENGTH}).`,
  );
}

function emitRecordFields(
  fields: IRRecord["fields"],
  level: number,
  addLine: (line?: string) => void,
): void {
  const indent = " ".repeat(7 + level * 4);
  for (const field of fields) {
    emitField(field.name, field.type, level, indent, addLine);
  }
}

/** COBOL level numbers step 05, 10, 15 with nesting depth. */
function levelNumber(level: number): string {
  return String(Math.min(level * 5, 45)).padStart(2, "0");
}

function emitField(
  name: string,
  type: IRType,
  level: number,
  indent: string,
  addLine: (line?: string) => void,
): void {
  const cobolName = toCobolFieldName(name);
  const lvl = levelNumber(level);

  // A bounded array becomes OCCURS. Arrays of records nest their fields.
  if (type.kind === "array") {
    if (type.element.kind === "record") {
      addLine(`${indent}${lvl}  ${cobolName} OCCURS ${type.length} TIMES.`);
      emitRecordFields(type.element.fields, level + 1, addLine);
      return;
    }
    addLine(
      `${indent}${lvl}  ${cobolName.padEnd(20)} ${formatCobolType(type.element)}`,
    );
    addLine(`${indent}        OCCURS ${type.length} TIMES.`);
    return;
  }

  if (type.kind === "record") {
    addLine(`${indent}${lvl}  ${cobolName}.`);
    emitRecordFields(type.fields, level + 1, addLine);
    return;
  }

  // A nullable value carries a Db2-style indicator halfword beside it.
  if (type.kind === "nullable") {
    emitField(name, type.inner, level, indent, addLine);
    addLine(
      `${indent}${lvl}  ${nullIndicatorName(name).padEnd(20)} PIC S9(4) COMP.`,
    );
    return;
  }

  addLine(`${indent}${lvl}  ${cobolName.padEnd(20)} ${formatCobolType(type)}.`);

  // Enum members become level-88 condition names, the idiomatic COBOL form.
  if (type.kind === "enum") {
    for (const member of type.members) {
      addLine(
        `${indent}    88  ${enumConditionName(name, member).padEnd(28)} VALUE "${member}".`,
      );
    }
  }
}

function nullIndicatorName(fieldName: string): string {
  return `${toCobolFieldName(fieldName)}-IND`;
}

function enumConditionName(fieldName: string, member: string): string {
  return `${toCobolFieldName(fieldName)}-${toCobolName(member)}`;
}

/**
 * Return statements only assign the result field. The paragraph ends with a
 * single `GOBACK.`, because a period inside an `IF` branch would terminate the
 * COBOL sentence and leave the following `ELSE` and `END-IF` dangling.
 */
function emitFunctionBody(
  fn: IRFunction,
  addLine: (line?: string) => void,
): void {
  currentParameters = parameterBindings(fn.name, fn.parameters);
  emitStatement(fn.body, addLine, 11, functionResultName(fn.name));
  currentParameters = new Map();
  addLine(`           GOBACK.`);
}

function emitStatement(
  block: IRBlock,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  for (const statement of block.statements) {
    switch (statement.kind) {
      case "LetStatement":
        emitLetStatement(statement, addLine, indent);
        break;
      case "ReturnStatement":
        emitReturnStatement(statement, addLine, indent, resultName);
        break;
      case "IfStatement":
        emitIfStatement(statement, addLine, indentLevel, resultName);
        break;
      case "WhileStatement":
        emitWhileStatement(statement, addLine, indentLevel, resultName);
        break;
      case "AssignStatement":
        emitAssignStatement(statement, addLine, indent);
        break;
      case "ExpressionStatement":
        emitExpressionStatement(statement, addLine, indent);
        break;
      case "FileStatement":
        emitFileStatement(statement, addLine, indent);
        break;
      case "SwitchStatement":
        emitSwitchStatement(statement, addLine, indentLevel, resultName, false);
        break;
      default:
        throw new Error(
          `Unsupported statement in function body: ${statement.kind}`,
        );
    }
  }
}

/**
 * Transaction bodies carry effects rather than a return value, so they emit
 * through their own path. The typechecker restricts them to let, debit, credit,
 * and audit statements.
 */
function emitTransactionBody(
  block: IRBlock,
  addLine: (line?: string) => void,
  indentLevel: number,
): void {
  const indent = " ".repeat(indentLevel);
  void indentLevel;
  for (const statement of block.statements) {
    switch (statement.kind) {
      case "LetStatement":
        emitLetStatement(statement, addLine, indent);
        break;
      case "LedgerStatement":
        emitLedgerStatement(statement, addLine, indent);
        break;
      case "AuditStatement":
        emitAuditStatement(statement, addLine, indent);
        break;
      case "IfStatement":
        emitTransactionBranch(statement, addLine, indentLevel);
        break;
      case "WhileStatement":
        emitWhileStatement(statement, addLine, indentLevel, "");
        break;
      case "AssignStatement":
        emitAssignStatement(statement, addLine, indent);
        break;
      case "ExpressionStatement":
        emitExpressionStatement(statement, addLine, indent);
        break;
      case "FileStatement":
        emitFileStatement(statement, addLine, indent);
        break;
      case "SwitchStatement":
        emitSwitchStatement(statement, addLine, indentLevel, "", true);
        break;
      default:
        throw new Error(
          `Unsupported statement in transaction body: ${statement.kind}`,
        );
    }
  }
}

/**
 * Ledger postings are delegated to the BankLang ledger interface described in
 * ADR-0003. The generated COBOL fills a fixed group item and calls a named
 * program rather than inlining any posting logic.
 */
function emitLedgerStatement(
  statement: IRLedgerStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  addLine(
    `${indent}MOVE "${statement.operation.toUpperCase()}" TO ${LEDGER_OPERATION_FIELD}`,
  );
  addLine(
    `${indent}MOVE ${renderExpression(statement.account)} TO ${LEDGER_ACCOUNT_FIELD}`,
  );
  addLine(
    `${indent}MOVE ${renderDecimalExpression(statement.amount)} TO ${LEDGER_AMOUNT_FIELD}`,
  );
  addLine(`${indent}CALL "${LEDGER_PROGRAM}" USING ${LEDGER_INTERFACE_GROUP}`);
}

function emitAuditStatement(
  statement: IRAuditStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  addLine(
    `${indent}MOVE ${renderExpression(statement.eventName)} TO ${AUDIT_EVENT_FIELD}`,
  );
  addLine(
    `${indent}MOVE ${renderExpression(statement.correlation)} TO ${AUDIT_CORRELATION_FIELD}`,
  );
  addLine(`${indent}CALL "${AUDIT_PROGRAM}" USING ${AUDIT_INTERFACE_GROUP}`);
}

/** `switch` over an enum becomes `EVALUATE TRUE` over the level-88 names. */
function emitSwitchStatement(
  statement: IRSwitchStatement,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
  inTransaction: boolean,
): void {
  const indent = " ".repeat(indentLevel);
  const subject = renderExpression(statement.subject);

  addLine(`${indent}EVALUATE ${subject}`);
  for (const branch of statement.cases) {
    addLine(`${indent}    WHEN "${branch.member}"`);
    if (inTransaction) {
      emitTransactionBody(branch.body, addLine, indentLevel + 8);
    } else {
      emitStatement(branch.body, addLine, indentLevel + 8, resultName);
    }
  }
  if (statement.otherwise) {
    addLine(`${indent}    WHEN OTHER`);
    if (inTransaction) {
      emitTransactionBody(statement.otherwise, addLine, indentLevel + 8);
    } else {
      emitStatement(statement.otherwise, addLine, indentLevel + 8, resultName);
    }
  }
  addLine(`${indent}END-EVALUATE`);
}

/** `IF` inside a transaction branches on effects, not on a returned value. */
function emitTransactionBranch(
  statement: IRIfStatement,
  addLine: (line?: string) => void,
  indentLevel: number,
): void {
  const indent = " ".repeat(indentLevel);
  emitCallsIn(statement.condition, addLine, indent);
  addLine(`${indent}IF ${renderCondition(statement.condition)}`);
  emitTransactionBody(statement.thenBranch, addLine, indentLevel + 4);
  if (statement.elseBranch) {
    addLine(`${indent}ELSE`);
    emitTransactionBody(statement.elseBranch, addLine, indentLevel + 4);
  }
  addLine(`${indent}END-IF`);
}

/**
 * `PERFORM UNTIL` with a guard counter.
 *
 * The declared limit is emitted as a real counter rather than trusted, so a
 * loop whose condition never goes false still terminates. BANK-TXN-004 makes
 * the limit mandatory; this makes it enforced at run time.
 */
function emitWhileStatement(
  statement: IRWhileStatement,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  const counter = loopCounterName(statement);

  addLine(`${indent}MOVE 0 TO ${counter}`);
  addLine(
    `${indent}PERFORM UNTIL ${counter} >= ${statement.limit} OR NOT (${renderCondition(statement.condition)})`,
  );
  addLine(`${indent}    ADD 1 TO ${counter}`);
  emitStatement(statement.body, addLine, indentLevel + 4, resultName);
  addLine(`${indent}END-PERFORM`);
}

function emitAssignStatement(
  statement: IRAssignStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  const target =
    statement.target.kind === "Identifier"
      ? resolveIdentifier(statement.target.name)
      : renderQualifiedFieldReference(statement.target);

  emitComputeInto(target, statement.expression, addLine, indent);
}

function emitExpressionStatement(
  statement: IRExpressionStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  emitCallsIn(statement.expression, addLine, indent);
}

/**
 * File operations, each followed by its status check when the declaration
 * bound a status field. `read` also drives the AT END path by moving the
 * end-of-file status into the status field.
 */
function emitFileStatement(
  statement: IRFileStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  const file = fileCobolName(statement.fileName);

  switch (statement.operation) {
    case "open":
      addLine(
        `${indent}OPEN ${statement.fileMode === "input" ? "INPUT" : "OUTPUT"} ${file}`,
      );
      return;
    case "close":
      addLine(`${indent}CLOSE ${file}`);
      return;
    case "read":
      // A keyed read on an indexed file moves the key into the record key
      // field first, which is how COBOL addresses a KSDS record.
      if (statement.key && statement.keyFieldName) {
        addLine(
          `${indent}MOVE ${renderExpression(statement.key)} TO ${toCobolFieldName(statement.keyFieldName)} OF ${fileRecordNameFor(statement.fileName)}`,
        );
      }
      addLine(`${indent}READ ${file} INTO ${recordTarget(statement)}`);
      if (statement.statusName) {
        // An indexed read reports a missing key rather than end of file.
        const notFound = statement.fileOrganization === "indexed" ? "23" : "10";
        const clause =
          statement.fileOrganization === "indexed" ? "INVALID KEY" : "AT END";
        addLine(
          `${indent}    ${clause} MOVE "${notFound}" TO ${toCobolFieldName(statement.statusName)}`,
        );
      }
      addLine(`${indent}END-READ`);
      return;
    case "write":
      addLine(
        `${indent}WRITE ${fileRecordNameFor(statement.fileName)} FROM ${recordTarget(statement)}`,
      );
      return;
  }
}

function recordTarget(statement: IRFileStatement): string {
  return statement.recordName
    ? resolveIdentifier(statement.recordName)
    : fileRecordNameFor(statement.fileName);
}

function fileRecordNameFor(fileName: string): string {
  return `${toCobolName(fileName)}-RECORD`;
}

/** Deterministic counter name, derived from the loop's source position. */
function loopCounterName(statement: IRWhileStatement): string {
  return `WS-LOOP-${statement.span.start.line}-${statement.span.start.column}`;
}

/**
 * Emits `PERFORM` for every call inside an expression before the expression is
 * used, because COBOL has no call-in-expression form. Results land in each
 * function's result field, which is what `renderExpression` reads.
 */
function emitCallsIn(
  expression: IRExpression,
  addLine: (line?: string) => void,
  indent: string,
): void {
  switch (expression.kind) {
    case "Call":
      for (const argument of expression.args) {
        emitCallsIn(argument, addLine, indent);
      }
      // Arguments are moved into the callee's parameter storage, then the
      // paragraph is performed.
      expression.args.forEach((argument, index) => {
        addLine(
          `${indent}MOVE ${renderExpression(argument)} TO ${parameterFieldName(expression.callee, index)}`,
        );
      });
      addLine(`${indent}PERFORM ${toCobolParagraphName(expression.callee)}`);
      return;
    case "BinaryComparison":
    case "BinaryArithmetic":
    case "Logical":
      emitCallsIn(expression.left, addLine, indent);
      emitCallsIn(expression.right, addLine, indent);
      return;
    case "Not":
      emitCallsIn(expression.operand, addLine, indent);
      return;
    case "Rounded":
      emitCallsIn(expression.operand, addLine, indent);
      return;
    default:
      return;
  }
}

/**
 * Assignment target plus expression, honouring a rounding mode when the
 * expression is a `round(...)` or `divide(...)`.
 */
function emitComputeInto(
  target: string,
  expression: IRExpression,
  addLine: (line?: string) => void,
  indent: string,
): void {
  emitCallsIn(expression, addLine, indent);

  if (expression.resolvedType.kind === "bool") {
    emitBooleanAssignment(indent, target, expression, addLine);
    return;
  }

  if (expression.resolvedType.kind === "string") {
    addLine(`${indent}MOVE ${renderExpression(expression)} TO ${target}`);
    return;
  }

  if (expression.kind === "Rounded") {
    addLine(
      `${indent}COMPUTE ${target} ROUNDED MODE IS ${COBOL_ROUNDING_MODES[expression.mode]} = ${renderDecimalExpression(expression.operand)}`,
    );
    return;
  }

  addLine(
    `${indent}COMPUTE ${target} = ${renderDecimalExpression(expression)}`,
  );
}

/**
 * Maps each parameter to the COBOL storage it reads from. Record parameters
 * resolve to the record group item; scalars get dedicated fields so a call can
 * move arguments into them.
 */
function parameterBindings(
  owner: string,
  parameters: { name: string; type: IRType }[],
): Map<string, string> {
  return new Map(
    parameters.map((parameter, index) => [
      parameter.name,
      parameter.type.kind === "record"
        ? toCobolName(parameter.type.name)
        : parameterFieldName(owner, index),
    ]),
  );
}

function resolveIdentifier(name: string): string {
  return currentParameters.get(name) ?? toCobolFieldName(name);
}

function collectLoops(block: IRBlock): IRWhileStatement[] {
  const loops: IRWhileStatement[] = [];
  for (const statement of block.statements) {
    if (statement.kind === "WhileStatement") {
      loops.push(statement);
      loops.push(...collectLoops(statement.body));
    }
    if (statement.kind === "IfStatement") {
      loops.push(...collectLoops(statement.thenBranch));
      if (statement.elseBranch) {
        loops.push(...collectLoops(statement.elseBranch));
      }
    }
  }
  return loops;
}

function parameterFieldName(functionName: string, index: number): string {
  return `${toCobolName(functionName)}-P${index + 1}`;
}

function emitLetStatement(
  statement: IRLetStatement,
  addLine: (line?: string) => void,
  indent: string,
): void {
  emitComputeInto(
    resolveIdentifier(statement.name),
    statement.initializer,
    addLine,
    indent,
  );
}

function emitIfStatement(
  statement: IRIfStatement,
  addLine: (line?: string) => void,
  indentLevel: number,
  resultName: string,
): void {
  const indent = " ".repeat(indentLevel);
  addLine(`${indent}IF ${renderCondition(statement.condition)}`);
  emitStatement(statement.thenBranch, addLine, indentLevel + 4, resultName);
  if (statement.elseBranch) {
    addLine(`${indent}ELSE`);
    emitStatement(statement.elseBranch, addLine, indentLevel + 4, resultName);
  }
  addLine(`${indent}END-IF`);
}

function emitReturnStatement(
  statement: { expression: IRExpression },
  addLine: (line?: string) => void,
  indent: string,
  resultName: string,
): void {
  emitComputeInto(resultName, statement.expression, addLine, indent);
}

function renderExpression(expression: IRExpression): string {
  switch (expression.kind) {
    case "Identifier":
      return resolveIdentifier(expression.name);
    case "DecimalLiteral":
      return expression.text;
    case "BooleanLiteral":
      return expression.value ? "TRUE" : "FALSE";
    case "StringLiteral":
      return `"${expression.value}"`;
    case "MemberAccess":
      return renderQualifiedFieldReference(expression);
    case "BinaryComparison":
      return `${renderExpression(expression.left)} ${COBOL_COMPARISONS[expression.operator]} ${renderExpression(expression.right)}`;
    case "BinaryArithmetic":
      return `${renderExpression(expression.left)} ${expression.operator} ${renderExpression(expression.right)}`;
    case "Logical":
      return `${renderExpression(expression.left)} ${expression.operator === "&&" ? "AND" : "OR"} ${renderExpression(expression.right)}`;
    case "Not":
      return `NOT (${renderExpression(expression.operand)})`;
    case "Rounded":
      return renderDecimalExpression(expression.operand);
    case "Call":
      return functionResultName(expression.callee);
    case "EnumMember":
      return `"${expression.member}"`;
    case "IndexAccess":
      return `${renderExpression(expression.target)} (${renderExpression(expression.index)})`;
    case "NullableCheck":
      return expression.operation === "isPresent"
        ? `${nullIndicatorFor(expression.operand)} = 0`
        : renderExpression(expression.operand);
  }
}

/**
 * The indicator halfword beside a nullable value. Zero means present, which
 * follows the Db2 null-indicator convention.
 */
function nullIndicatorFor(expression: IRExpression): string {
  if (expression.kind === "Identifier") {
    return `${toCobolFieldName(expression.name)}-IND`;
  }
  if (expression.kind === "MemberAccess") {
    return `${toCobolFieldName(expression.member)}-IND OF ${toCobolName(expression.recordName)}`;
  }
  return "0";
}

/**
 * COBOL qualifies a field with the group item that contains it, so
 * `request.amount` becomes `AMOUNT OF TRANSFER-REQUEST`.
 */
function renderQualifiedFieldReference(
  expression: IRMemberAccessExpression,
): string {
  const base = `${toCobolFieldName(expression.member)} OF ${toCobolName(expression.recordName)}`;
  // A subscripted field is written `FIELD OF RECORD (INDEX)`.
  return expression.index
    ? `${base} (${renderExpression(expression.index)})`
    : base;
}

function renderDecimalExpression(expression: IRExpression): string {
  switch (expression.kind) {
    case "Identifier":
      return resolveIdentifier(expression.name);
    case "DecimalLiteral":
      return expression.text;
    case "MemberAccess":
      return renderQualifiedFieldReference(expression);
    case "BinaryArithmetic":
      return `(${renderDecimalExpression(expression.left)} ${expression.operator} ${renderDecimalExpression(expression.right)})`;
    case "Rounded":
      return renderDecimalExpression(expression.operand);
    case "Call":
      return functionResultName(expression.callee);
    case "IndexAccess":
      return `${renderExpression(expression.target)} (${renderDecimalExpression(expression.index)})`;
    case "NullableCheck":
      return renderDecimalExpression(expression.operand);
    default:
      return renderExpression(expression);
  }
}

function renderCondition(expression: IRExpression): string {
  switch (expression.kind) {
    case "BooleanLiteral":
      return expression.value ? "1 = 1" : "1 = 0";
    case "Identifier":
      return expression.resolvedType.kind === "bool"
        ? `${resolveIdentifier(expression.name)} = 'Y'`
        : resolveIdentifier(expression.name);
    case "MemberAccess":
      return expression.resolvedType.kind === "bool"
        ? `${renderQualifiedFieldReference(expression)} = 'Y'`
        : renderQualifiedFieldReference(expression);
    case "Logical":
      return `(${renderCondition(expression.left)}) ${expression.operator === "&&" ? "AND" : "OR"} (${renderCondition(expression.right)})`;
    case "Not":
      return `NOT (${renderCondition(expression.operand)})`;
    case "Call":
      return `${functionResultName(expression.callee)} = 'Y'`;
    case "NullableCheck":
      return expression.operation === "isPresent"
        ? `${nullIndicatorFor(expression.operand)} = 0`
        : renderExpression(expression);
    case "BinaryComparison":
      return `${renderDecimalExpression(expression.left)} ${COBOL_COMPARISONS[expression.operator]} ${renderDecimalExpression(expression.right)}`;
    default:
      return renderExpression(expression);
  }
}

function emitBooleanAssignment(
  indent: string,
  targetName: string,
  expression: IRExpression,
  addLine: (line?: string) => void,
): void {
  if (expression.kind === "BooleanLiteral") {
    addLine(`${indent}MOVE '${expression.value ? "Y" : "N"}' TO ${targetName}`);
    return;
  }

  addLine(`${indent}IF ${renderCondition(expression)}`);
  addLine(`${indent}    MOVE 'Y' TO ${targetName}`);
  addLine(`${indent}ELSE`);
  addLine(`${indent}    MOVE 'N' TO ${targetName}`);
  addLine(`${indent}END-IF`);
}

function collectFunctionLocals(block: IRBlock): IRLetStatement[] {
  const locals: IRLetStatement[] = [];
  const seen = new Set<string>();

  const visit = (current: IRBlock): void => {
    for (const statement of current.statements) {
      if (statement.kind === "LetStatement") {
        if (!seen.has(statement.name)) {
          seen.add(statement.name);
          locals.push(statement);
        }
        continue;
      }

      if (statement.kind === "IfStatement") {
        visit(statement.thenBranch);
        if (statement.elseBranch) {
          visit(statement.elseBranch);
        }
      }
    }
  };

  visit(block);
  return locals;
}

function functionResultName(functionName: string): string {
  return toCobolName(`${functionName}Result`);
}

function defaultCobolArtifactPath(moduleName: string): string {
  return `dist/cobol/${toCobolProgramId(moduleName)}.cbl`;
}

function defaultJclArtifactPath(moduleName: string): string {
  return `dist/jcl/${toCobolProgramId(moduleName)}.jcl`;
}

function toJclJobName(moduleName: string): string {
  return toCobolProgramId(moduleName).replace(/-/g, "").slice(0, 8);
}

function toJclDatasetName(cobolArtifactPath: string): string {
  return cobolArtifactPath
    .replace(/\.cbl$/i, "")
    .replace(/\//g, ".")
    .replace(/-/g, "")
    .toUpperCase();
}

function formatCobolType(type: IRType): string {
  switch (type.kind) {
    case "decimal":
      return decimalPicture(type.precision, type.scale);
    case "string":
      return `PIC X(${type.length})`;
    case "bool":
      return "PIC X VALUE 'N'";
    case "record":
      return toCobolName(type.name);
    case "currency":
      return decimalPicture(type.precision, type.scale);
    case "enum":
      return `PIC X(${enumWidth(type.members)})`;
    case "nullable":
      return formatCobolType(type.inner);
    case "array":
      return formatCobolType(type.element);
  }
}

export function renderCopybook(record: IRRecord): string {
  const layout = describeRecordLayout(record);
  const lines = [
    "*> Generated by bankc.",
    "*> Do not edit this file directly.",
    `01  ${layout.cobolName}.`,
    ...layout.fields.map(
      (field) => `    05  ${field.cobolName.padEnd(20)} ${field.picture}.`,
    ),
  ];

  return `${lines.join("\n")}\n`;
}

export function countPackedDecimalBytes(precision: number): number {
  return packedDecimalByteLength(precision);
}
