/**
 * The comment block a generated program opens with.
 *
 * Every COBOL program written by a person for production carries one, and it is
 * the first thing anybody reads: what the program is for, what it is entered
 * with, which datasets it touches under which DD names, which modules it calls,
 * which copybooks it needs, what each return code means, and whether it can be
 * rerun. A program with none reads as machine output whatever the code below it
 * looks like — the 2026-08-05 audit called it "the cheapest change with the
 * largest effect on perceived seriousness".
 *
 * None of it is decoration. The DD table is what an operator needs when the job
 * abends on an allocation; the return-code table is what the next step's `COND=`
 * is written against; the restart note is what somebody decides at 3am. It is
 * all derived from the program rather than written by hand, so it cannot drift
 * away from what the program actually does — which is the failure mode of every
 * prologue maintained by editing.
 */

import { describeRecordLayout } from "../../copybook/src/index";
import { toCobolName } from "../../cobol-ir/src/index";
import { isLibraryModule, type IRProgram } from "../../ir/src/index";

export interface PrologueFacts {
  /** COBOL name of the program, which is also its load module member. */
  programName: string;
  /** The DD name, mode, organization and record length of each file. */
  files: {
    dd: string;
    mode: string;
    organization: string;
    record: string;
    length: number;
  }[];
  /** Modules the program calls, with what each is for. */
  calls: { name: string; purpose: string }[];
  /** Copybook members the program `COPY`s, when it copies its records. */
  copybooks: string[];
  /** Return codes the program can end with, and what each means. */
  returnCodes: { code: number; meaning: string }[];
  /** How the program is entered, in one or more lines. */
  entry: string[];
  /** What a rerun involves. */
  restart: string[];
}

/** Modules the emitter calls, and the sentence describing each. */
const RUNTIME_PURPOSES: Record<string, string> = {
  BANKLEDG: "ledger posting and rollback",
  BANKAUDT: "audit trail",
  BANKMQ: "message queue interface",
  CBLTDLI: "IMS DL/I",
};

export function prologueLines(
  program: IRProgram,
  facts: PrologueFacts,
  options: { sourceFile: string; copybookMode: "inline" | "copy" },
): string[] {
  const rule = `${COMMENT}${"-".repeat(WIDTH - COMMENT.length)}`;
  const lines: string[] = [rule];

  // Wrapped here rather than by the reference-format pass, which knows where
  // column 72 is but not that the text is prose: it breaks at the last space
  // that fits, so a sentence ends up split across an indent it did not choose
  // and the block stops reading as one.
  //
  // `hang` is the width of the entry's label column, where it has one. A
  // continuation lines up under the text it continues, so `12  A failure the
  // program named…` wraps under the meaning rather than under the `12`, and a
  // plain sentence wraps flush and reads as a paragraph. It used to indent
  // every continuation two spaces past its own first line, which lined up with
  // nothing and made each wrapped sentence read as a further, deeper entry.
  const section = (title: string, body: readonly string[], hang = 0): void => {
    if (body.length === 0) {
      return;
    }
    lines.push(COMMENT.trimEnd(), `${COMMENT}${title}`);
    for (const entry of body) {
      lines.push(...fill(entry, `${COMMENT}  `, hang));
    }
  };

  lines.push(
    `${COMMENT}${facts.programName} — ${program.moduleName}`,
    COMMENT.trimEnd(),
    // The file's own name, not the path it was compiled from. An absolute
    // path is this machine's, and a checked-in artifact holding one is not
    // reproducible anywhere else.
    ...fill(
      `Generated by bankc from ${options.sourceFile.split(/[/\\]/).pop()}.`,
      COMMENT,
    ),
    ...fill(
      "Do not edit this file directly. Source maps are in dist/maps.",
      COMMENT,
    ),
  );

  section("PURPOSE", purposeLines(program));
  section("ENTRY", facts.entry);
  section(
    "FILES",
    facts.files.map(
      (file) =>
        `${file.dd.padEnd(DD_COLUMN)}${file.mode.padEnd(8)}${file.organization.padEnd(11)}${file.record} (${file.length} bytes)`,
    ),
    DD_COLUMN,
  );
  section(
    "CALLS",
    facts.calls.map(
      (call) => `${call.name.padEnd(MODULE_COLUMN)}${call.purpose}`,
    ),
    MODULE_COLUMN,
  );
  section("COPYBOOKS", options.copybookMode === "copy" ? facts.copybooks : []);
  section(
    "RETURN CODES",
    facts.returnCodes.map(
      (entry) => `${String(entry.code).padEnd(CODE_COLUMN)}${entry.meaning}`,
    ),
    CODE_COLUMN,
  );
  section("RESTART", facts.restart);

  lines.push(rule);
  return lines;
}

/** Where a comment line starts, and the last column any line may reach. */
const COMMENT = "      *> ";
const WIDTH = 72;

/**
 * The label column of each tabular section, used twice: to pad the label and
 * to indent a continuation under the text beside it. One constant, because the
 * two drifting apart is how a wrapped line ends up lining up with nothing.
 *
 * A DD name and a load module name are both eight characters, so nine leaves
 * one space; a return code is at most two digits, and four keeps `0` and `16`
 * in one column with two spaces after the widest.
 */
const DD_COLUMN = 9;
const MODULE_COLUMN = 9;
const CODE_COLUMN = 4;

/**
 * One entry filled into as many comment lines as it needs.
 *
 * `hang` is the width of the entry's label column. A continuation is indented
 * by it, so it starts under the text it continues rather than under the label:
 * a return-code meaning wraps under the meaning, and an entry with no label
 * wraps flush and reads as a paragraph.
 */
function fill(text: string, prefix: string, hang = 0): string[] {
  const continuation = `${prefix}${" ".repeat(hang)}`;
  const lines: string[] = [];
  let rest = text;
  let current = prefix;

  while (rest.length > WIDTH - current.length) {
    const available = WIDTH - current.length;
    // A run with no space in it is cut at the margin rather than written over
    // it: past column 72 the compiler does not see the text at all, so a
    // comment that overruns loses its tail with nothing said about it.
    const cut = rest.lastIndexOf(" ", available);
    const at = cut > 0 ? cut : available;
    if (at <= 0) {
      break;
    }
    lines.push(`${current}${rest.slice(0, at)}`);
    rest = rest.slice(cut > 0 ? at + 1 : at);
    current = continuation;
  }
  lines.push(`${current}${rest}`);

  return lines;
}

/** What the program does, from the routines it declares. */
function purposeLines(program: IRProgram): string[] {
  const entry =
    program.transactions.find((transaction) => transaction.isEntry) ??
    program.transactions[0];
  if (!entry) {
    return ["A library of functions. Nothing here is an entry point."];
  }

  const others = program.transactions
    .filter((transaction) => transaction !== entry)
    .map((transaction) => toCobolName(transaction.name));

  return [
    `${toCobolName(entry.name)}, the transaction this program is entered at.`,
    ...(others.length > 0 ? [`Also carries: ${others.join(", ")}.`] : []),
  ];
}

/**
 * Everything the prologue states, read off the program.
 *
 * Separated from the rendering so a test can assert the facts rather than the
 * layout, and so the same facts can feed a different document later.
 */
export function collectPrologueFacts(
  program: IRProgram,
  options: {
    programName: string;
    ddNameOf: (fileName: string) => string;
    copybookMemberOf: (recordName: string) => string;
    parmFields: { source: string; picture: string; width: number }[];
    /** Files a `restart`/`checkpoint` pair writes its position to. */
    restartedFiles: readonly string[];
  },
): PrologueFacts {
  const cics = program.transactions.some((transaction) => transaction.isCics);
  const ims = program.databases.length > 0;

  const calls = new Set<string>();
  if (program.transactions.length > 0) {
    calls.add("BANKAUDT");
  }
  if (program.transactions.some((transaction) => transaction.postsToLedger)) {
    calls.add("BANKLEDG");
  }
  if (ims) {
    calls.add("CBLTDLI");
  }
  for (const requirement of program.backendRequirements) {
    if (requirement === "mq") {
      calls.add("BANKMQ");
    }
  }

  return {
    programName: options.programName,
    files: program.files.map((file) => ({
      dd: options.ddNameOf(file.name),
      mode: file.mode,
      organization: file.organization,
      record: toCobolName(file.record.name),
      length: describeRecordLayout(file.record).totalLength,
    })),
    calls: [...calls]
      .sort()
      .map((name) => ({ name, purpose: RUNTIME_PURPOSES[name] ?? "" })),
    copybooks: program.records
      .map((record) => options.copybookMemberOf(record.name))
      .sort(),
    returnCodes: returnCodesFor(program),
    entry: entryLines(program, { cics, ims, parmFields: options.parmFields }),
    restart: restartLines(program, options.restartedFiles),
  };
}

function entryLines(
  program: IRProgram,
  context: {
    cics: boolean;
    ims: boolean;
    parmFields: { source: string; picture: string; width: number }[];
  },
): string[] {
  // A module of functions and nothing else. The batch sentence below was
  // emitted here unconditionally, so the two library examples opened by saying
  // "Nothing here is an entry point" under PURPOSE and "started by EXEC PGM in
  // a job" under ENTRY, four lines apart. Said rather than left out: a section
  // that is simply missing reads as one somebody forgot to fill in, and this
  // is the first thing a reviewer reads.
  if (isLibraryModule(program)) {
    return [
      "None. This module is a library: it is linked into a caller and entered at one of its paragraphs, not started as a job step.",
    ];
  }

  if (context.cics) {
    const record = program.transactions.find(
      (transaction) => transaction.isCics,
    )?.parameters[0];
    return [
      "A CICS transaction, started by a transaction identifier in a region rather than by EXEC PGM in a job.",
      ...(record && record.type.kind === "record"
        ? [
            `DFHCOMMAREA holds ${toCobolName(record.type.name)}, and EIBCALEN is tested against its length before anything reads it.`,
          ]
        : []),
    ];
  }

  if (context.ims) {
    return [
      "An IMS program. The region enters it with the I/O PCB and one PCB per database, in that order, and CMPAT=YES is what puts the I/O PCB first.",
    ];
  }

  if (context.parmFields.length === 0) {
    return [
      "A batch program with no parameters, started by EXEC PGM in a job.",
    ];
  }

  const total = context.parmFields.reduce((sum, field) => sum + field.width, 0);
  return [
    `A batch program, started by EXEC PGM and entered with the job's PARM behind a halfword length: ${total} characters, positional.`,
    ...context.parmFields.map(
      (field) =>
        `${field.source.padEnd(20)}${field.picture.replace(/^PIC /, "")} (${field.width})`,
    ),
    "A PARM shorter than that ends the step with return code 12 rather than reading past what was passed.",
  ];
}

function returnCodesFor(
  program: IRProgram,
): { code: number; meaning: string }[] {
  const codes: { code: number; meaning: string }[] = [
    { code: 0, meaning: "The work completed." },
  ];

  if (program.transactions.some((transaction) => transaction.isCics)) {
    return [
      ...codes,
      {
        code: 12,
        meaning:
          "Not used under CICS. A failure abends the task with code BLNG.",
      },
    ];
  }

  codes.push({
    code: 12,
    meaning: "A failure the program named. BANK-FAILURE-CODE says which.",
  });
  if (program.files.length > 0) {
    codes.push({
      code: 16,
      meaning: "A sort or merge did not complete. SORT-RETURN says so.",
    });
  }
  return codes;
}

function restartLines(
  program: IRProgram,
  restarted: readonly string[],
): string[] {
  if (restarted.length > 0) {
    return [
      `Restartable. The position is written to ${restarted
        .map((name) => toCobolName(name))
        .join(
          ", ",
        )} and committed after the work it covers, so a rerun resumes from the last checkpoint.`,
    ];
  }
  if (program.files.some((file) => file.mode !== "input")) {
    return [
      "Not restartable. Rerun from the top: the generated job deletes a half-written output dataset rather than cataloguing it, so there is nothing for a second run to read as though it were complete.",
    ];
  }
  return ["Rerunnable. The program writes no dataset."];
}
