       PROCESS NODLL,NODYNAM,TEST(NOSEP),NOCICS,NOSQL,PGMN(LU),NOSEQ
      *> Generated by bankc.
      *> Do not edit this file directly.
      *> zUnit test case TZUNITTE for ZUNITTES.
      *> Source: main.bank.ts
      *>
      *> Run it with the job in TZUNITTE.jcl. The program under
      *> test has to be compiled with TEST and be in BZULOD, or the
      *> runner has nothing to intercept.
      *>
      *> TEST_POSTSBOTHLEGS: the driver for test POSTSBOTHLEGS.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'TEST_POSTSBOTHLEGS'.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  PROGRAM-NAME             PIC X(8) VALUE 'ZUNITTES'.
       01  AZ-CSECT                 PIC X(72) VALUE SPACES.
       01  BZ-ASSERT.
           05  MESSAGE-LEN          PIC S9(4) COMP-4 VALUE 1.
           05  MESSAGE-TXT          PIC X(254) VALUE SPACES.
       01  BZ-P1                    PIC S9(9) COMP-4 VALUE 4.
       01  BZ-P2                    PIC S9(9) COMP-4 VALUE 2001.
       01  BZ-P3                    PIC X(3) VALUE 'AZU'.
       01  BZUASSRT                 PIC X(8) VALUE 'BZUASSRT'.
       01  BZUGETEP                 PIC X(8) VALUE 'BZUGETEP'.
       01  AZ-EP-PTR                USAGE IS POINTER.
       01  AZ-TEST-LEN              PIC S9(9) COMP-5.
       01  AZ-GRP-INDEX             PIC 9(8).
       01  AZ-FLAG-IN               PIC 9(1).
       01  AZ-RECORD-PTR            USAGE IS POINTER.
       01  AZ-RC-WORK               PIC S9(4) USAGE BINARY.
       01  AZ-COUNT-SHOW            PIC Z(4)9.
       01  BANK-PARM.
           05  BANK-PARM-LENGTH     PIC S9(4) COMP.
           05  BANK-PARM-DATA.
               10  BANK-PARM-ACCOUNT        PIC X(16).
               10  BANK-PARM-AMOUNT         PIC S9(16)V9(2) SIGN IS
                   LEADING SEPARATE.
               10  BANK-PARM-IDEMPOTENCY-KEY PIC X(36).
       LINKAGE SECTION.
       01  AZ-TEST                  PIC X(80).
       01  AZ-ARG-LIST.
           05  ARG-LENGTH           PIC 9(4) COMP-4.
           05  ARG-DATA             PIC X(256).
       01  AZ-INFO-BLOCK.
           COPY EQAITERC.
       01  AZ-PROC-PTR              USAGE IS PROCEDURE-POINTER.
       01  AZ-CALL-COUNT            PIC 9(5) COMP-5.
       PROCEDURE DIVISION USING AZ-TEST AZ-ARG-LIST AZ-INFO-BLOCK.
           DISPLAY 'AZU0000I TEST_POSTSBOTHLEGS STARTED...'
           MOVE 0 TO AZ-TEST-LEN
           INSPECT AZ-TEST TALLYING AZ-TEST-LEN FOR
               CHARACTERS BEFORE INITIAL SPACE
      *> Start the call counters from zero.
           MOVE 1 TO AZ-GRP-INDEX
           MOVE 0 TO AZ-FLAG-IN
           MOVE RETURN-CODE TO AZ-RC-WORK
           CALL 'GTMEMRC' USING TC-WORK-AREA OF AZ-INFO-BLOCK
               AZ-GRP-INDEX AZ-FLAG-IN AZ-RECORD-PTR
           SET ADDRESS OF AZ-CALL-COUNT TO AZ-RECORD-PTR
           MOVE AZ-RC-WORK TO RETURN-CODE
           MOVE 0 TO AZ-CALL-COUNT
           MOVE 2 TO AZ-GRP-INDEX
           MOVE 0 TO AZ-FLAG-IN
           MOVE RETURN-CODE TO AZ-RC-WORK
           CALL 'GTMEMRC' USING TC-WORK-AREA OF AZ-INFO-BLOCK
               AZ-GRP-INDEX AZ-FLAG-IN AZ-RECORD-PTR
           SET ADDRESS OF AZ-CALL-COUNT TO AZ-RECORD-PTR
           MOVE AZ-RC-WORK TO RETURN-CODE
           MOVE 0 TO AZ-CALL-COUNT
      *> The PARM the step is started with.
           INITIALIZE BANK-PARM
           MOVE 71 TO BANK-PARM-LENGTH
           MOVE '0001234567890123' TO BANK-PARM-ACCOUNT
           MOVE 100.00 TO BANK-PARM-AMOUNT
           MOVE 'IDEM-0001' TO BANK-PARM-IDEMPOTENCY-KEY
      *> Enter the program under test.
           DISPLAY 'AZU0000I CALL ZUNITTES'
           CALL BZUGETEP USING BY REFERENCE PROGRAM-NAME AZ-CSECT
               RETURNING AZ-EP-PTR
           IF AZ-EP-PTR = NULL
               MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
               MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
               STRING 'UNABLE TO GET THE ENTRY POINT BY BZUGETEP.'
                   DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                   WITH POINTER MESSAGE-LEN OF BZ-ASSERT
               END-STRING
               SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
               PERFORM THROW-ASSERTION
               GOBACK
           END-IF
           SET ADDRESS OF AZ-PROC-PTR TO AZ-EP-PTR
           CALL AZ-PROC-PTR USING BANK-PARM
           MOVE 0 TO RETURN-CODE
      *> Every call the test expects has to have arrived.
           PERFORM CHECK-BANKLEDG-CALLS
           PERFORM CHECK-BANKAUDT-CALLS
           DISPLAY 'AZU0000I TEST_POSTSBOTHLEGS END.'
           GOBACK.
       CHECK-BANKLEDG-CALLS.
           MOVE 1 TO AZ-GRP-INDEX
           MOVE 0 TO AZ-FLAG-IN
           MOVE RETURN-CODE TO AZ-RC-WORK
           CALL 'GTMEMRC' USING TC-WORK-AREA OF AZ-INFO-BLOCK
               AZ-GRP-INDEX AZ-FLAG-IN AZ-RECORD-PTR
           SET ADDRESS OF AZ-CALL-COUNT TO AZ-RECORD-PTR
           MOVE AZ-RC-WORK TO RETURN-CODE
           IF AZ-CALL-COUNT NOT EQUAL 2
               MOVE AZ-CALL-COUNT TO AZ-COUNT-SHOW
               MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
               MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
               STRING 'EXPECTED 2 CALLS TO BANKLEDG, GOT' AZ-COUNT-SHOW
                   DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                   WITH POINTER MESSAGE-LEN OF BZ-ASSERT
               END-STRING
               SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
               PERFORM THROW-ASSERTION
           END-IF
           EXIT.
       CHECK-BANKAUDT-CALLS.
           MOVE 2 TO AZ-GRP-INDEX
           MOVE 0 TO AZ-FLAG-IN
           MOVE RETURN-CODE TO AZ-RC-WORK
           CALL 'GTMEMRC' USING TC-WORK-AREA OF AZ-INFO-BLOCK
               AZ-GRP-INDEX AZ-FLAG-IN AZ-RECORD-PTR
           SET ADDRESS OF AZ-CALL-COUNT TO AZ-RECORD-PTR
           MOVE AZ-RC-WORK TO RETURN-CODE
           IF AZ-CALL-COUNT NOT EQUAL 1
               MOVE AZ-CALL-COUNT TO AZ-COUNT-SHOW
               MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
               MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
               STRING 'EXPECTED 1 CALL TO BANKAUDT, GOT' AZ-COUNT-SHOW
                   DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                   WITH POINTER MESSAGE-LEN OF BZ-ASSERT
               END-STRING
               SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
               PERFORM THROW-ASSERTION
           END-IF
           EXIT.
       THROW-ASSERTION.
           DISPLAY 'AZU2001W THE TEST "' AZ-TEST(1:AZ-TEST-LEN)
               '" FAILED DUE TO AN ASSERTION.'
           DISPLAY 'AZU1101I ' MESSAGE-TXT OF BZ-ASSERT(1:MESSAGE-LEN OF
               BZ-ASSERT)
           CALL BZUASSRT USING BZ-P1 BZ-P2 BZ-P3 BZ-ASSERT
           EXIT.
       END PROGRAM 'TEST_POSTSBOTHLEGS'.
      *>
      *> BZU_TEST: the runner's callback for ZUNITTES itself.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'BZU_TEST'.
       DATA DIVISION.
       LINKAGE SECTION.
       01  AZ-TEST                  PIC X(80).
       01  AZ-INFO-BLOCK.
           COPY EQAITERC.
       01  BANK-PARM.
           05  BANK-PARM-LENGTH     PIC S9(4) COMP.
           05  BANK-PARM-DATA.
               10  BANK-PARM-ACCOUNT        PIC X(16).
               10  BANK-PARM-AMOUNT         PIC S9(16)V9(2) SIGN IS
                   LEADING SEPARATE.
               10  BANK-PARM-IDEMPOTENCY-KEY PIC X(36).
       PROCEDURE DIVISION.
       PGM-INPT.
           ENTRY 'PGM_INPT_ZUNITTES' USING AZ-TEST AZ-INFO-BLOCK
               BANK-PARM
           DISPLAY 'AZU0000I PGM_INPT_ZUNITTES'
           MOVE 0 TO RETURN-CODE
           GOBACK.
       PGM-OUTP.
           ENTRY 'PGM_OUTP_ZUNITTES' USING AZ-TEST AZ-INFO-BLOCK
               BANK-PARM
           DISPLAY 'AZU0000I PGM_OUTP_ZUNITTES'
           MOVE 4 TO RETURN-CODE
           GOBACK.
       END PROGRAM 'BZU_TEST'.
      *>
      *> BZU_INIT: run before each test.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'BZU_INIT'.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  AZ-TEST-LEN              PIC S9(9) COMP-5.
       01  AZ-TESTCASE-ID           PIC X(36)
           VALUE 'd012252c-2493-4992-8419-78b0a40d97ba'.
       LINKAGE SECTION.
       01  AZ-TEST                  PIC X(80).
       01  AZ-TEST-ID               PIC X(80).
       01  AZ-INFO-BLOCK.
           COPY EQAITERC.
       PROCEDURE DIVISION USING AZ-TEST AZ-TEST-ID AZ-INFO-BLOCK.
           MOVE 0 TO AZ-TEST-LEN
           INSPECT AZ-TEST TALLYING AZ-TEST-LEN FOR
               CHARACTERS BEFORE INITIAL SPACE
           DISPLAY 'AZU0000I BZU_INIT: ' AZ-TEST(1:AZ-TEST-LEN)
           MOVE AZ-TESTCASE-ID TO AZ-TEST-ID
           GOBACK.
       END PROGRAM 'BZU_INIT'.
      *>
      *> BZU_TERM: run after each test.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'BZU_TERM'.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  AZ-TEST-LEN              PIC S9(9) COMP-5.
       LINKAGE SECTION.
       01  AZ-TEST                  PIC X(80).
       01  AZ-INFO-BLOCK.
           COPY EQAITERC.
       PROCEDURE DIVISION USING AZ-TEST AZ-INFO-BLOCK.
           MOVE 0 TO AZ-TEST-LEN
           INSPECT AZ-TEST TALLYING AZ-TEST-LEN FOR
               CHARACTERS BEFORE INITIAL SPACE
           DISPLAY 'AZU0000I BZU_TERM: ' AZ-TEST(1:AZ-TEST-LEN)
           GOBACK.
       END PROGRAM 'BZU_TERM'.
      *>
      *> PGM_BANKLEDG: the stub the program's calls arrive at.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'PGM_BANKLEDG'.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BZ-ASSERT.
           05  MESSAGE-LEN          PIC S9(4) COMP-4 VALUE 1.
           05  MESSAGE-TXT          PIC X(254) VALUE SPACES.
       01  BZ-P1                    PIC S9(9) COMP-4 VALUE 4.
       01  BZ-P2                    PIC S9(9) COMP-4 VALUE 2001.
       01  BZ-P3                    PIC X(3) VALUE 'AZU'.
       01  BZUASSRT                 PIC X(8) VALUE 'BZUASSRT'.
       01  AZ-TEST-LEN              PIC S9(9) COMP-5.
       01  AZ-GRP-INDEX             PIC 9(8).
       01  AZ-FLAG-IN               PIC 9(1).
       01  AZ-RECORD-PTR            USAGE IS POINTER.
       01  AZ-RC-WORK               PIC S9(4) USAGE BINARY.
       01  AZ-CALL-NUMBER           PIC 9(5) COMP-5.
       01  AZ-COUNT-SHOW            PIC Z(4)9.
       01  AZ-AMOUNT-SHOW           PIC -(16)9.99.
       LINKAGE SECTION.
       01  AZ-TEST                  PIC X(80).
       01  AZ-INFO-BLOCK.
           COPY EQAITERC.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION    PIC X(6).
           05  BANK-LEDGER-ACCOUNT      PIC X(32).
           05  BANK-LEDGER-AMOUNT       PIC S9(16)V99 COMP-3.
       01  AZ-CALL-COUNT            PIC 9(5) COMP-5.
       PROCEDURE DIVISION.
       PGM-INPT.
           ENTRY 'PGM_INPT_BANKLEDG' USING AZ-TEST AZ-INFO-BLOCK
               BANK-LEDGER-INTERFACE
           MOVE 4 TO RETURN-CODE
           MOVE 0 TO AZ-TEST-LEN
           INSPECT AZ-TEST TALLYING AZ-TEST-LEN FOR
               CHARACTERS BEFORE INITIAL SPACE
           MOVE 1 TO AZ-GRP-INDEX
           MOVE 0 TO AZ-FLAG-IN
           MOVE RETURN-CODE TO AZ-RC-WORK
           CALL 'GTMEMRC' USING TC-WORK-AREA OF AZ-INFO-BLOCK
               AZ-GRP-INDEX AZ-FLAG-IN AZ-RECORD-PTR
           SET ADDRESS OF AZ-CALL-COUNT TO AZ-RECORD-PTR
           MOVE AZ-RC-WORK TO RETURN-CODE
           ADD 1 TO AZ-CALL-COUNT
           MOVE AZ-CALL-COUNT TO AZ-CALL-NUMBER
           EVALUATE AZ-TEST(1:AZ-TEST-LEN)
           WHEN 'POSTSBOTHLEGS'
               PERFORM CHECK-POSTSBOTHLEGS
           WHEN OTHER
               CONTINUE
           END-EVALUATE
           GOBACK.
       PGM-OUTP.
           ENTRY 'PGM_OUTP_BANKLEDG' USING AZ-TEST AZ-INFO-BLOCK
               BANK-LEDGER-INTERFACE
           MOVE 0 TO RETURN-CODE
           GOBACK.
       CHECK-POSTSBOTHLEGS.
           EVALUATE AZ-CALL-NUMBER
           WHEN 1
               IF BANK-LEDGER-OPERATION = 'DEBIT'
                   AND BANK-LEDGER-ACCOUNT = '0001234567890123'
                   AND BANK-LEDGER-AMOUNT = 100.00
                   CONTINUE
               ELSE
                   MOVE BANK-LEDGER-AMOUNT TO AZ-AMOUNT-SHOW
                   MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
                   MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
                   STRING
                       'BANKLEDG CALL 1 EXPECTED DEBIT 0001234567890123 
      -                '100.00, GOT' BANK-LEDGER-OPERATION ' '
                       BANK-LEDGER-ACCOUNT ' ' AZ-AMOUNT-SHOW
                       DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                       WITH POINTER MESSAGE-LEN OF BZ-ASSERT
                   END-STRING
                   SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
                   PERFORM THROW-ASSERTION
               END-IF
           WHEN 2
               IF BANK-LEDGER-OPERATION = 'CREDIT'
                   AND BANK-LEDGER-ACCOUNT = 'SUSPENSE'
                   AND BANK-LEDGER-AMOUNT = 100.00
                   CONTINUE
               ELSE
                   MOVE BANK-LEDGER-AMOUNT TO AZ-AMOUNT-SHOW
                   MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
                   MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
                   STRING
                       'BANKLEDG CALL 2 EXPECTED CREDIT SUSPENSE 100.00,
      -                ' GOT' BANK-LEDGER-OPERATION ' '
                       BANK-LEDGER-ACCOUNT ' ' AZ-AMOUNT-SHOW
                       DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                       WITH POINTER MESSAGE-LEN OF BZ-ASSERT
                   END-STRING
                   SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
                   PERFORM THROW-ASSERTION
               END-IF
           WHEN OTHER
               MOVE AZ-CALL-NUMBER TO AZ-COUNT-SHOW
               MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
               MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
               STRING 'MORE THAN 2 CALLS TO BANKLEDG, AT CALL'
                   AZ-COUNT-SHOW
                   DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                   WITH POINTER MESSAGE-LEN OF BZ-ASSERT
               END-STRING
               SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
               PERFORM THROW-ASSERTION
           END-EVALUATE
           EXIT.
       THROW-ASSERTION.
           DISPLAY 'AZU2001W THE TEST "' AZ-TEST(1:AZ-TEST-LEN)
               '" FAILED DUE TO AN ASSERTION.'
           DISPLAY 'AZU1101I ' MESSAGE-TXT OF BZ-ASSERT(1:MESSAGE-LEN OF
               BZ-ASSERT)
           CALL BZUASSRT USING BZ-P1 BZ-P2 BZ-P3 BZ-ASSERT
           EXIT.
       END PROGRAM 'PGM_BANKLEDG'.
      *>
      *> PGM_BANKAUDT: the stub the program's calls arrive at.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'PGM_BANKAUDT'.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BZ-ASSERT.
           05  MESSAGE-LEN          PIC S9(4) COMP-4 VALUE 1.
           05  MESSAGE-TXT          PIC X(254) VALUE SPACES.
       01  BZ-P1                    PIC S9(9) COMP-4 VALUE 4.
       01  BZ-P2                    PIC S9(9) COMP-4 VALUE 2001.
       01  BZ-P3                    PIC X(3) VALUE 'AZU'.
       01  BZUASSRT                 PIC X(8) VALUE 'BZUASSRT'.
       01  AZ-TEST-LEN              PIC S9(9) COMP-5.
       01  AZ-GRP-INDEX             PIC 9(8).
       01  AZ-FLAG-IN               PIC 9(1).
       01  AZ-RECORD-PTR            USAGE IS POINTER.
       01  AZ-RC-WORK               PIC S9(4) USAGE BINARY.
       01  AZ-CALL-NUMBER           PIC 9(5) COMP-5.
       01  AZ-COUNT-SHOW            PIC Z(4)9.
       LINKAGE SECTION.
       01  AZ-TEST                  PIC X(80).
       01  AZ-INFO-BLOCK.
           COPY EQAITERC.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT         PIC X(32).
           05  BANK-AUDIT-CORRELATION   PIC X(64).
       01  AZ-CALL-COUNT            PIC 9(5) COMP-5.
       PROCEDURE DIVISION.
       PGM-INPT.
           ENTRY 'PGM_INPT_BANKAUDT' USING AZ-TEST AZ-INFO-BLOCK
               BANK-AUDIT-INTERFACE
           MOVE 4 TO RETURN-CODE
           MOVE 0 TO AZ-TEST-LEN
           INSPECT AZ-TEST TALLYING AZ-TEST-LEN FOR
               CHARACTERS BEFORE INITIAL SPACE
           MOVE 2 TO AZ-GRP-INDEX
           MOVE 0 TO AZ-FLAG-IN
           MOVE RETURN-CODE TO AZ-RC-WORK
           CALL 'GTMEMRC' USING TC-WORK-AREA OF AZ-INFO-BLOCK
               AZ-GRP-INDEX AZ-FLAG-IN AZ-RECORD-PTR
           SET ADDRESS OF AZ-CALL-COUNT TO AZ-RECORD-PTR
           MOVE AZ-RC-WORK TO RETURN-CODE
           ADD 1 TO AZ-CALL-COUNT
           MOVE AZ-CALL-COUNT TO AZ-CALL-NUMBER
           EVALUATE AZ-TEST(1:AZ-TEST-LEN)
           WHEN 'POSTSBOTHLEGS'
               PERFORM CHECK-POSTSBOTHLEGS
           WHEN OTHER
               CONTINUE
           END-EVALUATE
           GOBACK.
       PGM-OUTP.
           ENTRY 'PGM_OUTP_BANKAUDT' USING AZ-TEST AZ-INFO-BLOCK
               BANK-AUDIT-INTERFACE
           MOVE 0 TO RETURN-CODE
           GOBACK.
       CHECK-POSTSBOTHLEGS.
           EVALUATE AZ-CALL-NUMBER
           WHEN 1
               IF BANK-AUDIT-EVENT = 'POSTED'
                   AND BANK-AUDIT-CORRELATION = 'IDEM-0001'
                   CONTINUE
               ELSE
                   MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
                   MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
                   STRING
                       'BANKAUDT CALL 1 EXPECTED POSTED IDEM-0001, GOT'
                       BANK-AUDIT-EVENT ' ' BANK-AUDIT-CORRELATION
                       DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                       WITH POINTER MESSAGE-LEN OF BZ-ASSERT
                   END-STRING
                   SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
                   PERFORM THROW-ASSERTION
               END-IF
           WHEN OTHER
               MOVE AZ-CALL-NUMBER TO AZ-COUNT-SHOW
               MOVE 1 TO MESSAGE-LEN OF BZ-ASSERT
               MOVE SPACES TO MESSAGE-TXT OF BZ-ASSERT
               STRING 'MORE THAN 1 CALL TO BANKAUDT, AT CALL'
                   AZ-COUNT-SHOW
                   DELIMITED BY SIZE INTO MESSAGE-TXT OF BZ-ASSERT
                   WITH POINTER MESSAGE-LEN OF BZ-ASSERT
               END-STRING
               SUBTRACT 1 FROM MESSAGE-LEN OF BZ-ASSERT
               PERFORM THROW-ASSERTION
           END-EVALUATE
           EXIT.
       THROW-ASSERTION.
           DISPLAY 'AZU2001W THE TEST "' AZ-TEST(1:AZ-TEST-LEN)
               '" FAILED DUE TO AN ASSERTION.'
           DISPLAY 'AZU1101I ' MESSAGE-TXT OF BZ-ASSERT(1:MESSAGE-LEN OF
               BZ-ASSERT)
           CALL BZUASSRT USING BZ-P1 BZ-P2 BZ-P3 BZ-ASSERT
           EXIT.
       END PROGRAM 'PGM_BANKAUDT'.
      *>
      *> GTMEMRC: the call counters, in storage every program sees.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. 'GTMEMRC'.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BZUGTMEM                 PIC X(8) VALUE 'BZUGTMEM'.
       01  DATA-SIZE                PIC 9(8) COMP-4.
       LINKAGE SECTION.
       01  AZ-TC-WORK-AREA          PIC X(256).
       01  AZ-GRP-INDEX             PIC 9(8).
       01  AZ-FLAG-IN               PIC 9(1).
       01  AZ-RECORD-PTR            USAGE IS POINTER.
       01  AZ-RECORD-PTR-VALUE
           REDEFINES AZ-RECORD-PTR  PIC S9(9) COMP-5.
       01  DATA-PTR                 USAGE IS POINTER.
       01  DATA-PTR-VALUE
           REDEFINES DATA-PTR       PIC S9(9) COMP-5.
       01  DATA-AREA.
           05  RECORD-COUNT-IO OCCURS 2.
               10  RECORD-COUNT-OT  PIC 9(5) COMP-5.
               10  RECORD-COUNT-IN  PIC 9(5) COMP-5.
       01  WK-RECORD-COUNT          PIC 9(5) COMP-5.
       PROCEDURE DIVISION USING AZ-TC-WORK-AREA AZ-GRP-INDEX AZ-FLAG-IN
           AZ-RECORD-PTR.
       MAINPROC.
           SET ADDRESS OF DATA-PTR TO ADDRESS OF AZ-TC-WORK-AREA
           IF DATA-PTR-VALUE = 0
               COMPUTE DATA-SIZE = LENGTH OF WK-RECORD-COUNT * 2 * 2
               CALL BZUGTMEM USING DATA-SIZE RETURNING DATA-PTR
               SET ADDRESS OF DATA-AREA TO DATA-PTR
           END-IF
           SET AZ-RECORD-PTR TO DATA-PTR
           COMPUTE AZ-RECORD-PTR-VALUE = AZ-RECORD-PTR-VALUE +
               LENGTH OF WK-RECORD-COUNT * 2 * (AZ-GRP-INDEX - 1)
           IF AZ-FLAG-IN = 1
               ADD LENGTH OF WK-RECORD-COUNT TO AZ-RECORD-PTR-VALUE
           END-IF
           SET ADDRESS OF WK-RECORD-COUNT TO AZ-RECORD-PTR
           GOBACK.
       END PROGRAM 'GTMEMRC'.
