//* Generated by bankc.
//* Do not edit this file directly.
//TZUNITTE JOB (BANKLANG),'ZUNIT ZUNITTES',CLASS=A,MSGCLASS=X,
//             NOTIFY=&SYSUID
//* zUnit test case for ZUNITTES.
//* Source: examples/zunit-tested-posting/src/main.bank.ts
//*
//* The program under test has to be in the load library below and
//* to have been compiled with TEST. That is what the runner
//* intercepts its calls through: a program compiled without it
//* runs, and calls the real BANKLEDG and BANKAUDT.
//*
//* The compiler options are in the driver's PROCESS statement,
//* which is what Enterprise COBOL reads them from and what
//* overrides anything a site's procedure passes.
//*
//* Dataset names, unit and space parameters and the procedure
//* library are placeholders for an installation's standards.
//   JCLLIB ORDER=(BANKLANG.TAZ.PROCLIB)
//COMPILE  EXEC IGYWCL
//COBOL.SYSIN DD DISP=SHR,DSN=BANKLANG.ZUNIT.COBOL(TZUNITTE)
//LKED.SYSLMOD DD DISP=SHR,DSN=BANKLANG.TEST.LOADLIB(TZUNITTE)
//RUNNER   EXEC PROC=EQAPPLAY,COND=(4,LT),
//         BZUCFG=BANKLANG.ZUNIT.BZUCFG(TZUNITTE),
//         BZUCBK=BANKLANG.TEST.LOADLIB,
//         BZULOD=BANKLANG.TEST.LOADLIB,
//         PRM='STOP=E,REPORT=XML'
//REPLAY.BZURPT DD DISP=SHR,DSN=BANKLANG.ZUNIT.BZURES(TZUNITTE)
//REPLAY.SYSOUT DD SYSOUT=*
//REPLAY.CEEDUMP DD SYSOUT=*
