CBL ARITH(COMPAT),TRUNC(STD),NUMPROC(NOPFD),NOSSRANGE
CBL RENT,NODYNAM,QUOTE,PGMNAME(COMPAT)
      *> ---------------------------------------------------------------
      *> AMORTISA — AmortisationSchedule
      *>
      *> Generated by bankc from main.bank.ts.
      *> Do not edit this file directly. Source maps are in dist/maps.
      *>
      *> PURPOSE
      *>   BUILD-SCHEDULE, the transaction this program is entered at.
      *>
      *> ENTRY
      *>   A batch program with no parameters, started by EXEC PGM in a
      *>     job.
      *>
      *> CALLS
      *>   BANKAUDT audit trail
      *>
      *> RETURN CODES
      *>   0   The work completed.
      *>   12  A failure the program named. BANK-FAILURE-CODE says
      *>     which.
      *>
      *> RESTART
      *>   Rerunnable. The program writes no dataset.
      *> ---------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. AMORTISA.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  COMPOUND-RESULT PIC S9(16)V99 COMP-3.
       01  COMPOUND-P1          PIC S9(16)V99 COMP-3.
       01  COMPOUND-P2          PIC S9(5)V9999 COMP-3.
       01  COMPOUND-P3          PIC S9(9) COMP-3.
       01  BANK-BOUNDS-STATUS   PIC X(2) VALUE "00".
       01  BANK-COPY-INDEX      PIC 9(9) COMP.
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       01  BANK-RND-1-VALUE     PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-STEP      PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-UNITS     PIC S9(18) COMP-3.
       01  BANK-RND-1-EXCESS    PIC SV9(4) COMP-3.
       01  INSTALMENT.
           05  DUE-BALANCE          PIC S9(16)V99 COMP-3.
           05  INTEREST-DUE         PIC S9(16)V99 COMP-3.
       01  LOAN.
           05  ACCOUNT-ID           PIC X(16).
           05  PRINCIPAL            PIC S9(16)V99 COMP-3.
           05  MONTHLY-RATE         PIC S9(5)V9999 COMP-3.
           05  TERM-MONTHS          PIC S9(9) COMP-3.
           05  SCHEDULE OCCURS 36 TIMES
                   INDEXED BY SCHEDULE-IDX.
               10  DUE-BALANCE          PIC S9(16)V99 COMP-3.
               10  INTEREST-DUE         PIC S9(16)V99 COMP-3.
           05  IDEMPOTENCY-KEY      PIC X(36).
       01  INTEREST-FOR-RESULT PIC S9(16)V99 COMP-3.
       01  INTEREST-FOR-P1      PIC S9(16)V99 COMP-3.
       01  INTEREST-FOR-P2      PIC S9(5)V9999 COMP-3.
       01  RUNNING              PIC S9(16)V99 COMP-3.
       01  MONTH                PIC 9(9) COMP.
       01  BANK-LEDGER-INTERFACE.
           05  BANK-LEDGER-OPERATION    PIC X(6).
           05  BANK-LEDGER-ACCOUNT      PIC X(32).
           05  BANK-LEDGER-AMOUNT       PIC S9(16)V99 COMP-3.
       01  BANK-AUDIT-INTERFACE.
           05  BANK-AUDIT-EVENT         PIC X(32).
           05  BANK-AUDIT-CORRELATION   PIC X(64).

       PROCEDURE DIVISION.
       BANK-MAIN.
           MOVE 0 TO BANK-RETURN-CODE
           MOVE SPACES TO BANK-FAILURE-CODE
           PERFORM BUILD-SCHEDULE THRU BUILD-SCHEDULE-EXIT
           MOVE BANK-RETURN-CODE TO RETURN-CODE
           GOBACK.
       INTEREST-FOR.
           *> HALF_EVEN is generated. COBOL has
           *> only ROUNDED, which is HALF_UP.
           COMPUTE BANK-RND-1-VALUE = (INTEREST-FOR-P1 *
               INTEREST-FOR-P2)
               ON SIZE ERROR
                   DISPLAY "ARITHMETIC OVERFLOW INTEREST-FOR-RESULT"
                       UPON SYSOUT
                   MOVE 12 TO BANK-RETURN-CODE
                   MOVE "ARITHMETIC-OVERFLOW" TO BANK-FAILURE-CODE
                   GO TO INTEREST-FOR-EXIT
           END-COMPUTE
           COMPUTE BANK-RND-1-EXCESS =
               (INTEREST-FOR-P1 * INTEREST-FOR-P2) - BANK-RND-1-VALUE
           COMPUTE BANK-RND-1-STEP = 0.01
           IF BANK-RND-1-EXCESS < 0
               COMPUTE BANK-RND-1-STEP = -0.01
           END-IF
           COMPUTE BANK-RND-1-UNITS = BANK-RND-1-VALUE * 100
           EVALUATE TRUE
               WHEN FUNCTION ABS (BANK-RND-1-EXCESS) > 0.005
                   ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
               WHEN FUNCTION ABS (BANK-RND-1-EXCESS) = 0.005
                   IF FUNCTION MOD (BANK-RND-1-UNITS, 2) = 1
                       ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
                   END-IF
           END-EVALUATE
           MOVE BANK-RND-1-VALUE TO INTEREST-FOR-RESULT
           CONTINUE.
       INTEREST-FOR-EXIT.
           EXIT.
       BUILD-SCHEDULE.
           MOVE PRINCIPAL OF LOAN TO RUNNING
           PERFORM VARYING MONTH FROM 1 BY 1 UNTIL MONTH > 36
               MOVE RUNNING TO DUE-BALANCE OF LOAN (MONTH)
               MOVE RUNNING TO INTEREST-FOR-P1
               MOVE MONTHLY-RATE OF LOAN TO INTEREST-FOR-P2
               PERFORM INTEREST-FOR THRU INTEREST-FOR-EXIT
               IF BANK-FAILURE-CODE NOT = SPACES
                   GO TO BUILD-SCHEDULE-EXIT
               END-IF
               MOVE INTEREST-FOR-RESULT TO INTEREST-DUE OF LOAN (MONTH)
               MOVE RUNNING TO COMPOUND-P1
               MOVE MONTHLY-RATE OF LOAN TO COMPOUND-P2
               MOVE 1 TO COMPOUND-P3
               CALL "COMPOUND" USING COMPOUND-P1, COMPOUND-P2,
                   COMPOUND-P3, COMPOUND-RESULT
               IF BANK-FAILURE-CODE NOT = SPACES
                   GO TO BUILD-SCHEDULE-EXIT
               END-IF
               MOVE COMPOUND-RESULT TO RUNNING
           END-PERFORM
           MOVE "SCHEDULE_BUILT" TO BANK-AUDIT-EVENT
           MOVE IDEMPOTENCY-KEY OF LOAN TO BANK-AUDIT-CORRELATION
           CALL "BANKAUDT" USING BANK-AUDIT-INTERFACE
           CONTINUE.
       BUILD-SCHEDULE-EXIT.
           EXIT.
       END PROGRAM AMORTISA.

       IDENTIFICATION DIVISION.
       PROGRAM-ID. COMPOUND RECURSIVE.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BANK-FAILURE-CODE    PIC X(32) EXTERNAL.
       01  BANK-RETURN-CODE     PIC S9(4) COMP EXTERNAL.
       LOCAL-STORAGE SECTION.
       01  GROWN                PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-VALUE     PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-STEP      PIC S9(16)V99 COMP-3.
       01  BANK-RND-1-UNITS     PIC S9(18) COMP-3.
       01  BANK-RND-1-EXCESS    PIC SV9(4) COMP-3.
       01  WS-ARG-1             PIC S9(16)V99 COMP-3.
       01  WS-ARG-2             PIC S9(5)V9999 COMP-3.
       01  WS-ARG-3             PIC S9(9) COMP-3.
       01  WS-SUB-RESULT        PIC S9(16)V99 COMP-3.
       LINKAGE SECTION.
       01  LK-P1                PIC S9(16)V99 COMP-3.
       01  LK-P2                PIC S9(5)V9999 COMP-3.
       01  LK-P3                PIC S9(9) COMP-3.
       01  LK-RESULT            PIC S9(16)V99 COMP-3.

       PROCEDURE DIVISION USING LK-P1 LK-P2 LK-P3 LK-RESULT.
       COMPOUND-BODY.
           IF LK-P3 <= 0
               MOVE LK-P1 TO LK-RESULT
           ELSE
               *> HALF_EVEN is generated. COBOL has
               *> only ROUNDED, which is HALF_UP.
               COMPUTE BANK-RND-1-VALUE = (LK-P1 + (LK-P1 * LK-P2))
                   ON SIZE ERROR
                       DISPLAY "ARITHMETIC OVERFLOW GROWN" UPON SYSOUT
                       MOVE 12 TO BANK-RETURN-CODE
                       MOVE "ARITHMETIC-OVERFLOW" TO BANK-FAILURE-CODE
                       GO TO COMPOUND-EXIT
               END-COMPUTE
               COMPUTE BANK-RND-1-EXCESS =
                   (LK-P1 + (LK-P1 * LK-P2)) - BANK-RND-1-VALUE
               COMPUTE BANK-RND-1-STEP = 0.01
               IF BANK-RND-1-EXCESS < 0
                   COMPUTE BANK-RND-1-STEP = -0.01
               END-IF
               COMPUTE BANK-RND-1-UNITS = BANK-RND-1-VALUE * 100
               EVALUATE TRUE
                   WHEN FUNCTION ABS (BANK-RND-1-EXCESS) > 0.005
                       ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
                   WHEN FUNCTION ABS (BANK-RND-1-EXCESS) = 0.005
                       IF FUNCTION MOD (BANK-RND-1-UNITS, 2) = 1
                           ADD BANK-RND-1-STEP TO BANK-RND-1-VALUE
                       END-IF
               END-EVALUATE
               MOVE BANK-RND-1-VALUE TO GROWN
               MOVE GROWN TO WS-ARG-1
               MOVE LK-P2 TO WS-ARG-2
               COMPUTE WS-ARG-3 = (LK-P3 - 1)
               CALL "COMPOUND" USING WS-ARG-1, WS-ARG-2, WS-ARG-3,
                   WS-SUB-RESULT
               IF BANK-FAILURE-CODE NOT = SPACES
                   GO TO COMPOUND-EXIT
               END-IF
               MOVE WS-SUB-RESULT TO LK-RESULT
           END-IF
           CONTINUE.
       COMPOUND-EXIT.
           GOBACK.
       END PROGRAM COMPOUND.
