       *> Generated by bankc.
       *> Do not edit this file directly.
       01  POSTING-RECORD.
           05  POSTING-ACCOUNT-ID  PIC X(16).
           05  POSTING-BALANCE     PIC S9(16)V99 COMP-3.
           05  POSTING-FLAG        PIC X(1).
